Add Chinese version of README and provide saved models
PaddlePaddle/models pull request #1011
Opened 2018-06-26 02:43 UTC by zenghsh3

1. Add Chinese version of README
2. Provide saved model of Pong and Breakout game
3. Refine README
4. Refine code of saving model

2018-06-27 17:33 UTC, wanghaoshuang requested changes
请不要将模型文件提交上来。可以放到网盘，然后这里给个链接即可。

2018-06-27 17:33 UTC, wanghaoshuang commented on fluid/DeepQNetwork/README_cn.md
> +# 基于PaddlePaddle的Fluid版本复现DQN, DoubleDQN, DuelingDQN三个模型
需要说明下该model依赖的paddle版本

2018-06-27 17:33 UTC, wanghaoshuang commented on fluid/DeepQNetwork/README_cn.md
> +# 基于PaddlePaddle的Fluid版本复现DQN, DoubleDQN, DuelingDQN三个模型
排版可以优化一下，比如这里的一级标题可以改为二级标题“简介”。

2018-06-27 17:33 UTC, wanghaoshuang commented on fluid/DeepQNetwork/README_cn.md
> +## [Atari游戏介绍](https://gym.openai.com/envs/#atari)
这个就没必要写成二级标题吧？

2018-06-27 17:33 UTC, wanghaoshuang commented on fluid/DeepQNetwork/README_cn.md
> ++ Pong游戏训练结果
可以简要介绍下这个图表的含义。

2018-06-27 19:52 UTC, yu239 commented on fluid/DeepQNetwork/README_cn.md
> ++ 测试模型：
Larger fonts?

2018-06-27 19:55 UTC, yu239 commented on fluid/DeepQNetwork/README.md
> +    To train more games, can install more rom files from [here](https://github.com/openai/atari-py/tree/master/atari_py/atari_roms)
Maybe also document the training time to give the users a rough idea?

2018-06-27 19:55 UTC, yu239-zz submitted a review, later dismissed
some minor things

2018-06-28 02:29 UTC, zenghsh3 commented on fluid/DeepQNetwork/README_cn.md
> +# 基于PaddlePaddle的Fluid版本复现DQN, DoubleDQN, DuelingDQN三个模型
在下面依赖中有说明paddle的版本要求：paddlepaddle-gpu>=0.12.0

2018-06-28 03:11 UTC, zenghsh3 commented on fluid/DeepQNetwork/README_cn.md
> +# 基于PaddlePaddle的Fluid版本复现DQN, DoubleDQN, DuelingDQN三个模型
done

2018-06-28 03:11 UTC, zenghsh3 commented on fluid/DeepQNetwork/README_cn.md
> +## [Atari游戏介绍](https://gym.openai.com/envs/#atari)
done

2018-06-28 03:11 UTC, zenghsh3 commented on fluid/DeepQNetwork/README_cn.md
> ++ Pong游戏训练结果
done

2018-06-28 03:11 UTC, zenghsh3 commented on fluid/DeepQNetwork/README_cn.md
> ++ 测试模型：
done

2018-06-28 03:26 UTC, zenghsh3 commented on fluid/DeepQNetwork/README.md
> +    To train more games, can install more rom files from [here](https://github.com/openai/atari-py/tree/master/atari_py/atari_roms)
done

2018-06-28 04:15 UTC, kuke commented
如果要开放模型，可以放在百度云上，paddle有公共账号，如有需要可以hi我们

2018-06-28 04:16 UTC, kuke reviewed
如果要开放模型，不推荐放在repo里。可以放在百度云上，paddle有公共账号，如有需要可以hi我们

2018-06-28 04:25 UTC, zenghsh3 commented
repo中没有放保存好的模型了，已经改用提供百度云链接的方式：https://github.com/PaddlePaddle/models/pull/1011/commits/c1f95cd267c6d4abf585449790ddfb712404d4e3

2018-06-29 08:47 UTC, wanghaoshuang approved these changes
LGTM

2018-06-29 09:12 UTC, kuke commented
Due to the limited time, we are going to merge this pull request first to have a tiny adjustment on the format.

2018-06-29 09:14 UTC, kuke commented
Thanks for everyone's contribution!

2018-06-29 09:14 UTC, merged