Improve audio featurizer and add shift augmentor for DS2.
PaddlePaddle/models pull request #114
Opened 2017-06-21 12:59 UTC by xinghai-sun

resolve #113

1. Improve audio featurizer (resample, db_normalize, and random shift).
2. Add shift augmentor.
3. Update default argument to be the current best seggestion.
4. Add checkpoints with pass id.

2017-06-21 13:03 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +    def slice_from_file(cls, file, start=None, end=None):
@reviewers:
No different for `slice_from_file` and `make_silence`. Only re-order the methods.

2017-06-21 13:35 UTC, pkuyym requested changes
Almost LGTM.

2017-06-21 13:35 UTC, pkuyym commented on deep_speech_2/data_utils/audio.py
> +        if shift_ms / 1000.0 > self.duration:
Should be ```abs(shift_ms)``` ?

2017-06-21 13:35 UTC, pkuyym commented on deep_speech_2/data_utils/featurizer/audio_featurizer.py
> +                                 decibels before extracting the features.
Better to change **decibels** to **dB** for consistency

2017-06-21 13:35 UTC, pkuyym commented on deep_speech_2/data_utils/featurizer/audio_featurizer.py
> +        # decibel normalization
dB better ?

2017-06-21 13:35 UTC, pkuyym commented on deep_speech_2/data_utils/featurizer/speech_featurizer.py
> +    :param target_dB: Target audio decibels for normalization.
dB better?

2017-06-26 05:06 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        if shift_ms / 1000.0 > self.duration:
Done.

2017-06-26 05:06 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        if shift_ms / 1000.0 > self.duration:
Done.

2017-06-26 05:06 UTC, xinghai-sun commented on deep_speech_2/data_utils/featurizer/audio_featurizer.py
> +                                 decibels before extracting the features.
For comments, full name `decibels` is used for clarity, while in arguments a short name of `dB` is used instead.
I think it makes sense?

2017-06-26 05:06 UTC, xinghai-sun commented on deep_speech_2/data_utils/featurizer/audio_featurizer.py
> +        # decibel normalization
For comments, full name `decibels` is used for clarity, while in arguments a short name of `dB` is used instead.
I think it makes sense?

2017-06-26 05:06 UTC, xinghai-sun commented on deep_speech_2/data_utils/featurizer/speech_featurizer.py
> +    :param target_dB: Target audio decibels for normalization.
For comments, full name `decibels` is used for clarity, while in arguments a short name of `dB` is used instead.
I think it makes sense?

2017-06-26 05:10 UTC, pkuyym approved these changes
Great. LGTM.

2017-06-26 05:15 UTC, xinghai-sun commented
The experimental results for comparing old and new featurizer are as follows. We have a better convergence with the new featurizer.

![compare_old_new_data](https://user-images.githubusercontent.com/7038341/27525562-6d7e2cb0-5a71-11e7-8fef-03a62ad9ee2b.png)

2017-06-26 06:24 UTC, merged

2021-02-24 14:31 UTC, jeff41404 commented
看issue中的报错截图，是 x = paddle.randn([1, 768], 'int64') 写错了，如果要用int64，应该改成 x = paddle.randint(low=0, high=255, shape=[1, 768], dtype='int64') 这种形式（注意这里low和high的数字是示例，请根据实际情况修改）
![image](https://user-images.githubusercontent.com/8555991/109015200-d784d480-76ef-11eb-8787-7e66694f64ac.png)

2021-02-25 10:14 UTC, geekChinaMaster commented
> 看issue中的报错截图，是 x = paddle.randn([1, 768], 'int64') 写错了，如果要用int64，应该改成 x = paddle.randint(low=0, high=255, shape=[1, 768], dtype='int64') 这种形式（注意这里low和high的数字是示例，请根据实际情况修改）
> ![image](https://user-images.githubusercontent.com/8555991/109015200-d784d480-76ef-11eb-8787-7e66694f64ac.png)

这里修改了之后还是有报错
![图片](https://user-images.githubusercontent.com/44657953/109138191-0f922300-7795-11eb-8f4e-ed51c85d008b.png)