Update CE.
PaddlePaddle/models pull request #1153
Opened 2018-08-16 07:17 UTC by qingqing01

2018-08-20 05:22 UTC, baiyfbupt approved these changes
LGTM

2018-08-20 05:26 UTC, baiyfbupt commented on fluid/image_classification/_ce.py
> +train_acc_top1_kpi = AccKpi('train_acc_top1', 0.005, 0, desc='TOP1 ACC')
这里是否也需要`actived=True`?

2018-08-20 05:26 UTC, guochaorong requested changes
调稳定了再打开监控~

2018-08-21 10:49 UTC, velconia reviewed
LGTM in Python3 changes, @guochaorong please check the part of CE changes

2018-08-24 23:41 UTC, guochaorong approved these changes

2018-08-24 23:41 UTC, merged