Init demo.
PaddlePaddle/models pull request #137
Opened 2017-06-28 15:20 UTC by pkuyym

resolves #136

2017-07-08 03:20 UTC, luotao1 requested changes

2017-07-08 03:20 UTC, luotao1 commented on ssd/README.md
> +SSD使用一个卷积神经网络实现“端到端”的检测，所谓“端到端”指输入为原始图像，输出为检测结果，无需借助外部工具或流程进行特征提取、候选框生成等。论文中SSD的基础模型为VGG-16，其在VGG-16的某些层后面增加了一些额外的层进行候选框的提取，下图为模型的总体结构：
其在->且在？

2017-07-08 03:20 UTC, luotao1 commented on ssd/README.md
> +图1. SSD网络结构
1. 图过小，里面的英文字都看不清楚。
2. 图中的英文字能翻译成中文么，不然小白用户还是看不懂。

2017-07-08 03:20 UTC, luotao1 commented on ssd/README.md
> +如图所示，候选框的生成规则是预先设定的，比如Conv7输出的特征图每个像素点会对应6个候选框，这些候选框长宽比或面积有区分。在预测阶段模型会对这些提取出来的候选框做后处理，然后输出作为最终的检测结果。
图的解释可以多一点。12行我看的不是很明白。
1. 生成规则是预先设定的，从图中的哪儿可以看出来？
2. Conv7对应的6个候选框分别是图中的哪儿？也可能是图比较小，我没找到Conv7
3. 后处理是指什么？是一个专有名词么

2017-07-08 03:20 UTC, luotao1 commented on ssd/README.md
> +<center>表1. 示例文件</center>
表名一般放在表格的上方，图名一般放在图的下方，请修改下位置。

2017-07-08 03:20 UTC, luotao1 commented on ssd/README.md
> +训练阶段需要对数据做预处理，包括裁剪、采样等，这部分操作在```image_util.py```和```data_provider.py```中完成；值得注意的是，```config/vgg_config.py```为参数配置文件，包括训练参数、神经网络参数等，本配置文件包含参数是针对PASCAL VOC数据配置的，当训练自有数据时，需要仿照该文件配置新的参数；```data/prepare_v
32行中的分号都改成句号。

2017-07-08 03:20 UTC, luotao1 commented on ssd/README.md
> +首先需要下载数据集，VOC2007\[[2](#引用)\]和VOC2012\[[3](#引用)\]，VOC2007包含训练集和测试集，VOC2012只包含训练集，将下载好的数据解压，目录结构为```VOCdevkit/{VOC2007，VOC2012}```。进入```data```目录，运行```python prepare_voc_data.py```即可生成```trainval.txt`
可以贴对应的代码，怎么进行数据准备。

2017-07-08 03:20 UTC, luotao1 commented on ssd/README.md
> +下载预训练的VGG-16模型，我们提供了一个转换好的模型，具体下载地址为：，下载好模型后，放置路径为```vgg/vgg_model.tar.gz```。
具体下载地址为，后面是空的，是以后补上么

2017-07-08 03:20 UTC, luotao1 commented on ssd/README.md
> +直接执行```python train.py```即可进行训练。需要注意本示例仅支持CUDA GPU环境，无法在CPU上训练。```train.py```的一些关键执行逻辑：
为什么无法在CPU上训练，能否简单讲一下原因。CPU部分是后续要集成么

2017-07-08 03:20 UTC, luotao1 commented on ssd/README.md
> +调用```paddle.init```指定使用4卡GPU训练；调用```data_provider.Settings```配置数据预处理所需参数，其中```cfg.IMG_HEIGHT```和```cfg.IMG_WIDTH```在配置文件```config/vgg_config.py```中设置，这里均为300；调用```train```执行训练，其中```train_file_list```
1. 为什么均为300，是和论文保持统一么？
2. mAP是什么？
3. 需事先创建，现在的代码是没有创建，就无法保存么 @qingqing01

2017-07-08 03:20 UTC, luotao1 commented on ssd/README.md
> +1. Liu, Wei, et al. "SSD: Single shot multibox detector." European conference on computer vision. Springer, Cham, 2016.
请放论文链接地址，论文作者可以多列几个。

2017-07-08 03:20 UTC, luotao1 commented on ssd/README.md
> +2. http://host.robots.ox.ac.uk/pascal/VOC/voc2007/index.html
这里应该放 The PASCAL Visual Object Classes Challenge 2007，然后带155行的链接。下同。

2017-07-17 05:00 UTC, pkuyym reviewed
Follow comments and reorganize SSD introduction section.

2017-07-17 05:00 UTC, pkuyym commented on ssd/README.md
> +SSD使用一个卷积神经网络实现“端到端”的检测，所谓“端到端”指输入为原始图像，输出为检测结果，无需借助外部工具或流程进行特征提取、候选框生成等。论文中SSD的基础模型为VGG-16，其在VGG-16的某些层后面增加了一些额外的层进行候选框的提取，下图为模型的总体结构：
Done

2017-07-17 05:00 UTC, pkuyym commented on ssd/README.md
> +<center>表1. 示例文件</center>
Done.

2017-07-17 05:00 UTC, pkuyym commented on ssd/README.md
> +训练阶段需要对数据做预处理，包括裁剪、采样等，这部分操作在```image_util.py```和```data_provider.py```中完成；值得注意的是，```config/vgg_config.py```为参数配置文件，包括训练参数、神经网络参数等，本配置文件包含参数是针对PASCAL VOC数据配置的，当训练自有数据时，需要仿照该文件配置新的参数；```data/prepare_v
Done

2017-07-17 05:00 UTC, pkuyym commented on ssd/README.md
> +首先需要下载数据集，VOC2007\[[2](#引用)\]和VOC2012\[[3](#引用)\]，VOC2007包含训练集和测试集，VOC2012只包含训练集，将下载好的数据解压，目录结构为```VOCdevkit/{VOC2007，VOC2012}```。进入```data```目录，运行```python prepare_voc_data.py```即可生成```trainval.txt`
Done

2017-07-17 05:00 UTC, pkuyym commented on ssd/README.md
> +直接执行```python train.py```即可进行训练。需要注意本示例仅支持CUDA GPU环境，无法在CPU上训练。```train.py```的一些关键执行逻辑：
主要是CPU的训练比较慢，图像任务一般都使用GPU，这里的实现采用硬编码方式使用cuDNN，后续不打算集成CPU版本

2017-07-17 05:00 UTC, pkuyym commented on ssd/README.md
> +调用```paddle.init```指定使用4卡GPU训练；调用```data_provider.Settings```配置数据预处理所需参数，其中```cfg.IMG_HEIGHT```和```cfg.IMG_WIDTH```在配置文件```config/vgg_config.py```中设置，这里均为300；调用```train```执行训练，其中```train_file_list```
1. 300x300是论文中比较典型的一个配置，也包含512*512，用户可自行修改配置实现
2. mAP是指mean average precision，是物体检测领域常用的评测指标
3. 应该是需要要求目录已经存在的

2017-07-17 05:00 UTC, pkuyym commented on ssd/README.md
> +1. Liu, Wei, et al. "SSD: Single shot multibox detector." European conference on computer vision. Springer, Cham, 2016.
Done

2017-07-17 05:00 UTC, pkuyym commented on ssd/README.md
> +2. http://host.robots.ox.ac.uk/pascal/VOC/voc2007/index.html
Done

2017-07-17 05:00 UTC, pkuyym commented on ssd/README.md
> +图1. SSD网络结构
重新梳理了这一部分

2017-07-17 05:00 UTC, pkuyym commented on ssd/README.md
> +如图所示，候选框的生成规则是预先设定的，比如Conv7输出的特征图每个像素点会对应6个候选框，这些候选框长宽比或面积有区分。在预测阶段模型会对这些提取出来的候选框做后处理，然后输出作为最终的检测结果。
重新梳理了这一部分

2017-07-17 05:00 UTC, pkuyym commented on ssd/README.md
> +下载预训练的VGG-16模型，我们提供了一个转换好的模型，具体下载地址为：，下载好模型后，放置路径为```vgg/vgg_model.tar.gz```。
最后会补上这个链接，Mark一下

2017-07-17 06:14 UTC, luotao1 commented on ssd/README.md
> +SSD使用一个卷积神经网络实现“端到端”的检测，所谓“端到端”指输入为原始图像，输出为检测结果，无需借助外部工具或流程进行特征提取、候选框生成等。论文中SSD的基础模型为VGG16\[[2](#引用)\]，不同于原始VGG16网络模型，SSD做了一些改变：1. 将最后的FC6、FC7全连接层变为卷积层，卷积层参数通过对原始FC6、FC7参数采样得到； 2. 将Pool5层的参数由2x2-s2（k
1,2,3点写成如下格式，会更清爽
1. XXX
2. XXX
3. XXX

2017-07-17 06:14 UTC, luotao1 commented on ssd/README.md
> +VOCdevkit/VOC2007/JPEGImages/000023.jpg VOCdevkit/VOC2007/Annotations/000023.xml
这里列的太多了，列个2-3行就够了

2017-07-17 06:14 UTC, luotao1 commented on ssd/README.md
> +3. The PASCAL Visual Object Classes Challenge 2007. http://host.robots.ox.ac.uk/pascal/VOC/voc2007/index.html
1. 改成这种格式，下同：[The PASCAL Visual Object Classes Challenge 2007](http://host.robots.ox.ac.uk/pascal/VOC/voc2007/index.html).
2. 前面两篇也加下链接地址

2017-07-17 06:18 UTC, luotao1 commented on ssd/README.md
> +直接执行```python train.py```即可进行训练。需要注意本示例仅支持CUDA GPU环境，无法在CPU上训练。```train.py```的一些关键执行逻辑：
> 主要是CPU的训练比较慢，图像任务一般都使用GPU，这里的实现采用硬编码方式使用cuDNN，后续不打算集成CPU版本

可将回复的这段话加入文中。

2017-07-17 06:18 UTC, luotao1 commented on ssd/README.md
> +调用```paddle.init```指定使用4卡GPU训练；调用```data_provider.Settings```配置数据预处理所需参数，其中```cfg.IMG_HEIGHT```和```cfg.IMG_WIDTH```在配置文件```config/vgg_config.py```中设置，这里均为300；调用```train```执行训练，其中```train_file_list```
可将回复的3点加入文中。

2017-07-17 06:44 UTC, pkuyym reviewed
Follow comments.

2017-07-17 06:44 UTC, pkuyym commented on ssd/README.md
> +VOCdevkit/VOC2007/JPEGImages/000023.jpg VOCdevkit/VOC2007/Annotations/000023.xml
Done.

2017-07-17 06:44 UTC, pkuyym commented on ssd/README.md
> +直接执行```python train.py```即可进行训练。需要注意本示例仅支持CUDA GPU环境，无法在CPU上训练。```train.py```的一些关键执行逻辑：
Done

2017-07-17 06:44 UTC, pkuyym commented on ssd/README.md
> +调用```paddle.init```指定使用4卡GPU训练；调用```data_provider.Settings```配置数据预处理所需参数，其中```cfg.IMG_HEIGHT```和```cfg.IMG_WIDTH```在配置文件```config/vgg_config.py```中设置，这里均为300；调用```train```执行训练，其中```train_file_list```
Done.

2017-07-17 07:45 UTC, luotao1 commented on ssd/README.md
> +2. 将pool5层的参数由2x2-s2（kernel大小为2x2，stride size为2）更改为3x3-s1-p1（kernel大小为3x3，stride size为1，padding size为1）
1和2后面加句号。

2017-07-17 07:45 UTC, luotao1 commented on ssd/README.md
> +1. [Wei Liu, Dragomir Anguelov, Dumitru Erhan, Christian Szegedy, Scott Reed, Cheng-Yang Fu, Alexander C. Berg. "SSD: Single shot multibox detector." European conference on computer vision. Springer,
1. Wei Liu, Dragomir Anguelov, Dumitru Erhan, Christian Szegedy, Scott Reed, Cheng-Yang Fu, Alexander C. Berg. [SSD: Single shot multibox detector](https://arxiv.org/abs/1512.02325). European conference on computer vision. Springer, Cham, 2016.
2. Simonyan, Karen, and Andrew Zisserman. [Very deep convolutional networks for large-scale image recognition](https://arxiv.org/abs/1409.1556). arXiv preprint arXiv:1409.1556 (2014).

2017-07-17 07:45 UTC, luotao1 commented on ssd/README.md
> +调用```paddle.init```指定使用4卡GPU训练；调用```data_provider.Settings```配置数据预处理所需参数，其中```cfg.IMG_HEIGHT```和```cfg.IMG_WIDTH```在配置文件```config/vgg_config.py```中设置，这里均为300，300x300是一个典型配置，兼顾效率和检测精度，也可以通过修改配置文件扩展到50
由于这段内容较多，分点进行描述会清楚，可改成如下：
- 调用```paddle.init```指定使用4卡GPU训练。
- 调用```data_provider.Settings```配置数据预处理所需参数，其中```cfg.IMG_HEIGHT```和```cfg.IMG_WIDTH```在配置文件```config/vgg_config.py```中设置，这里均为300。300x300是一个典型配置，兼顾效率和检测精度，也可以通过修改配置文件扩展到500x500。
- 调用```train```执行训练，其中```train_file_list```指定训练数据列表，```dev_file_list```指定评估数据列表，```init_model_path```指定预训练模型位置。
- 训练过程中会打印一些日志信息，每训练10个batch会输出当前的轮数、当前batch的cost及mAP（mean Average Precision），每训练一个pass，会保存一次模型，默认保存在```checkpoints```目录下（注：需事先创建）。

mAP的括号里加个中文名词，是平均精度的意思么？

2017-07-17 07:45 UTC, luotao1 commented on ssd/README.md
> +3. 在conv4\_3、conv7、conv8\_2、conv9\_2、conv10\_2及pool11层后面接了priorbox层，priorbox层的主要目的是根据输入的feature map生成一系列的矩形候选框。关于SSD的更详细的介绍可以参考论文\[[1](#引用)\]。下图为模型（300x300）的总体结构：
> 关于SSD的更详细的介绍可以参考论文\[[1](#引用)\]。下图为模型（300x300）的总体结构：

这句不在第3点内，应该换行写。

2017-07-17 07:45 UTC, luotao1 commented on ssd/README.md
> +## SSD原理
1. SSD原理部分够清楚了么 @qingqing01 @lcy-seso  ，还需要更详细一点么？
2. 概述中写了：SSD的检测速度快且检测精度高，文章中需要简单介绍为什么在VGG16上做了这些改变后，就速度快且精度高了呢？

2017-07-18 02:43 UTC, pkuyym reviewed
Follow comments and add more introduction information for SSD.

2017-07-18 02:43 UTC, pkuyym commented on ssd/README.md
> +2. 将pool5层的参数由2x2-s2（kernel大小为2x2，stride size为2）更改为3x3-s1-p1（kernel大小为3x3，stride size为1，padding size为1）
Done

2017-07-18 02:43 UTC, pkuyym commented on ssd/README.md
> +3. 在conv4\_3、conv7、conv8\_2、conv9\_2、conv10\_2及pool11层后面接了priorbox层，priorbox层的主要目的是根据输入的feature map生成一系列的矩形候选框。关于SSD的更详细的介绍可以参考论文\[[1](#引用)\]。下图为模型（300x300）的总体结构：
Done

2017-07-18 02:43 UTC, pkuyym commented on ssd/README.md
> +调用```paddle.init```指定使用4卡GPU训练；调用```data_provider.Settings```配置数据预处理所需参数，其中```cfg.IMG_HEIGHT```和```cfg.IMG_WIDTH```在配置文件```config/vgg_config.py```中设置，这里均为300，300x300是一个典型配置，兼顾效率和检测精度，也可以通过修改配置文件扩展到50
Done.

2017-07-18 02:43 UTC, pkuyym commented on ssd/README.md
> +1. [Wei Liu, Dragomir Anguelov, Dumitru Erhan, Christian Szegedy, Scott Reed, Cheng-Yang Fu, Alexander C. Berg. "SSD: Single shot multibox detector." European conference on computer vision. Springer,
Done.

2017-07-18 02:43 UTC, pkuyym commented on ssd/README.md
> +## SSD原理
Done.

2017-07-18 07:47 UTC, luotao1 approved these changes
LGTM

2017-07-18 15:48 UTC, qingqing01 commented on ssd/README.md
> +从SSD的网络结构可以看出，候选矩形框在多个feature map上生成，不同的feature map具有的感受野不同，这样可以在不同尺度扫描图像，相对于其他检测方法可以生成更丰富的候选框，从而提高检测精度；另一方面SSD对VGG16的扩展部分以较小的代价实现对候选框的位置和类别得分的计算，整个过程只需要一个卷积神经网络完成，所以速度较快。
feature map -> 特征图(feature map)

2017-07-18 15:48 UTC, qingqing01 commented on ssd/README.md
> +该函数首先对每个year的数据进行处理，然后将训练图像的文件路径列表进行随机打乱，最后保存训练文件列表和测试文件列表。默认```prepare_voc_data.py```和```VOCdevkit```在相同目录下，且生成的文件列表也在该目录。需注意```trainval.txt```既包含VOC2007的训练数据，也包含VOC2012的训练数据，```test.txt```只包含VOC200
每个year -> 每一年(year)

2017-07-18 15:48 UTC, qingqing01 commented on ssd/README.md
> +
最好加上mAP曲线图~

2017-07-18 15:48 UTC, qingqing01 commented on ssd/README.md
> +
可以给出一张可视化图~

2017-07-18 15:48 UTC, qingqing01 commented on ssd/README.md
> +    save_path='infer.res',
可以给出infer.res结果样例~

2017-07-18 15:48 UTC, qingqing01 commented on ssd/data/prepare_voc_data.py
> +    return osp.join(devkit_dir, 'VOC' + year, 'ImageSets/Main')
上面3个函数一样，可以合成一个：

```
def get_dir(devkit_dir, year, field):
    return osp.join(devkit_dir, 'VOC' + year,  field)
```

field 可以是：'JPEGImages', 'Annotations', 'ImageSets/Main'

2017-07-18 15:48 UTC, qingqing01 commented on ssd/data_provider.py
> +        self._img_mean = self._img_mean.astype('float32')
line:36 - line:42可以删除，写成：

self._mean_value =  self._mean_value[:, np.newaxis, np.newaxis].astype('float32')

2017-07-18 15:48 UTC, qingqing01 commented on ssd/image_util.py
> +    return pic.flatten()
这个函数没用就删掉~

2017-07-18 15:48 UTC, qingqing01 commented on ssd/image_util.py
> +    return width * height
bboxSize -> bbox_area ?

2017-07-18 15:48 UTC, qingqing01 commented on ssd/image_util.py
> +def generateSample(sampler):
generateSample -> generate_sample

2017-07-18 15:48 UTC, qingqing01 commented on ssd/image_util.py
> +def jaccardOverlap(sample_bbox, object_bbox):
jaccardOverlap -> jaccard_overlap

下面几个函数也是~

2017-07-18 15:48 UTC, qingqing01 commented on ssd/infer.py
> +    detect_out = vgg_net_ssd_v2.net_conf(mode='infer')
Where is the `vgg_net_ssd_v2` ?

2017-07-18 15:48 UTC, qingqing01 commented on ssd/infer.py
> +                           str(xmax) + ' ' + str(ymax) + '\n')
line:75 - line:86和上面重复，可以抽出来一个 batch_infer函数，两处调用，减少重复代码。

2017-07-18 15:48 UTC, qingqing01 commented on ssd/train.py
> +            parameters.set(param_name, fparams.get(param_name))
请使用`init_from_tar`接口~

2017-07-18 15:48 UTC, qingqing01 commented on ssd/train.py
> +    optimizer = paddle.optimizer.Momentum(
optimizer设置放在 `cost, detect_out = vgg_ssd_net.net_conf('train')` 之前吧，避免momentum没有起作用~

2017-07-18 15:48 UTC, qingqing01 commented on ssd/train.py
> +        paddle.reader.shuffle(
reader里已经设置了shuffle，这块的shuffle觉得可以去掉吧~

2017-07-18 15:48 UTC, qingqing01 commented on ssd/vgg_ssd_net.py
> +    def xavier(channels, filter_size, local_lr, regularization):
有pre-trained的模型初始化，觉得可以去掉`xavier`，而且采用默认的`msra`初始化方式即可~

2017-07-18 15:48 UTC, qingqing01 commented on ssd/vgg_ssd_net.py
> +            num_channels=num_filters,
这行可以去掉~

2017-07-18 15:48 UTC, qingqing01 commented on ssd/vgg_ssd_net.py
> +            num_channels=num_filters,
这行可去掉~

2017-07-18 15:48 UTC, qingqing01 commented on ssd/vgg_ssd_net.py
> +            num_channels=num_filters,
去掉这行

2017-07-18 15:48 UTC, qingqing01 commented on ssd/vgg_ssd_net.py
> +        num_channels=64,
num_channels除过第一个conv需要设置外，后面的conv可以不用设置的~

2017-07-18 15:48 UTC, qingqing01 commented on ssd/vgg_ssd_net.py
> +        stride=2)
[`img_conv_group`](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/networks.py#L333)可以用来简化上面配置。 但是参数名字可能会变化，导致无法加载初始化模型。

但也可以封装下conv层，让上面配置简单一些，每个conv都写一堆参数，导致配置比较长，不够简洁~

2017-08-11 03:00 UTC, pkuyym commented on ssd/image_util.py
> +    return width * height
Done.

2017-08-11 03:00 UTC, pkuyym commented on ssd/image_util.py
> +    return pic.flatten()
Done.

2017-08-11 03:00 UTC, pkuyym commented on ssd/image_util.py
> +def generateSample(sampler):
Done.

2017-08-11 03:00 UTC, pkuyym commented on ssd/image_util.py
> +def jaccardOverlap(sample_bbox, object_bbox):
Done.

2017-08-11 03:00 UTC, pkuyym commented on ssd/infer.py
> +    detect_out = vgg_net_ssd_v2.net_conf(mode='infer')
Done.

2017-08-11 03:00 UTC, pkuyym commented on ssd/train.py
> +    optimizer = paddle.optimizer.Momentum(
Done.

2017-08-11 03:00 UTC, pkuyym commented on ssd/train.py
> +        paddle.reader.shuffle(
Done.

2017-08-11 03:00 UTC, pkuyym commented on ssd/vgg_ssd_net.py
> +    def xavier(channels, filter_size, local_lr, regularization):
Done.

2017-08-11 03:00 UTC, pkuyym commented on ssd/vgg_ssd_net.py
> +        stride=2)
封装了conv_group，简化配置

2017-08-11 03:00 UTC, pkuyym commented on ssd/vgg_ssd_net.py
> +        num_channels=64,
封装了conv_group，简化配置

2017-08-11 03:00 UTC, pkuyym commented on ssd/vgg_ssd_net.py
> +            num_channels=num_filters,
封装了conv_group，简化配置

2017-08-11 03:00 UTC, pkuyym commented on ssd/vgg_ssd_net.py
> +            num_channels=num_filters,
封装了conv_group，简化配置

2017-08-11 03:00 UTC, pkuyym commented on ssd/vgg_ssd_net.py
> +            num_channels=num_filters,
封装了conv_group，简化配置

2017-08-11 03:00 UTC, pkuyym commented on ssd/train.py
> +            parameters.set(param_name, fparams.get(param_name))
Done.

2017-08-11 03:00 UTC, pkuyym commented on ssd/infer.py
> +                           str(xmax) + ' ' + str(ymax) + '\n')
Done.

2017-08-11 03:00 UTC, pkuyym commented on ssd/data_provider.py
> +        self._img_mean = self._img_mean.astype('float32')
Done.

2017-08-11 03:00 UTC, pkuyym commented on ssd/data/prepare_voc_data.py
> +    return osp.join(devkit_dir, 'VOC' + year, 'ImageSets/Main')
Done.

2017-08-11 03:00 UTC, pkuyym commented on ssd/README.md
> +从SSD的网络结构可以看出，候选矩形框在多个feature map上生成，不同的feature map具有的感受野不同，这样可以在不同尺度扫描图像，相对于其他检测方法可以生成更丰富的候选框，从而提高检测精度；另一方面SSD对VGG16的扩展部分以较小的代价实现对候选框的位置和类别得分的计算，整个过程只需要一个卷积神经网络完成，所以速度较快。
Done

2017-08-11 03:00 UTC, pkuyym commented on ssd/README.md
> +该函数首先对每个year的数据进行处理，然后将训练图像的文件路径列表进行随机打乱，最后保存训练文件列表和测试文件列表。默认```prepare_voc_data.py```和```VOCdevkit```在相同目录下，且生成的文件列表也在该目录。需注意```trainval.txt```既包含VOC2007的训练数据，也包含VOC2012的训练数据，```test.txt```只包含VOC200
Done

2017-08-11 03:00 UTC, pkuyym commented on ssd/README.md
> +
Done.

2017-08-11 03:00 UTC, pkuyym commented on ssd/README.md
> +    save_path='infer.res',
Done

2017-08-11 03:00 UTC, pkuyym commented on ssd/README.md
> +
Done

2017-08-11 05:00 UTC, qingqing01 approved these changes

2017-08-11 05:00 UTC, merged