refactor ctr model
PaddlePaddle/models pull request #138
Opened 2017-06-29 02:07 UTC by Superjom

修改如下：

1. 模型和示例数据的格式解耦，现在用户只需要准备对应格式的数据，不需要修改代码就可以直接训练和预测
2. 添加预测脚本 `infer.py`
3. 支持 classification, regression 两种任务类型，可通过命令行参数控制

2017-07-05 04:13 UTC, lcy-seso requested changes

2017-07-05 04:13 UTC, lcy-seso commented on ctr/README.md
>  CTR(Click-Through Rate，点击率预估)\[[1](https://en.wikipedia.org/wiki/Click-through_rate)\] 是用来表示用户点击一个特定链接的概率，
1. 第一句话：是用来表示用户点击一个特定链接的概率 ，通常被用来衡量一个在线广告系统的有效性。--> 是对用户点击一个特定链接的概率做出预测，是广告投放过程中的一个重要环节。精准的点击率预估对在线广告系统收益最大化具有重要意义。
2. 11 行，from @llxxxll "召回"这个词对基础用户比较陌生，解释或者再用其他方式描述一下。
3. 这一篇分段过于细碎，第23，24 行全部合在第一段中。
4. 第24行“系统大体上会执行下列步骤来展示广告” --> 粗略来讲，系统会执行下列步骤展示广告：
5. 31 行去掉 “很”，很重要 --> 重要。
6. 53 ~ 62 行合并为一段。

2017-07-05 04:13 UTC, lcy-seso commented on ctr/README.md
> +
1. 69 行`click` 是指点击率吗？在69行时还没有介绍数据，这里还无法和数据中的 `click` 字段关联上，说明更清楚一些吧。
2. 79 和 81 合为一段。
3. 81 行之后，可否用文字再进一步描述解释一下格式。

2017-07-05 04:13 UTC, lcy-seso commented on ctr/README.md
> +具体的特征处理方法参看 [data process](./dataset.md)。
77 行 我们使用 Kaggle 上 `Click-through rate prediction` 任务的数据集来演示模型。 --> 我们使用 Kaggle 上 `Click-through rate prediction` 任务的数据集来运行本例中的模型。

2017-07-05 04:13 UTC, lcy-seso commented on ctr/README.md
> +演示数据集\[[2](#参考文档)\] 可以使用 `avazu_data_processor.py` 脚本处理，具体使用方法参考如下说明：
本例目录下的`avazu_data_processor.py` 脚本可以对下载的原始数据进行处理，具体使用方法参考如下说明：

2017-07-05 04:13 UTC, lcy-seso commented on ctr/README.md
> +└── utils.py           # helper functions
- 这里没有 `avazu_data_processor.py`  这个文件，是刻意的吗？这个文件也挺重要的。
- images 目录是可以简单地省略。

2017-07-05 04:13 UTC, lcy-seso commented on ctr/README.md
> +├── reader.py          # data provider
data provider --> data reader，v2 之后很少提 data provider 的概念了。

2017-07-05 04:13 UTC, lcy-seso commented on ctr/README.md
> +```
91 ~ 112 行，（1）用 list 的形式；（2）写一句简要的中文说明来解释重要的参数。

2017-07-05 04:13 UTC, lcy-seso commented on ctr/README.md
> +    3. `mkdir -p output; python avazu_data_processer.py --data_path train.txt --output_dir output --num_lines_to_detect 1000 --test_set_size 100` 生成演示数据
- 251 行：下载训练数据，可以使用 Kaggle 上 CTR 比赛的数据\[[2](#参考文献)\] --> 准备训练数据。
    - 上文已经介绍本例使用 Kaggle CTR 比赛数据运行本例，这里简单说明即可。

2017-07-05 04:13 UTC, lcy-seso commented on ctr/README.md
> +```
用文字描述一下数据格式。

2017-07-05 04:13 UTC, lcy-seso commented on ctr/avazu_data_processer.py
> +We will treat following fields as categorical features:
following fields --> following fields

2017-07-05 04:13 UTC, lcy-seso commented on ctr/network_conf.py
> +            name='lr',
- `name` 是必须的吗？如果没有显示地引用名字，删掉`name`。
- Paddle目前官方的demo 除了data_layer 必须有名字之外，都没有指定名字，保持例子风格的一致。

2017-07-05 04:13 UTC, lcy-seso commented on ctr/network_conf.py
> +            name='output',
同上，去掉`name`

2017-07-05 04:13 UTC, lcy-seso commented on ctr/network_conf.py
> +# -*- coding: utf-8 -*-
有些脚本加了 shebang，保持一致，或者都删掉，或者都加上。

2017-07-05 04:13 UTC, lcy-seso commented on ctr/utils.py
> +logger = logging.getLogger("logger")
- 可以直接 `logging.getLogger("paddle")` 获取 `config_parser.py` 中的logger。

2017-07-05 04:13 UTC, lcy-seso commented on ctr/train.py
> +
如果是不需要的注释，就删掉吧。

2017-07-05 04:13 UTC, lcy-seso commented on ctr/avazu_data_processer.py
> +
不需要的注释就删掉。

2017-07-17 01:26 UTC, Superjom commented
运行训练和测试 有问题，需要check

2017-07-17 07:16 UTC, Superjom commented on ctr/README.md
> +```
done

2017-07-17 07:24 UTC, Superjom commented on ctr/README.md
> +```
done

2017-07-17 07:24 UTC, Superjom commented on ctr/network_conf.py
> +# -*- coding: utf-8 -*-
done

2017-07-17 07:58 UTC, lcy-seso approved these changes
LGTM

2017-07-17 07:58 UTC, lcy-seso commented on ctr/README.md
> +1.  获取满足 query 的广告集合
“满足 query ” 这一句的意义不明白，我不是特别理解。
能否略微再增加一些描述性词汇。

2017-07-17 08:27 UTC, merged