DSSM
PaddlePaddle/models pull request #141
Opened 2017-07-02 10:22 UTC by Superjom

DSSM 模型实现

支持 CLASSIFICATION/REGRESSION/RANK 3种损失函数 +
FC/RNN/CNN 三种模型结构的组合

2017-07-05 05:50 UTC, lcy-seso requested changes

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +两个单位间语义距离的权衡是一种非常常规的需求，本文将会演示如何使用 DSSM 模型建模两个字符串间的关系，
- “两个单位间语义距离的权衡是一种非常常规的需求” 这句话的含义不是特别精确，我没有从这个描述中精确地理解到这篇例子的模型要解决什么问题。
- “使用 DSSM 模型建模两个字符串间的关系” --> 什么关系？语义关系？
- “单位”这里具体都可以指什么呢？有些意义不明确。
- ”本文将会演示“ --> "本例演示"，和其它篇章保持一致。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +DSSM \[[1](##参考文档)\]是微软研究院13年提出来的比较经典的语义模型，用于学习两个单位之间的语义距离，适用于如下场景：
- 比较经典 --> 这样口语化的描述尽量避免。技术文章里，经典就是经典，不经典就是不经打，不存在“比较经典”。
- “单位” 有没有其他说法？或者其它词汇，表意不具体，不明确。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +# Deep Structured Semantic Models (DSSM)
- 深度结构化语义模型 （Deep Structured Semantic Models, DSSM）
- 在存在中文的情况下，尽量给一个中文的解释

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +3. 自动推荐，衡量User与被推荐的Item之间的关联程度
1 ~ 3 每句之后都加上句号吧。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +DSSM 如今已经发展成了一个框架，可以很自然地建模两个单位之间的距离关系，比如对于相关性，可以用余弦相似度（COS)来刻画，模型具体训练时，可以用分类或者pairwise rank的方式训练。
如今，DSSM 已经发展成一个框架，用于很建模两个单位之间的距离关系。例如：对于相关性问题，可以用余弦相似度（cosine）来刻画，**[还有没有其它例子，一个例子用来说明 DSSM 发展为一个框架略显单薄行]**。模型的训练可以使用分类或者pairwise rank的方式。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +在原始的DSSM模型的论文\[[1](#参考文档)\]中，DSSM模型用来衡量用户搜索词 Query 和文档集合 Documents 之间隐含的语义关系，模型结构如下
在原始的DSSM模型的论文\[[1](#参考文档)\]中 --> 原论文\[[1](#参考文档)\]中，

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +其贯彻的思想是， **用DNN将高维特征空间转化为低纬空间的向量（图中红色框部分）** ，
- 用DNN将高维特征空间转化为低纬空间的向量
     - 主干：特征空间转化为向量，这个意义不太对。
     - 这句话 至少应该是 “用DNN将高维特征空间中的特征向量转化为低纬空间的向量”。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +**在上层用cossim（余弦相似度）来衡量 Query Semantic Feature 与 Document Semantic Feature 的语义相关性**。
- 在上层用cossim（余弦相似度）--> 在上层用余弦相似度（cosine similarity）。
    - 这篇 README 只需要保持术语和名词的自洽，不一定严格遵循论文里面的所有符号。
    - cossim 不是一个广泛认可的固定的缩写，尽量保持表意的完整。
- 来衡量 Query Semantic Feature 与 Document Semantic Feature 的语义相关性，用中文。
    -  Query Semantic Feature 和 Document Semantic Feature 上文没有出现，也不是固定的专有名词，应该用中文。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +一个Query会抽取正例 `D+` 和4个负例 `D-` 整体上算条件概率用对数似然函数作为损失，
- `D+` 和 `D-` 用Latex 符号。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +这也就是图中类似 $P(D_1|Q)$ 的结构，具体细节请参考原论文。
- 图中，到底是图几呢？直接引用。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +在后续的优化中，DSSM模型的结构得以简化，最终在分享\[[3](#参考文档)\]中，模型的结构变成
随着后续优化DSSM模型的结构得以简化，演变为：

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +图中的白色空白框可以用任何模型替代，比如全连接FC，卷积CNN，RNN等都可以，该模型结构专名用于衡量两个元素（比如字符串）间的语义距离。
1. 白色空白框 --> 空白方框
2. 该模型结构专名用于 --> 该模型结构专门用于

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +在现实使用中，DSSM模型会当成基础积木，搭配上其他结构来实现具体的功能，比如
- 在现实使用中，DSSM模型会作基础的积木，同时搭配其他结构来实现具体的功能，这里以排序学习为例：
- 我有2个问题：
    1. “同时搭配其他结构” --> 这个描述是技术不精确的？什么样的自他结构，这个其它结构的功能是什么？是学习策略？损失函数？
    2. 排序学习之外是否有其它的应用例子呢？

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +Figure 2. DSSM通用结构
Figure 2 --> 图 2

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +- 在排序学习中，将 Figure 2 中结构添加 pairwise rank损失，变成一个rank模型
- Figure 2 --> 图 2
- 变成一个 rank 模型 --> 变成一个排序模型
    - 如果有中文概念，尽量保持一致地使用中文

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +- 在需要对一个pair分类时，比如CTR预估中，对点击与否做0，1二元分类，添加classification error变成一个分类问题
- classification error --> 交叉熵

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +- 在需要对一个子串打分时，可以使用cossim来计算相似度，变成一个回归问题
- cossim -> 余弦相似度

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +本教程将尝试面向应用提供一个比较通用的解决方案，在模型任务类型上支持
本教程 --> 本例

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +在semantic feature的生成的模型结构上，本模型支持
前文没有明确给 `semantic feature`下定义，这里出现，读者无法限定是模型的那一部分。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +DSSM模型可以拆成三小块实现，分别是左边和右边的DNN，
- 请直接对应到图×，否则“左边、右边”会出现指代不清的问题。
- 三小块 --> 三部分：1. ×， 2. ×， 3.×。
- 52 ~ 54 行提到了三种模型，这里又直接特指了 DNN？把61行的意思提前，这里最好有一个多度说明，比如：我们以DNN为例，CNN，RNN原理相同等。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +
- 58 行 “以及顶层的损失函数，”之后是句号。
- 59 行不需要换行。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +本教程中为了简便和通用，将左右两个DNN的结构都设为相同的，因此只有三个选项FC,CNN,RNN等。
本教程 --> 本例

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +两者数据的数据不同，最好定制下对应的DNN结构。
最好定制下对应的DNN结构 --> 建议对应定制DNN的结构。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +在损失函数的设计方面，也支持三种，CLASSIFICATION, REGRESSION, RANK；
CLASSIFICATION, REGRESSION, RANK；--> 分类问题使用的交叉熵损失函数，回归问题使用的最小均方误差，排序学习使用的pairwise rank loss。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +在CLASSIFICATION任务中，类别预测的分布通过softmax计算。
- 63 ~ 65 合并成一行。
- CLASSIFICATION、REGRESSION、RANK使用中文，需要时也不需要全大写。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +在 [paddle/models](https://github.com/PaddlePaddle/models)之前的系列教程中，对上面提到的很多内容都有了详细的介绍，比如
在其它教程中，对上述很多内容都有过详细的介绍，例如：

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +如下图，REGRESSION 和 CLASSIFICATION 模型的结构很相似
REGRESSION 和 CLASSIFICATION 使用中文。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +Figure 3. DSSM for REGRESSION or CLASSIFICATION
- Figure 3 图3
- REGRESSION 和 CLASSIFICATION 使用中文

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +最重要的组成部分包括 embedding，左右两个sentece vector的学习器（可以用RNN/CNN/FC中的任意一种实现），
sentence vector --> 使用中文。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +而Pairwise Rank的结构会复杂一些，类似两个 Figure 3. 中的结构，增加了对应的 Hinge lost的损失函数。
82 ~ 85 合并成1行。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +下面是各个部分具体的实现方法，所有的代码均包含在 `./network_conf.py` 中。
下面是各个部分具体的实现方法，所有的代码均包含在 `./network_conf.py` 中。  --> 下面是各个部分具体实现，详细代码均包含在 `network_conf.py` 中。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +### 创建文本的embedding
embedding --> 词向量，有中文翻译的术语，尽量使用中文。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +由于输入给 `embedding` 的是一个句子对应的 `wordid list`，因此embedding 输出的是 word vector list.
- `embedding` `wordid list` `word vector list`，这些词或者前文已下过定义，或者是专有名词，否则不要在中文的行文过程中夹杂/引入不必要的英文。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +```
删掉 136 和 138 行吧。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +CNN 接受 embedding 输出的 list of word vevtors，通过卷积和池化操作捕捉到原始句子的关键信息，
-  vevtors -->  vectors
- embedding 输出的 list of word vevtors 如果想使用英文，请在文章的一开始就对关键、反复出现的名词下一个定义，后面可以直接用，以保证自洽性。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +这里实现中，分别使用了窗口长度为3和4的个CNN学到的句子向量按元素求和得到最终的句子向量。
- 这里实现中 --> 本例的实现中，
- 3和4的个 ，多了“个”

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +RNN很适合学习变长序列的信息，使用RNN来学习句子的信息也算是标配之一。
使用RNN来学习句子的信息也算是标配之一。--> 使用RNN来学习句子的信息几乎是自然语言处理任务的标配。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +使用取Max的方法能够避免句子长度对semantic vector的影响。
在构建FC时需要首先使用`paddle.layer.pooling` 对词向量序列进行最大池化操作，将边长序列转化为一个固定维度向量，作为整个句子的语义表达，使用最大池化能够降低句子长度对句向量表达的影响。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +在 CNN/DNN/FC提取出 semantic vector后，在上层接着用多层FC实现一个DNN的结构
在上层接着用多层FC实现一个DNN的结构-->在上层可继续接多层FC来实现深层DNN结构。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +    # if more than three layers, than a fc layer will be added.
if more than three layers, than a fc layer will be added. 这句注释的语法有问题。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +
CLASSIFICATION和REGRESSION请使用中文。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +Pairwise Rank复用上面的DNN结构，同一个source对两个target求相似度打分，使用了hinge lost，
1. lost --> loss，且 Paddle 中的 rank-loss 是 logit loss，不是 hinge loss，这里提 hinge loss 是否不太合适。
2. target 请使用中文，如果不是（1）必须的技术名词；（2）明确地定义一个变量，且下文清晰指代，尽量较少在中文行文中引入不必要的英文。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +如果左边的target打分高，则预测为1，否则预测为 0。
则预测为1 --> 预测为1

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +#   - source's wordids
word index in the word dictionary.
1. source 不合适，上文从没有提过 source 的概念。
2. wordids 不是一个单词，上文也没有清晰的下过定义。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +```
- 314  ~ 337 行用中文描述一下数据的格式，并给一个实例。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +可以直接执行 `python train.py -y 0 --model_arch 0` 使用简单的demo数据来训练一个分类的FC模型。
demo 数据是什么呢？

2017-07-05 05:50 UTC, lcy-seso commented on dssm/README.md
> +## 参考文档
参考文献

2017-07-05 05:50 UTC, lcy-seso commented on dssm/data/classification/test.txt
> +苹果 六 袋	苹果 6s	0
1. 示例数据，也将训练和测试数据放置为不同数据。
2. 提供不同的数据，删掉重复。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/data/classification/train.txt
> +苹果 六 袋	苹果 6s	0
1. 示例数据，也将训练和测试数据放置为不同数据。
2. 提供不同的数据，删掉重复。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/data/rank/test.txt
> +苹果 六 袋	苹果 6s	新手 汽车 驾驶	1
1. 示例数据，也将训练和测试数据放置为不同数据。
2. 提供不同的数据，删掉重复。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/data/rank/train.txt
> +苹果 六 袋	苹果 6s	新手 汽车 驾驶	1
1. 示例数据，也将训练和测试数据放置为不同数据。
2. 提供不同的数据，删掉重复。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/network_conf.py
> +                    name=name,
如果不是显示地引用名字，去掉指定名字。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/reader.py
> +        print rcd
删掉弃用的注释。

2017-07-05 05:50 UTC, lcy-seso commented on dssm/utils.py
> +logger = logging.getLogger("logger")
直接 get “paddle” 这个logger，可以不需要再重新定义一个。

2017-07-12 13:00 UTC, Superjom commented on dssm/reader.py
> +        print rcd
dong

2017-07-13 09:35 UTC, Superjom commented on dssm/network_conf.py
> +                    name=name,
done

2017-07-13 09:42 UTC, lcy-seso approved these changes
LGTM and we will keep on refining this example.

2017-07-13 09:42 UTC, merged