add ce
PaddlePaddle/models pull request #1563
Opened 2018-12-26 12:12 UTC by zhengya01

2018-12-26 12:17 UTC, kolinwei commented on fluid/PaddleNLP/text_matching_on_quora/.run_ce.sh
> +cudaid=${language_model:=0} # use 0-th card as default
不要用language_model 改成text_matching_on_quta

2018-12-26 12:20 UTC, kolinwei requested changes

2018-12-26 12:20 UTC, kolinwei commented on fluid/PaddleNLP/text_matching_on_quora/.run_ce.sh
> +cudaid=${language_model_m:=0,1,2,3} # use 0,1,2,3 card as default
text_matching_on_quora_m

2018-12-26 12:20 UTC, kolinwei commented on fluid/PaddleNLP/text_matching_on_quora/train_and_evaluate.py
> +SEED = 102
这个加载enable_ce分支里，不要影响非CE下的逻辑

2018-12-26 12:32 UTC, kolinwei approved these changes

2018-12-27 07:49 UTC, mapingshuo approved these changes

2018-12-27 07:49 UTC, merged