make DeepQNetwork models support paddlepaddle>=1.0.0
PaddlePaddle/models pull request #1573
Opened 2018-12-28 05:05 UTC by zenghsh3

2018-12-28 06:21 UTC, TomorrowIsAnOtherDay requested changes

2018-12-28 06:21 UTC, TomorrowIsAnOtherDay commented on fluid/DeepQNetwork/DoubleDQN_agent.py
> +            pred_action_value = fluid.layers.reduce_sum(
fluid support `argmax` at the moment.

2018-12-28 06:21 UTC, TomorrowIsAnOtherDay commented on fluid/DeepQNetwork/DoubleDQN_agent.py
> +            greedy_action = fluid_argmax(next_s_predcit_value)
we could replace `fluid_argmax`  with `argmax` in fluid.
Please remove fluid_argmax in this folder.

2018-12-28 06:21 UTC, TomorrowIsAnOtherDay commented on fluid/DeepQNetwork/DuelingDQN_agent.py
>  from utils import fluid_flatten
fluid support `flatten`, too.
Please remove file `utils` and use fluid general API.

2018-12-28 09:26 UTC, zenghsh3 commented on fluid/DeepQNetwork/DoubleDQN_agent.py
> +            pred_action_value = fluid.layers.reduce_sum(
done

2018-12-28 09:26 UTC, zenghsh3 commented on fluid/DeepQNetwork/DoubleDQN_agent.py
> +            greedy_action = fluid_argmax(next_s_predcit_value)
done

2018-12-28 09:26 UTC, zenghsh3 commented on fluid/DeepQNetwork/DuelingDQN_agent.py
>  from utils import fluid_flatten
done

2019-01-30 21:58 UTC, TomorrowIsAnOtherDay approved these changes

2019-01-30 22:00 UTC, merged