Face detection ce
PaddlePaddle/models pull request #1596
Opened 2019-01-03 13:04 UTC by zhengya01

2019-01-03 13:24 UTC, kolinwei requested changes

2019-01-03 13:24 UTC, kolinwei commented on fluid/PaddleCV/face_detection/_ce.py
> +os.environ['ceroot'] = "./"
ceroor不需要在这里设置,框架会自己设置

2019-01-04 02:38 UTC, kolinwei approved these changes

2019-01-04 02:58 UTC, qingqing01 approved these changes

2019-01-07 12:26 UTC, merged