Ce gru4rec
PaddlePaddle/models pull request #1840
Opened 2019-03-06 03:55 UTC by zhengya01

2019-03-06 13:41 UTC, kolinwei requested changes

2019-03-06 13:41 UTC, kolinwei commented on fluid/PaddleRec/gru4rec/.run_ce.sh
> +cudaid=${tagspace:=0} # use 0-th card as default
gre4rec

2019-03-07 02:35 UTC, kolinwei approved these changes

2019-03-07 03:29 UTC, frankwhzhang approved these changes

2019-03-07 08:44 UTC, merged