Ce chinese ner
PaddlePaddle/models pull request #1890
Opened 2019-03-14 03:07 UTC by zhengya01

2019-03-14 03:46 UTC, kolinwei requested changes

2019-03-14 03:46 UTC, kolinwei commented on fluid/PaddleNLP/chinese_ner/.run_ce.sh
> +cudaid=${tagspace_4:=0,1,2,3} # use 0-th card as default
改成chinese_ner

2019-03-14 03:49 UTC, kolinwei approved these changes

2019-03-15 12:04 UTC, kuke approved these changes
LGTM

2019-03-15 12:05 UTC, merged