add reduce master grad for fp16
PaddlePaddle/models pull request #1925
Opened 2019-03-27 07:34 UTC by typhoonzero

2019-03-28 11:16 UTC, gongweibao requested changes

2019-03-28 11:16 UTC, gongweibao commented on fluid/PaddleCV/image_classification/utils/fp16_utils.py
> +                    allreduce_role_var.append(gradname_to_paramname[input_varname])
如果所有op的op_role_var都是[],是不是就可以兼容c++端插入allreduce和python端插入allreduce？

2019-03-29 02:54 UTC, typhoonzero commented on fluid/PaddleCV/image_classification/utils/fp16_utils.py
> +                    allreduce_role_var.append(gradname_to_paramname[input_varname])
不太理解啥意思

2019-03-29 07:18 UTC, gongweibao approved these changes

2019-03-29 07:20 UTC, merged