Fix bugs of mt_with_external_memory
PaddlePaddle/models pull request #282
Opened 2017-09-19 02:59 UTC by ranqiu92

@lcy-seso

2017-09-19 03:01 UTC, lcy-seso approved these changes
LGTM

2017-09-21 08:45 UTC, lcy-seso commented
neural_turing_machine_arch.png 这幅图太大了，请在markdown中调整一下图片大小。

2017-09-21 08:46 UTC, lcy-seso requested changes
请在markdown中调整一下图片的显示大小，实在太大了。

2017-09-21 10:53 UTC, ranqiu92 commented
Done @lcy-seso

2017-09-21 10:54 UTC, lcy-seso approved these changes
Thank you.

2017-09-21 10:58 UTC, merged