Ss dev
PaddlePaddle/models pull request #29
Opened 2017-05-08 07:13 UTC by wwhu

resolve #11 
Note: This model may encounter "Floating point exception" after training on several mini-batches.
Scheduled sampling need to use the api multiplex_layer (PaddlePaddle/Paddle#1753), which has not been implemented in current Paddle version. I implemented this layer in my repositories (https://github.com/wwhu/Paddle/blob/ss-dev/python/paddle/trainer_config_helpers/layers.py). I will post a PR to the official Paddle repository after I write the unit test for it.

2017-05-09 03:37 UTC, luotao1 requested changes

2017-05-09 03:37 UTC, luotao1 commented on scheduled_sampling/random_schedule_generator.py
> +    b: parameter of the decay (MUST BE DOUBLE)
12-15行的注释放到18行init函数下面，因为这三个参数在init的时候才出现。

2017-05-09 03:37 UTC, luotao1 commented on scheduled_sampling/random_schedule_generator.py
> +    def getScheduleRate(self):
33行注释放到36行下面。下同。因为后续如果别人在中间插了个函数，就不知道这段注释对应的是哪个函数了。

2017-05-09 12:11 UTC, lcy-seso requested changes
Some small modifications.

2017-05-09 12:11 UTC, lcy-seso commented on scheduled_sampling/random_schedule_generator.py
> +    pdb.set_trace()
please delete debug related codes.

2017-05-09 12:11 UTC, lcy-seso commented on scheduled_sampling/random_schedule_generator.py
> +import pdb
please remove the debug module.

2017-05-09 12:11 UTC, lcy-seso commented on scheduled_sampling/scheduled_sampling.py
> +            name='gru_out', size=target_dict_dim)  # , boot_with_const_id=0)
please remove useless comment.

2017-05-10 07:34 UTC, wwhu commented
I have revised the code. Please review it. Thanks.
@lcy-seso @luotao1

2017-05-11 06:59 UTC, lcy-seso requested changes
Scheduled sampling should not be used in generation. Multiplex layer should only be created in training.

2017-05-11 06:59 UTC, lcy-seso commented on scheduled_sampling/scheduled_sampling.py
> +        param_attr=paddle.attr.ParamAttr(name='_source_language_embedding'))
Because the parameter name `_source_language_embedding` is not explicitly used, it can be removed to avoid such a hard code.

2017-05-11 06:59 UTC, lcy-seso commented on scheduled_sampling/scheduled_sampling.py
> +def seqToseq_net(source_dict_dim, target_dict_dim, is_generating=False):
comment on parameters like in `random_schedule_generator.py`.

2017-05-11 06:59 UTC, lcy-seso commented on scheduled_sampling/scheduled_sampling.py
> +                                         true_token_flag):
comment on parameters like in `random_schedule_generator.py`.

2017-05-11 06:59 UTC, lcy-seso commented on scheduled_sampling/scheduled_sampling.py
> +    def gru_decoder_with_attention_test(enc_vec, enc_proj, current_word):
comment on parameters like in `random_schedule_generator.py`.

2017-05-11 06:59 UTC, lcy-seso commented on scheduled_sampling/scheduled_sampling.py
> +            input=[true_token_flag, true_word, generated_word_emb])
This layer should not be created in generating, because, in the generation, generated word is always used.

2017-05-11 06:59 UTC, lcy-seso commented on scheduled_sampling/scheduled_sampling.py
> +        group_inputs.append(trg_embedding)
In the generation, target embedding is unknown. This configuration is not reasonable.

2017-05-15 07:49 UTC, wwhu commented on scheduled_sampling/scheduled_sampling.py
> +            input=[true_token_flag, true_word, generated_word_emb])
The multiplex layer is in the function gru_decoder_with_attention_train, which is only called during training.

2017-05-15 07:52 UTC, wwhu commented on scheduled_sampling/scheduled_sampling.py
> +        group_inputs.append(trg_embedding)
The type of trg_embedding is GeneratedInputV2. It shares the embedding matrix of the target language with the embedding matrix during training. It doesn't use ground-truth target words as inputs.

2017-05-15 07:57 UTC, wwhu commented
I have revised the comments and added the document in README.md. 
The experimental results are not included in the document since I haven't tuned the hyper parameters of the model .
The models runs slowly on my CPU machine. So it will take some time to validate the performance of scheduled sampling.
@lcy-seso

2017-05-15 10:30 UTC, lcy-seso requested changes
need modifications.

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/scheduled_sampling.py
> +            input=[true_token_flag, true_word, generated_word_emb])
Sorry, I see.

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/scheduled_sampling.py
> +        :type enc_vec: Layer
Layer --> LayerOutput

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/scheduled_sampling.py
> +        :type enc_proj: Layer
Layer --> LayerOutput

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/scheduled_sampling.py
> +        :type true_word: Layer
Layer --> LayerOutput

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/scheduled_sampling.py
> +        :rtype: Layer
Layer --> LayerOutput

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/scheduled_sampling.py
> +        :type true_word: Layer
Layer --> LayerOutput

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/scheduled_sampling.py
> +        :type enc_vec: Layer
Layer --> LayerOutput

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/scheduled_sampling.py
> +        :type enc_proj: Layer
Layer --> LayerOutput

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/scheduled_sampling.py
> +        :type true_word: Layer
Layer --> LayerOutput

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/README.md
> +### 训练结果待调参完成后补充
这一节先删去，可以merge 之后提PR修改。

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/README.md
> +Scheduled Sampling是一种解决训练和生成时输入数据分布不一致的方法。在训练早期该方法主要使用真实元素作为解码输入，以将模型从随机初始化的状态快速引导至一个合理的状态。随着训练的进行该方法会逐渐更多的使用生成元素作为解码输入，以解决数据分布不一致的问题。
加参考文献：https://arxiv.org/abs/1506.03099

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/README.md
> +解码阶段在生成第`t`个元素时，标准Sequence to Sequence模型使用上一时刻的真实元素`y(t-1)`作为输入。设上一时刻生成的元素为`g(t-1)`，Scheduled Sampling算法会以一定概率使用`g(t-1)`作为解码输入。
这句话中的 `t` ，`y(t-1)`等，全部替换成 $t$，$y(t-1)$ 等Latex 公式。

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/README.md
> +设当前已经训练到了第`i`个mini-batch，在`t`时刻Scheduled Sampling以概率`epsilon_i`使用上一时刻的真实元素`y(t-1)`作为解码输入，以概率`1-epsilon_i`使用上一时刻生成的元素`g(t-1)`作为解码输入。
数学变量和公式，用 Latex 公式。

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/README.md
> +随着`i`的增大`epsilon_i`会不断减小，解码阶段将不断倾向于使用生成的元素作为输入，训练阶段和生成阶段的数据分布将变得越来越一致。
这里的解释看不出来 epsilon 是如何随着“已处理的样本数”而衰减，普通用户看到这里会很难理解。

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/README.md
> +Scheduled Sampling是一种解决训练和生成时输入数据分布不一致的方法。在训练早期该方法主要使用真实元素作为解码输入，以将模型从随机初始化的状态快速引导至一个合理的状态。随着训练的进行该方法会逐渐更多的使用生成元素作为解码输入，以解决数据分布不一致的问题。
随着训练的进行该方法会逐渐更多的 --> 随着训练的进行该方法会逐渐更多地

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/README.md
> +解码阶段在生成第`t`个元素时，标准Sequence to Sequence模型使用上一时刻的真实元素`y(t-1)`作为输入。设上一时刻生成的元素为`g(t-1)`，Scheduled Sampling算法会以一定概率使用`g(t-1)`作为解码输入。
上一句话说，Scheduled sampling 主要引用在seq2seq 的训练，第二句又说“解码阶段在生成第`t`个元素时”，这里很容易令人迷惑。

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/README.md
> +设当前已经训练到了第`i`个mini-batch，在`t`时刻Scheduled Sampling以概率`epsilon_i`使用上一时刻的真实元素`y(t-1)`作为解码输入，以概率`1-epsilon_i`使用上一时刻生成的元素`g(t-1)`作为解码输入。
epsilon_i 是怎么来的？怎么和已处理样本关联起来的？

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/README.md
> +由于Scheduled Sampling是对Sequence to Sequence模型的改进，其整体实现框架与Sequence to Sequence模型较为相似。为突出本文重点，这里仅介绍与Scheduled Sampling相关的部分，完整的代码见`scheduled_sampling.py`。
与scheduled sampling相关的，包括：
1. 采样概率如何衰减
2. multiplex layer如何使用

都需要解释，这几组产生采样概率的函数，超参数设置原则？

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/README.md
> +schedule_generator = RandomScheduleGenerator("linear", 0.75, 1000000)
0.75, 1000000 这两个值是怎么选择的，请在 README 中解释，否则，用户很难确定这两个值的设置从何而来。

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/README.md
> +```
这样贴一段代码的效果和直接看代码是没啥区别的，请解释怎么使用，初始参数怎么设置。

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/README.md
> +其中`__init__`方法定义了几种不同的衰减概率，`processBatch`方法根据该概率进行采样，最终确定解码时是使用真实元素还是使用生成的元素。
贴一段代码，在代码后面附上这样一句话是没有有效的解释，和直接看代码是没区别的，作为读者看完这句话是充满了疑惑的。

1. 其中`__init__`方法定义了几种 --> 定义了几种？这几种怎么选择？参数怎么设置？请有效地与上文介绍进行管理，指代不请。

2. `processBatch`方法根据该概率进行采样 --> 该概率指代上一句的__init__里面定义的吗？__init__里面接受超参数，采样概率是如何变化的？

3. 最终确定解码时是使用真实元素还是使用生成的元素。 --> 怎么确定的？

2017-05-15 10:30 UTC, lcy-seso commented on scheduled_sampling/README.md
> +这里对数据reader进行封装，加入从`RandomScheduleGenerator`采样得到的`true_token_flag`作为另一组数据输入，控制解码使用的元素。
1. 这里对数据reader进行封装 --> 请展开多写两句，这句话放在这里，为啥对reader进行封装？请不要让读者去想。。。
2. 控制解码使用的元素。--> 这里并不涉及“解码”过程，通常把生成整个序列称之为解码。

2017-05-15 10:47 UTC, lcy-seso commented
请提multiplex layer 的v2 接口的PR，否则这个例子merege 之后无法运行。

2017-05-15 11:46 UTC, luotao1 requested changes
Readme需要大改：
1. random_schedule_generator.py不用放在paddle repo下面么，这样别的用户也可以使用 @lcy-seso 
2. 算法简介要更加通俗易懂，可以将论文中的图转成中文，结合图进行描述。
3. 模型实现部分目前是大段贴代码，大段贴代码的部分都可以删去，只留下一些关键的文字性描述即可。

2017-05-15 11:46 UTC, luotao1 commented on scheduled_sampling/README.md
> +# Scheduled Sampling
标题建议改成中文，下同所有的"Scheduled Sampling"

2017-05-15 11:46 UTC, luotao1 commented on scheduled_sampling/README.md
> +Scheduled Sampling是一种解决训练和生成时输入数据分布不一致的方法。在训练早期该方法主要使用真实元素作为解码输入，以将模型从随机初始化的状态快速引导至一个合理的状态。随着训练的进行该方法会逐渐更多的使用生成元素作为解码输入，以解决数据分布不一致的问题。
第4和第5行中间加空行，不然全部连在一起了。

2017-05-15 11:46 UTC, luotao1 commented on scheduled_sampling/README.md
> +序列生成任务的训练目标是在给定源输入的条件下，最大化目标序列的概率。训练时该模型将目标序列中的真实元素作为解码阶段每一步的输入，然后最大化下一个元素的概率。生成时上一步解码得到的元素被用作当前的输入，然后生成下一个元素。可见这种情况下训练阶段和生成阶段的解码层输入数据的概率分布并不一致。如果序列前面生成了错误的元素，后面的输入状态将会收到影响，而该误差会随着生成过程不断向后累积。
1. 如果有训练目标，就应该写生成目标。要不两个目标都可以不写，这儿建议可以全去掉，只讲训练和生成时的不同数据分布情况。
2. “如果序列前面生成了错误的元素，后面的输入状态将会收到影响，而该误差会随着生成过程不断向后累积。”是引入Scheduled Sampling的原因么？如果不是，可以去掉。

2017-05-15 11:46 UTC, luotao1 commented on scheduled_sampling/README.md
> +Scheduled Sampling是一种解决训练和生成时输入数据分布不一致的方法。在训练早期该方法主要使用真实元素作为解码输入，以将模型从随机初始化的状态快速引导至一个合理的状态。随着训练的进行该方法会逐渐更多的使用生成元素作为解码输入，以解决数据分布不一致的问题。
1. 在训练早期该方法主要使用真实元素作为解码输入：真实元素应该是目标序列的真实元素
2. 以将-》可以将
3. 随着训练的进行，该方法XXX （全文注意分句）

2017-05-15 11:46 UTC, luotao1 commented on scheduled_sampling/README.md
> +Scheduled Sampling主要应用在Sequence to Sequence模型的训练上，而生成阶段则不需要使用。
1. 主要应用在序列到序列模型的训练阶段，生成阶段不需要使用。
2. Sequence to Sequence 改成 “序列到序列”，下同。

2017-05-15 11:46 UTC, luotao1 commented on scheduled_sampling/README.md
> +## 算法简介
算法简介最好有图，现在的描述方式，小白用户看的很晕。

2017-06-14 23:52 UTC, lcy-seso commented
If you are not going to finish this pr, please tell me. I will do it myself.

2017-06-15 00:37 UTC, wwhu commented
I will finish it ASAP. Sorry for the delay. @lcy-seso

2017-06-15 00:41 UTC, lcy-seso commented
You're welcome. I think the work is almost finished, only after small modifications, we can merge it first, and then keep on refining it. Thanks for your work.

2017-06-15 11:26 UTC, wwhu commented on scheduled_sampling/README.md
> +schedule_generator = RandomScheduleGenerator("linear", 0.75, 1000000)
前面提了下超参数需要用户调优。后面调优后会替换这两个值，并说明这是调优后的结果。

2017-06-15 11:26 UTC, wwhu commented on scheduled_sampling/README.md
> +# Scheduled Sampling
这个好像还没有标准的中文翻译

2017-06-15 11:28 UTC, wwhu commented
@lcy-seso @luotao1 已按照上面的意见修改README和其他一些小问题

2017-06-16 07:57 UTC, lcy-seso requested changes
Need to fix a small bug due to the updates of PaddlePaddle.

2017-06-16 07:57 UTC, lcy-seso commented on scheduled_sampling/README.md
> +# Scheduled Sampling
这个例子不需要标准的中文翻译，用英文即可。暂时我也没有遇到广泛接受的中文翻译。

2017-06-16 07:57 UTC, lcy-seso commented on scheduled_sampling/scheduled_sampling.py
> +        trg_embedding = paddle.layer.GeneratedInputV2(
这里有一个小问题，paddle 最近升级了， GeneratedInputV2 和 StaticInputV2 两个函数的 V2 后缀都不再需要。全部替换为 GeneratedInput和StaticInput吧。否则会报错。

2017-06-17 03:30 UTC, wwhu commented on scheduled_sampling/scheduled_sampling.py
> +        trg_embedding = paddle.layer.GeneratedInputV2(
已修改

2017-06-19 02:43 UTC, lcy-seso approved these changes
Almost LGTM, I will further refactor and validate this demo.

2017-06-19 02:45 UTC, luotao1 approved these changes

2017-06-19 02:49 UTC, merged