Refine Image classification, Codes part
PaddlePaddle/models pull request #2974
Opened 2019-07-30 08:21 UTC by shippingwang

2019-09-02 09:53 UTC, qingqing01 commented on PaddleCV/image_classification/README.md
> +### SqueezeNet Series
后面没必要加Series吧

2019-09-02 09:53 UTC, qingqing01 commented on PaddleCV/image_classification/README.md
> +**A:** 维度对不上，删掉预训练参数中的FC
类别数匹配补上，需删掉最后一层分类层FC。

2019-09-02 09:53 UTC, qingqing01 commented on PaddleCV/image_classification/README.md
> +- 2019/08/01 **Stage7**: 更新DarkNet53, DenseNet121. Densenet161, DenseNet169, DenseNet201, DenseNet264, SqueezeNet1_0, SqueezeNet1_1, ResNeXt50_vd_32x4d, ResNeXt152_64x4d, ResNeXt101_32x8d_wsl, ResNeX
Stage1, Stage2, ..., Stage7 之类的都不用加吧。

2019-09-02 10:09 UTC, qingqing01 commented on PaddleCV/image_classification/utils/metrics.py
> +class Metrics(object):
这个文件里封装的是loss，不是metrics

2019-09-02 10:09 UTC, qingqing01 commented on PaddleCV/image_classification/utils/learning_rate.py
> +class Decay(object):
下面封装的是optimizer，而不是Decay

2019-09-02 10:09 UTC, qingqing01 commented on PaddleCV/image_classification/utils/utility.py
> +            % (args.checkpoint))
1. 函数名字去掉_old

2. 不要加 `(interface: load_persistable with multifiles) `。
```
Finish initing model from %s .
```

2019-09-03 13:51 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +### SqueezeNet Series
Done

2019-09-03 13:51 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +**A:** 维度对不上，删掉预训练参数中的FC
Done

2019-09-03 13:52 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +- 2019/08/01 **Stage7**: 更新DarkNet53, DenseNet121. Densenet161, DenseNet169, DenseNet201, DenseNet264, SqueezeNet1_0, SqueezeNet1_1, ResNeXt50_vd_32x4d, ResNeXt152_64x4d, ResNeXt101_32x8d_wsl, ResNeX
没有删，因为觉得一个一个Stage比较清晰

2019-09-03 13:52 UTC, shippingwang commented on PaddleCV/image_classification/utils/utility.py
> +            % (args.checkpoint))
Done, 新的load接口：init_model  新的save接口： save_model

2019-09-04 13:25 UTC, shippingwang commented on PaddleCV/image_classification/utils/learning_rate.py
> +class Decay(object):
已经改成Optimizer

2019-09-04 13:26 UTC, shippingwang commented on PaddleCV/image_classification/utils/metrics.py
> +class Metrics(object):
已经封装了新的接口create_model， Metrics类改为Loss类

2019-09-05 03:56 UTC, qingqing01 requested changes

2019-09-05 03:56 UTC, qingqing01 commented on PaddleCV/image_classification/utils/utility.py
> +    #parser.add_argument('--image_shape', nargs='+', type=int, default=[3,224,224], help='The size of Input image, order: [channels, height, weidth]')
del this line

2019-09-05 03:56 UTC, qingqing01 commented on PaddleCV/image_classification/utils/utility.py
> +    #add_arg('use_mem_opt',              bool,   False,                  "Whether to use memory optimization.")
del this line

2019-09-05 03:56 UTC, qingqing01 commented on PaddleCV/image_classification/utils/utility.py
> +        name="feed_lam", shape=[1], dtype="float32", lod_level=0)
feed_y_a到feed_lam的data layer定义移动到 if  里。

2019-09-05 03:56 UTC, qingqing01 commented on PaddleCV/image_classification/utils/utility.py
> +        #build_strategy.memory_optimize = args.with_mem_opt
del this line

2019-09-05 03:56 UTC, qingqing01 commented on PaddleCV/image_classification/utils/utility.py
> +        #build_strategy.fuse_all_reduce_ops=1
del this line

2019-09-05 03:56 UTC, qingqing01 commented on PaddleCV/image_classification/utils/utility.py
> +    add_arg('use_inplace',              bool,   True,                   "Whether to use inplace memory optimization.")
inplace 这个还需要作为开关吗？

2019-09-05 03:56 UTC, qingqing01 commented on PaddleCV/image_classification/utils/utility.py
> +def best_strategy(args, program, loss):
best_strategy这个函数哪里用了？

2019-09-05 03:56 UTC, qingqing01 commented on PaddleCV/image_classification/utils/utility.py
> +def best_strategy_compiled(args, program, loss):
这个代码没多少，觉得直接放到train.py里吧

2019-09-05 03:56 UTC, qingqing01 commented on PaddleCV/image_classification/infer.py
> +        readable_pred_label = readable_label(pred_label, args.label_path)
``` 
readable_pred_label = readable_label(pred_label, args.label_path) 
```
放到for循环前面

2019-09-05 03:56 UTC, qingqing01 commented on PaddleCV/image_classification/README.md
> +* **enable_ce**: 是否开启CE测试，默认值: False
ce的开关不用写在文档里

2019-09-05 03:56 UTC, qingqing01 commented on PaddleCV/image_classification/README.md
> +解决方案和超参配置：
模型类型和超参配置

2019-09-05 03:56 UTC, qingqing01 commented on PaddleCV/image_classification/README.md
> +注意：CE相关代码仅用于内部测试，enable_ce默认设置False。
用户文档里不用说明CE了吧

2019-09-05 03:56 UTC, qingqing01 commented on PaddleCV/image_classification/utils/loss.py
> +#copyright (c) 2019 PaddlePaddle Authors. All Rights Reserve.
不要叫loss.py， 该文件包含了完整的组网代码。移动到 utils外面，叫 build_model.py

2019-09-05 03:56 UTC, qingqing01 commented on PaddleCV/image_classification/utils/loss.py
> +class Loss(object):
这个class的作用并不是create loss。

封装3个函数: 

def _basic_model(data, model, args, is_train):

def _googlenet_model(data, model, args, is_train):

def _mixup_model(data, model, args, is_train):

2019-09-05 04:04 UTC, shippingwang commented on PaddleCV/image_classification/utils/utility.py
> +    #parser.add_argument('--image_shape', nargs='+', type=int, default=[3,224,224], help='The size of Input image, order: [channels, height, weidth]')
done

2019-09-05 04:05 UTC, shippingwang commented on PaddleCV/image_classification/utils/utility.py
> +    #add_arg('use_mem_opt',              bool,   False,                  "Whether to use memory optimization.")
done

2019-09-05 04:05 UTC, shippingwang commented on PaddleCV/image_classification/utils/utility.py
> +        name="feed_lam", shape=[1], dtype="float32", lod_level=0)
done

2019-09-05 04:05 UTC, shippingwang commented on PaddleCV/image_classification/utils/utility.py
> +        #build_strategy.memory_optimize = args.with_mem_opt
done

2019-09-05 04:05 UTC, shippingwang commented on PaddleCV/image_classification/utils/utility.py
> +        #build_strategy.fuse_all_reduce_ops=1
done

2019-09-05 04:05 UTC, shippingwang commented on PaddleCV/image_classification/utils/utility.py
> +    add_arg('use_inplace',              bool,   True,                   "Whether to use inplace memory optimization.")
done

2019-09-05 04:49 UTC, shippingwang commented on PaddleCV/image_classification/utils/utility.py
> +def best_strategy(args, program, loss):
过去的实现方式，已经删除

2019-09-05 04:50 UTC, shippingwang commented on PaddleCV/image_classification/utils/utility.py
> +def best_strategy_compiled(args, program, loss):
感觉影响阅读train，暴露很多用户不了解的概念，现在暂时放在utility下了

2019-09-05 04:51 UTC, shippingwang commented on PaddleCV/image_classification/infer.py
> +        readable_pred_label = readable_label(pred_label, args.label_path)
OK

2019-09-05 04:53 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +* **enable_ce**: 是否开启CE测试，默认值: False
已删除

2019-09-05 04:53 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +解决方案和超参配置：
OK

2019-09-05 04:55 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +注意：CE相关代码仅用于内部测试，enable_ce默认设置False。
Done

2019-09-05 04:57 UTC, shippingwang commented on PaddleCV/image_classification/utils/loss.py
> +#copyright (c) 2019 PaddlePaddle Authors. All Rights Reserve.
OK

2019-09-05 12:22 UTC, qingqing01 approved these changes

2019-09-05 13:16 UTC, merged