add ner model
PaddlePaddle/models pull request #30
Opened 2017-05-08 08:18 UTC by guoshengCS

fix #13

2017-05-09 03:42 UTC, luotao1 requested changes
数据集和模型比较大，不应该上传版本库，请清理。目前这个commit应该只留下conll03.py和ner_final.py两个文件。数据集可以给个下载地址，或集成进paddle.dataset中。

2017-05-09 07:47 UTC, lcy-seso requested changes
request changes.

2017-05-09 07:47 UTC, lcy-seso commented on sequence_tagging_for_ner/ner_final.py
> +        param_attr=paddle.attr.Param(name='crfw'))
The original configuration file contains an chunk evaluator.

2017-05-09 07:47 UTC, lcy-seso commented on sequence_tagging_for_ner/ner_final.py
> +    lstm_1_1 = paddle.layer.lstmemory(
The original configuration file uses simple RNN. By considering that we do not provide any examples of how to use the simple recurrent layer. I suggest not modify the original configuration file.

2017-05-09 07:47 UTC, lcy-seso commented on sequence_tagging_for_ner/ner_final.py
> +    #ws = paddle.layer.data(name='ws', type=d_type(num_ws))
If the comment has no special purpose, please remove it.

2017-05-09 07:47 UTC, lcy-seso commented on sequence_tagging_for_ner/ner_final.py
> +    #                    input=paddle.layer.table_projection(input=ws))
If the comment has no special purpose, please remove it.

2017-05-09 10:48 UTC, lcy-seso requested changes
Bug occurs.

2017-05-09 10:48 UTC, lcy-seso commented on sequence_tagging_for_ner/conll03.py
> +            #word_idx = [word_dict.get(w, UNK_IDX) for w in sentence]
Please remove useless comments.

2017-05-09 10:48 UTC, lcy-seso commented on sequence_tagging_for_ner/ner_final.py
> +        param_attr=lstm_para_attr)
line 51 to line 109, please rewrite by using for loop statement.

2017-05-09 10:48 UTC, lcy-seso commented on sequence_tagging_for_ner/ner_final.py
> +    feature_out, target, crf_cost, predict = ner_net()
crf_cost cannot be used in inference because label is unknown.

2017-05-10 03:11 UTC, guoshengCS commented
@lcy-seso 请教下chunk_evalutor 的使用问题，以下是文档中的部分截图，使用chunk_evalutor的话label的id是需要满足这样的条件的么：tagType = label % numTagType，chunkType = label / numTagType
![image](https://cloud.githubusercontent.com/assets/14105589/25881545/21e0833c-3570-11e7-8eb5-fa87a208d13a.png)

2017-05-11 05:27 UTC, guoshengCS commented on sequence_tagging_for_ner/ner_final.py
> +    #ws = paddle.layer.data(name='ws', type=d_type(num_ws))
done

2017-05-11 05:27 UTC, guoshengCS commented on sequence_tagging_for_ner/ner_final.py
> +    #                    input=paddle.layer.table_projection(input=ws))
done

2017-05-11 05:28 UTC, guoshengCS commented on sequence_tagging_for_ner/ner_final.py
> +    lstm_1_1 = paddle.layer.lstmemory(
done

2017-05-11 05:28 UTC, guoshengCS commented on sequence_tagging_for_ner/ner_final.py
> +        param_attr=paddle.attr.Param(name='crfw'))
to be done

2017-05-11 05:29 UTC, guoshengCS commented on sequence_tagging_for_ner/conll03.py
> +            #word_idx = [word_dict.get(w, UNK_IDX) for w in sentence]
done

2017-05-11 05:33 UTC, guoshengCS commented on sequence_tagging_for_ner/ner_final.py
> +    feature_out, target, crf_cost, predict = ner_net()
done

2017-05-11 05:40 UTC, guoshengCS commented on sequence_tagging_for_ner/ner_final.py
> +        param_attr=lstm_para_attr)
to be done,  haven't found a good way to rewrite, and fellow the original configuration temporarily

2017-05-11 06:02 UTC, lcy-seso requested changes
Need some modifications on codes and doc.

2017-05-11 06:02 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +<img src="image/data_format.png" width = "60%"  align=center /><br>
请变成表格，或则重绘。

2017-05-11 06:02 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +</div>
图再缩小一些，太大了。

2017-05-11 06:02 UTC, lcy-seso commented on sequence_tagging_for_ner/ner.py
> +        param_attr=rnn_para_attr)
请用for 循环来写 62 ~ 107 行。

2017-05-11 06:02 UTC, lcy-seso commented on sequence_tagging_for_ner/ner.py
> +    ner_net_infer(test_data_reader, parameters)
- 和其他例子一样，把训练好的模型保存到本地，目前的模型没有存储下来。
- 预测时，加载存储好的模型，进行预测。

2017-05-11 07:47 UTC, guoshengCS commented on sequence_tagging_for_ner/ner.py
> +        param_attr=rnn_para_attr)
不太清楚需要用for循环抽出什么结构，这个能否具体的说下，比如SRL中使用for循环抽出"fc+lstm"来构造栈式双向LSTM

2017-05-12 07:34 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +<img src="image/data_format.png" width = "60%"  align=center /><br>
done

2017-05-12 07:34 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +</div>
done

2017-05-12 07:34 UTC, guoshengCS commented on sequence_tagging_for_ner/ner.py
> +    ner_net_infer(test_data_reader, parameters)
done

2017-05-12 07:40 UTC, guoshengCS commented
辛苦review，用for循环改写一条暂未修正，这个还需要具体说明指导下，不太清楚需要用for循环抽出什么结构，比如SRL中使用for循环抽出"fc+lstm"来构造栈式双向LSTM

2017-05-12 08:10 UTC, guoshengCS commented
另外，按照 @luotao1 的意见相关数据移出版本库的话，可否提供一个类似SRL中的存放数据的地方，如http://paddlepaddle.bj.bcebos.com/demo/srl_dict_and_embedding/wordDict.txt

2017-05-15 10:38 UTC, lcy-seso commented on sequence_tagging_for_ner/ner_final.py
> +        param_attr=lstm_para_attr)
有什么问题？

2017-05-15 10:39 UTC, lcy-seso commented on sequence_tagging_for_ner/ner.py
> +    ner_net_infer()
请和其它例子一样，改成保存模型到本地，然后加载模型进行预测。

2017-05-16 05:01 UTC, guoshengCS commented on sequence_tagging_for_ner/ner_final.py
> +        param_attr=lstm_para_attr)
不太清楚需要用for循环抽出什么结构，比如SRL中使用for循环抽出"fc+lstm"来构造栈式双向LSTM，这个需要点拨一下，辛苦review

2017-05-18 04:55 UTC, lcy-seso requested changes
The readme doc needs modifications.

2017-05-18 04:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +
背景说明需要再完善一下，NER 序列标注的一个例子，利用序列标注还可以做其它任务，是本例的目标。

1. 大致解释一下什么是序列标注。
2. NN 解决序列标注的思路。
3. 序列标注还可以做什么，使用本例的配置，还可以做其它什么任务。
4. 序列标注需要的相关展开，请直接引导至PaddleBook的语义角色标注一节。

2017-05-18 04:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +其中第一列为原始句子序列（第二、三列分别为词性标签和句法分析中的语块标签，这里暂时不用），第四列为采用了I-TYPE方式表示的NER标签（I-TYPE和[BIO方式](https://github.com/PaddlePaddle/book/tree/develop/07.label_semantic_roles)的主要区别在于语块开始标记的使用上，I-TYPE只有在出现相邻的同类别实体时对后者
1. 这里请说明一下  `conll03.py` 做了哪些处理
2. 如何运行 `conll03.py`
3. 数据处理的说明很不清晰，比如，如果考虑需要运行这个例子：
    - 原始数据下载下来是什么样子呢？
    - 数据下载之后该放在哪里呢？
    - 数据预处理应该首先执行哪个脚本呢？是不是需要指定参数？路径是否需要设置？
    - 预处理完之后长什么样子呢？
    - 预处理的数据应该修改哪些变量，修改成什么样？修改好之后运行什么脚本来跑训练？
2. 请按照 step by step 的顺序来充足文档
3. 请参考文本分类的[自定义数据](https://github.com/PaddlePaddle/models/tree/develop/text_classification#自定义数据) 一节，来介绍如何替换成自己的数据进行训练。

2017-05-18 04:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +在本示例中，我们所使用的模型结构如图1所示。其输入为句子序列，在取词向量转换为词向量序列后，经过多组全连接层、双向RNN进行特征提取，最后接入CRF以学习到的特征为输入，以标记序列为监督信号，完成序列标注。更多关于RNN及其变体的知识可见[此页面](http://book.paddlepaddle.org/06.understand_sentiment/)。
把模型流程分解成：
    1. 输入特征是 one-hot 表示的……
    2. 转词向量……
    3. RNN 学习句子特征
    4. CRF 完成序列标注
这样用序号描述的步骤，不需要太长，但力求逻辑清晰。

2017-05-18 04:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +运行`ner.py`需要对数据设置部分进行更改，将以下代码中的变量值修改为正确的文件路径即可。
在哪里修改，如果修改？请基于“手把手不需要用户动脑子”这样的出发点来介绍。

2017-05-18 04:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +# init dataset
这里的注释不要用缩写。

2017-05-18 04:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +1. `ner_net_train(data_reader, num_passes)`函数实现了模型训练功能，参数`data_reader`表示训练数据的迭代器（使用默认值即可）、`num_passes`表示训练pass的轮数。训练过程中每100个iteration会打印模型训练信息，每个pass后会将模型保存下来，并将最终模型保存为`ner_net.tar.gz`。
按照Pass ID 来存储模型，文档这里也需要修改。

2017-05-18 04:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +2. `ner_net_infer(data_reader, model_file)`函数实现了预测功能，参数`data_reader`表示测试数据的迭代器（使用默认值即可）、`model_file`表示保存在本地的模型文件，预测过程会按如下格式打印预测结果：
预测需要用户做哪些事情呢？这里没有描述清楚。
1. 怎样执行？（比如就是简单执行`python A.py`，那么就简单直接的告诉用户，如果需要修改某个变量的值，也请加以说明）
2. 是否需要替换数据呢？

2017-05-18 04:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +	```
文本块之前的缩进请去掉。

2017-05-22 07:23 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +2. `ner_net_infer(data_reader, model_file)`函数实现了预测功能，参数`data_reader`表示测试数据的迭代器（使用默认值即可）、`model_file`表示保存在本地的模型文件，预测过程会按如下格式打印预测结果：
done

2017-05-22 07:23 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +1. `ner_net_train(data_reader, num_passes)`函数实现了模型训练功能，参数`data_reader`表示训练数据的迭代器（使用默认值即可）、`num_passes`表示训练pass的轮数。训练过程中每100个iteration会打印模型训练信息，每个pass后会将模型保存下来，并将最终模型保存为`ner_net.tar.gz`。
done，按照pass id存储模型，并将最后一轮模型另存为`ner_model.tar.gz`

2017-05-22 07:23 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +
done，重写了背景说明部分，补充了相应内容

2017-05-22 07:23 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +其中第一列为原始句子序列（第二、三列分别为词性标签和句法分析中的语块标签，这里暂时不用），第四列为采用了I-TYPE方式表示的NER标签（I-TYPE和[BIO方式](https://github.com/PaddlePaddle/book/tree/develop/07.label_semantic_roles)的主要区别在于语块开始标记的使用上，I-TYPE只有在出现相邻的同类别实体时对后者
done，重写了数据说明部分的内容进行了更细致的说明。暂未提供独立的数据预处理脚本，是将预处理过程内置在了返回生成器的过程中，另在使用说明部分增加了自定义数据的内容

2017-05-22 07:23 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +在本示例中，我们所使用的模型结构如图1所示。其输入为句子序列，在取词向量转换为词向量序列后，经过多组全连接层、双向RNN进行特征提取，最后接入CRF以学习到的特征为输入，以标记序列为监督信号，完成序列标注。更多关于RNN及其变体的知识可见[此页面](http://book.paddlepaddle.org/06.understand_sentiment/)。
done

2017-05-22 07:23 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +运行`ner.py`需要对数据设置部分进行更改，将以下代码中的变量值修改为正确的文件路径即可。
done

2017-05-22 07:23 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +# init dataset
done

2017-05-22 07:23 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +	```
done

2017-05-22 07:31 UTC, guoshengCS commented
@lcy-seso 辛苦review，根据上次review意见对README进行了较大改动，另为增强说服力参照论文[Natural Language Processing (Almost) from Scratch](http://www.jmlr.org/papers/volume12/collobert11a/collobert11a.pdf)对模型输入进行了修改，使用小写并加入大写标记作为特征。

2017-05-24 02:55 UTC, lcy-seso requested changes
Good writing, almost LGTM.

2017-05-24 02:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +图1. NER标注示例
图的名字修改一下：NER标注示例 --> BIO标注方法示例

2017-05-24 02:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +由于序列标注问题的广泛性，产生了[CRF](http://book.paddlepaddle.org/07.label_semantic_roles/)等经典的序列模型，这些模型多只能使用局部信息或需要人工设计特征。发展到深度学习阶段，各种网络结构能够实现复杂的特征抽取功能，循环神经网络（Recurrent Neural Network，RNN，更多相关知识见[此页面](http://book.
- 更多相关知识见[此页面] --> 把“此页面”修改为，PaddleBook中[语义角色标注](https://github.com/PaddlePaddle/book/blob/develop/07.label_semantic_roles/README.cn.md)一课。
- 语义角色标注的连接换成中文README的，目前models都是中文的说明

2017-05-24 02:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +在NER任务中，输入是"一句话"，目标是识别句子中的实体边界及类别，我们这里仅使用原始句子作为特征（参照论文\[[2](#参考文献)\]进行了一些预处理工作：将每个词转换为小写并将原词是否大写另作为一个特征）。按照上文所述处理序列标注问题的思路，可以构造如下结构的模型（图2是模型结构示意图）：
我们这里仅使用原始句子作为特征 --> 我们这里仅对原始句子作为特征

2017-05-24 02:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +本示例另在`ner.py`中提供了完整的运行流程，包括数据接口的使用和模型训练、预测。根据上文所述的接口使用方法，使用时需要将`ner.py`中如下的数据设置部分中的各变量修改为正确的文件路径：
1. 本示例 --> 本例
2. 修改为正确的文件路径 --> 修改为对应文件路径

2017-05-24 02:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +vocab_file = 'data/vocab.txt'     # word_dict文件
注释里word_dict这变量个用中文描述一下吧，比如：“输入句子对应的字典文件的路径”否则，还需要对应去理解这个变量的含义

2017-05-24 02:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +train_data_file = 'data/train'    # 训练数据文件
训练数据文件 --> 训练数据文件的路径

2017-05-24 02:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +test_data_file = 'data/test'      # 测试数据文件
测试数据文件 -->  测试数据文件的路径

2017-05-24 02:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +target_file = 'data/target.txt'   # label_dict文件
注释中 label_dict 用中文来解释吧~

2017-05-24 02:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +emb_file = 'data/wordVectors.txt' # 词向量文件
词向量文件 --> 预训练的词向量参数的路径。

2017-05-24 02:55 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +ner_net_infer(data_reader=test_data_reader, model_file='ner_model.tar.gz')
这里把模型的保存/加载的名字都改为与pass_id有关吧。

2017-05-24 08:05 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +在NER任务中，输入是"一句话"，目标是识别句子中的实体边界及类别，我们这里仅使用原始句子作为特征（参照论文\[[2](#参考文献)\]进行了一些预处理工作：将每个词转换为小写并将原词是否大写另作为一个特征）。按照上文所述处理序列标注问题的思路，可以构造如下结构的模型（图2是模型结构示意图）：
done

2017-05-24 08:05 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +图1. NER标注示例
done

2017-05-24 08:05 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +由于序列标注问题的广泛性，产生了[CRF](http://book.paddlepaddle.org/07.label_semantic_roles/)等经典的序列模型，这些模型多只能使用局部信息或需要人工设计特征。发展到深度学习阶段，各种网络结构能够实现复杂的特征抽取功能，循环神经网络（Recurrent Neural Network，RNN，更多相关知识见[此页面](http://book.
done

2017-05-24 08:05 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +本示例另在`ner.py`中提供了完整的运行流程，包括数据接口的使用和模型训练、预测。根据上文所述的接口使用方法，使用时需要将`ner.py`中如下的数据设置部分中的各变量修改为正确的文件路径：
done

2017-05-24 08:05 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +train_data_file = 'data/train'    # 训练数据文件
done

2017-05-24 08:05 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +test_data_file = 'data/test'      # 测试数据文件
done

2017-05-24 08:05 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +vocab_file = 'data/vocab.txt'     # word_dict文件
done

2017-05-24 08:05 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +target_file = 'data/target.txt'   # label_dict文件
done

2017-05-24 08:05 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +emb_file = 'data/wordVectors.txt' # 词向量文件
done

2017-05-24 08:05 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +ner_net_infer(data_reader=test_data_reader, model_file='ner_model.tar.gz')
done

2017-05-24 08:40 UTC, lcy-seso requested changes
some small modifications.

2017-05-24 08:40 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +在NER任务中，输入是"一句话"，目标是识别句子中的实体边界及类别，我们这里仅对原始句子作为特征（参照论文\[[2](#参考文献)\]进行了一些预处理工作：将每个词转换为小写并将原词是否大写另作为一个特征）。按照上文所述处理序列标注问题的思路，可以构造如下结构的模型（图2是模型结构示意图）：
- 抱歉，上一次的review 没有看清楚，将第一句话改残了。。
- 我们这里仅对原始句子作为特征（参照论文\[[2](#参考文献)\]进行了一些预处理工作：将每个词转换为小写并将原词是否大写另作为一个特征） --> 我们参照论文\[[2](#参考文献)\]仅对原始句子进行了一些预处理工作：将每个词转换为小写，并将原词是否大写另作为一个特征，共同作为模型的输入。

2017-05-24 08:40 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +（为保证本例的完整性，我们从中抽取少量样本放在`data/train`和`data/test`文件中作为训练和测试示例使用；由于版权原因完整数据还请自行获取）这三个文件数据格式如下：
（为保证本例的完整性，我们从中抽取少量样本放在`data/train`和`data/test`文件中作为训练和测试示例使用；由于版权原因完整数据还请自行获取） --> 为保证本例的完整性，我们从中原始数据抽取少量样本放在`data/train`和`data/test`文件中，作为示例使用；由于版权原因，完整数据还请大家自行获取。

2017-05-24 08:40 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +另外，我们附上word词典、label词典和预训练的词向量三个文件（word词典和词向量来源于[Stanford CS224d](http://cs224d.stanford.edu/)课程作业）以供使用。
这三个文件是否有可能在data文件夹下增加一个download的shell脚本，而不直接放在版本库中？

2017-05-24 08:40 UTC, lcy-seso commented on sequence_tagging_for_ner/README.md
> +1. `ner_net_train(data_reader, num_passes)`函数实现了模型训练功能，参数`data_reader`表示训练数据的迭代器、`num_passes`表示训练pass的轮数。训练过程中每100个iteration会打印模型训练信息（由于加入了chunk evaluator，会按语块计算当前模型识别的Precision、Recall和F1值，这里也会打印出来，其
训练过程中每100个iteration会打印模型训练信息（由于加入了chunk evaluator，会按语块计算当前模型识别的Precision、Recall和F1值，这里也会打印出来，其详细使用说明请参照[文档](http://www.paddlepaddle.org/develop/doc/api/v2/config/evaluators.html#chunk)） --> 训练过程中每100个iteration会打印模型训练信息。我们同时在模型配置中加入了chunk evaluator，会输出当前模型对语块识别的Precision、Recall和F1值。chunk evaluator 的详细使用说明请参照[文档](http://www.paddlepaddle.org/develop/doc/api/v2/config/evaluators.html#chunk)。

2017-05-24 08:40 UTC, lcy-seso commented on sequence_tagging_for_ner/ner.py
> +        num_chunk_types=(label_dict_len - 1) / 2)
221 ~ 222 行 bug，应该删掉。

2017-05-24 08:40 UTC, lcy-seso commented on sequence_tagging_for_ner/ner.py
>      paddle.init(use_gpu=False, trainer_count=1)
268 ~ 270 三行略微改一下~
```python
is_test = False

if is_test: 
    ner_net_train(data_reader=train_data_reader, num_passes=1)
else:
    ner_net_infer(data_reader=test_data_reader, model_file='ner_model.tar.gz')
```

2017-05-24 11:36 UTC, guoshengCS commented on sequence_tagging_for_ner/ner.py
> +        num_chunk_types=(label_dict_len - 1) / 2)
done

2017-05-24 11:36 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +在NER任务中，输入是"一句话"，目标是识别句子中的实体边界及类别，我们这里仅对原始句子作为特征（参照论文\[[2](#参考文献)\]进行了一些预处理工作：将每个词转换为小写并将原词是否大写另作为一个特征）。按照上文所述处理序列标注问题的思路，可以构造如下结构的模型（图2是模型结构示意图）：
done

2017-05-24 11:36 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +（为保证本例的完整性，我们从中抽取少量样本放在`data/train`和`data/test`文件中作为训练和测试示例使用；由于版权原因完整数据还请自行获取）这三个文件数据格式如下：
done

2017-05-24 11:36 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +另外，我们附上word词典、label词典和预训练的词向量三个文件（word词典和词向量来源于[Stanford CS224d](http://cs224d.stanford.edu/)课程作业）以供使用。
done

2017-05-24 11:36 UTC, guoshengCS commented on sequence_tagging_for_ner/README.md
> +1. `ner_net_train(data_reader, num_passes)`函数实现了模型训练功能，参数`data_reader`表示训练数据的迭代器、`num_passes`表示训练pass的轮数。训练过程中每100个iteration会打印模型训练信息（由于加入了chunk evaluator，会按语块计算当前模型识别的Precision、Recall和F1值，这里也会打印出来，其
done

2017-05-24 11:36 UTC, guoshengCS commented on sequence_tagging_for_ner/ner.py
>      paddle.init(use_gpu=False, trainer_count=1)
done temporarily

2017-05-24 11:37 UTC, lcy-seso approved these changes
LGTM

2017-05-24 11:39 UTC, luotao1 approved these changes

2017-05-24 11:39 UTC, merged