ltr case done.
PaddlePaddle/models pull request #31
Opened 2017-05-08 14:52 UTC by dzhwinter

lambdaRank has a bug, here may be more clear to view

2017-05-09 10:51 UTC, lcy-seso commented
请在 code review 之前，保证 travis-ci 的检查能够通过。

2017-05-10 09:42 UTC, qingqing01 requested changes

2017-05-10 09:42 UTC, qingqing01 commented on ltr/lambdaRank.py
> +    name="/hidden_1",
layer里的name去掉吧，官方示例demo应该提供一个好习惯。 下同，去掉~

2017-05-10 09:42 UTC, qingqing01 commented on ltr/lambdaRank.py
> +  cost = paddle.layer.lambda_cost(input=output,
这里使用lambda_cost，和 https://github.com/lcy-seso/paddle_confs_v1/blob/master/ltr/listwise_ltr.conf 配置不同，@lcy-seso 这样可否？

2017-05-10 09:42 UTC, qingqing01 commented on ltr/lambdaRank.py
> +    paddle.reader.shuffle(fill_default_test, buf_size=1000), batch_size=1000)
test集不需要paddle.reader.shuffle~

2017-05-10 09:42 UTC, qingqing01 commented on ltr/ranknet.py
> +def half_ranknet(name_prefix, input_dim):
存在和上面配置同样的问题。

2017-05-10 09:42 UTC, qingqing01 commented on ltr/ranknet.py
> +          event.pass_id, event.batch_id, event.cost)
只有cost，不知道如何评估。

2017-05-11 01:29 UTC, lcy-seso commented
travis-ci 的检查一直不通过，这样不能merge。

2017-05-11 18:29 UTC, dzhwinter commented on ltr/lambdaRank.py
> +    name="/hidden_1",
Done.

2017-05-11 18:32 UTC, dzhwinter commented on ltr/lambdaRank.py
> +  cost = paddle.layer.lambda_cost(input=output,
接口发生变化，例如给出的例子是一条item对应一条score，改成sequence_based的结果

2017-05-11 18:33 UTC, dzhwinter commented on ltr/lambdaRank.py
> +    paddle.reader.shuffle(fill_default_test, buf_size=1000), batch_size=1000)
fix Done.

2017-05-11 18:33 UTC, dzhwinter commented on ltr/ranknet.py
> +def half_ranknet(name_prefix, input_dim):
fix Done.

2017-05-11 18:35 UTC, dzhwinter commented on ltr/ranknet.py
> +          event.pass_id, event.batch_id, event.cost)
ok，时间限制没有实现ndcg的evaluator，将添加auc evaluator

2017-05-12 04:36 UTC, qingqing01 commented
@dzhwinter 你没push？只看到1个Commits，没有看到更新后的代码~

2017-05-15 11:07 UTC, dzhwinter commented
Done，已push

2017-05-15 11:57 UTC, dzhwinter commented
还是没有加入evaluator，加入auc层存在auc index out of range的问题。更重要的是，ndcg@k，err@k这些是是衡量排序质量的基本度量。计划近期加入ndcg Evaluator。

2017-05-16 06:13 UTC, qingqing01 requested changes
建议train和infer分两个步骤，文档里增加infer过程。

2017-05-16 06:13 UTC, qingqing01 commented on ltr/README.md
> +[RankNet](http://icml.cc/2015/wp-content/uploads/2015/06/icml_ranking.pdf)是一种经典的Pairwise的排序学习方法，是典型的前向神经网络排序模型。在文档集合S中的第i个文档记做`Ui`，它的文档特征向量记做`xi`，对于给定的一个文档对`<Ui, Uj>`，RankNet将输入的单个文档特征向量x映射到`f(x)`，得到
`Ui`, Uj等数学公式格式不统一，一些有``,一些没有，请参考公式要求：$U_i$

2017-05-16 06:13 UTC, qingqing01 commented on ltr/README.md
> +其中代表真实概率的
是：" 其中￥\bar{P_{i,j}}$代表真实概率："?

2017-05-16 06:13 UTC, qingqing01 commented on ltr/README.md
> +\lambda _{i,j}=\frac{\partial C}{\partial s_{i}} = \frac{1}{2}(1-S_{i,j})-\frac{1}{1+e^{\sigma (s_{i}-s_{j})}}
该公式没有正常显示：https://github.com/dzhwinter/models/tree/model_ltr2/ltr

2017-05-16 06:13 UTC, qingqing01 commented on ltr/README.md
> +- 全连接层(fully connected layer) : 指上一层中的每个节点都连接到下层网络。本例子中同样使用paddle.layer.fc实现，注意输入到RankCost层的全连接层输出为1x1的层结构
使用paddle.layer.fc ...   全连接层的维度为1。

2017-05-16 06:13 UTC, qingqing01 commented on ltr/README.md
> +- RankCost层： RankCost层是排序网络RankNet的核心，度量docA相关性是否比docB好，给出预测值并和label比较。使用了交叉熵(cross enctropy)作为度量损失函数，使用梯度下降方法进行优化。细节可见[RankNet](http://icml.cc/2015/wp-content/uploads/2015/06/icml_ranking.pdf)[4]
行尾需要句号

2017-05-16 06:13 UTC, qingqing01 commented on ltr/README.md
> +上述结构中使用了和前述图表相同的模型结构，使用了两层隐藏层，分别使用了`hidden_size=10`的全连接层和`hidden_size=1`的全连接层。本例子中的input_dim指输入**单个文档**的特征dense_vector的维度，label取值为1，-1。每条输入样本为`<label>，<docA, docB>`的结构，以docA为例，输入`input_dim`的文档特征，依次变换
本例子中的input_dim指输入**单个文档**的特征维度。

2017-05-16 06:13 UTC, qingqing01 commented on ltr/README.md
> +\<query_id\> \<relevance_score\> \<feature_vector\>的格式
feature_vector为什么是："0:0.1, 1:0.2, 2:0.4" 的格式？

2017-05-16 06:13 UTC, qingqing01 commented on ltr/README.md
> +```
dict可以对齐 (小问题)

2017-05-16 06:13 UTC, qingqing01 commented on ltr/README.md
> +$$\lambda _{i,j}=\frac{\partial C}{\partial s_{i}}=-\frac{\sigma }{1+e^{\sigma (s_{i}-s{j})}}|\Delta NDCG|$$
同样公式没有正确显示：https://github.com/dzhwinter/models/tree/model_ltr2/ltr

2017-05-16 06:13 UTC, qingqing01 commented on ltr/README.md
> +上述结构中使用了和前述图表相同的模型结构，和RankNet相似，分别使用了`hidden_size=10`的全连接层和`hidden_size=1`的全连接层。本例子中的input_dim指输入**单个文档**的特征dense_vector的维度，label取值为1，-1。每条输入样本为label，\<docA, docB\>的结构，以docA为例，输入input_dim的文档特征，依次变换成
**单个文档**的特征维度，

2017-05-16 06:13 UTC, qingqing01 commented on ltr/README.md
> +上述结构中使用了和前述图表相同的模型结构，和RankNet相似，分别使用了`hidden_size=10`的全连接层和`hidden_size=1`的全连接层。本例子中的input_dim指输入**单个文档**的特征dense_vector的维度，label取值为1，-1。每条输入样本为label，\<docA, docB\>的结构，以docA为例，输入input_dim的文档特征，依次变换成
这段显示有些乱码，注意下。https://github.com/dzhwinter/models/tree/model_ltr2/ltr

2017-05-16 06:13 UTC, qingqing01 commented on ltr/README.md
> +上面的代码使用了paddle内置的排序数据，如果希望使用自定义格式数据。可以参考Paddle内置的`mq2007`数据集，编写一个生成器函数。例如输入数据为如下格式，只包含doc0-doc2三个文档。
如果希望使用自定义格式数据。 ->  如果希望使用自定义格式数据， 句号改成逗号。

2017-05-16 06:13 UTC, qingqing01 commented on ltr/README.md
> +上面的代码使用了paddle内置的mq2007数据，如果希望使用自定义格式数据。可以参考Paddle内置的`mq2007`数据集，编写一个生成器函数。例如输入数据为如下格式，只包含doc0-doc2三个文档。
和"用户自定义RankNet数据"这节中重复的话可以去掉吧。

2017-05-16 06:13 UTC, qingqing01 commented on ltr/lambdaRank.py
> +import sqlite3
sqlite3没用的话去掉

2017-05-16 06:13 UTC, qingqing01 commented on ltr/lambdaRank.py
> +  """
注释对齐~

2017-05-16 06:13 UTC, qingqing01 commented on ltr/metrics.py
> +def ndcg(score_list):
写一些注释~

2017-05-16 06:13 UTC, qingqing01 commented on ltr/lambdaRank.py
> +    lambdaRank_infer(pass_id=2)
觉得train和infer分开好些，python lambdaRank.py --train/infer 这样子？ book里面放在一起我觉得是因为使用jupyter-notebook都是一个文件。 models里觉得可以分为两个步骤的~

2017-05-16 06:13 UTC, qingqing01 commented on ltr/README.md
> +用户运行`python ranknet.py`将会将每个轮次的模型存下来，并在测试数据上测试效果。
`python ranknet.py` 重要的运行命令单独一行~

2017-05-16 06:13 UTC, qingqing01 commented on ltr/lambdaRank.py
> +        paddle.reader.shuffle(fill_default_test, buf_size=100), batch_size=32)
test集不需要shuffle~

2017-05-16 06:13 UTC, qingqing01 commented on ltr/ranknet.py
> +        paddle.reader.buffered(paddle.dataset.mq2007.test, size=100),
为什么train_reader没有使用paddle.reader.buffered，而test用了？

2017-05-16 06:13 UTC, qingqing01 commented on ltr/ranknet.py
> +        batch_size=100)
batch_size=100是随意设置的嘛？ 这里是100，上面lambdaRank是32~

2017-05-16 06:13 UTC, qingqing01 commented on ltr/ranknet.py
> +from metrics import ndcg
ndcg没看哪里用了ndcg~

2017-05-16 06:13 UTC, qingqing01 commented on ltr/README.md
> +用户运行`python lambdaRank.py`将会把每个轮次的模型存下来，并在测试数据上测试效果。
`python lambdaRank.py`重要执行命令另起一行，醒目一些~

2017-05-16 09:43 UTC, dzhwinter commented on ltr/README.md
> +[RankNet](http://icml.cc/2015/wp-content/uploads/2015/06/icml_ranking.pdf)是一种经典的Pairwise的排序学习方法，是典型的前向神经网络排序模型。在文档集合S中的第i个文档记做`Ui`，它的文档特征向量记做`xi`，对于给定的一个文档对`<Ui, Uj>`，RankNet将输入的单个文档特征向量x映射到`f(x)`，得到
fix done.

2017-05-16 09:44 UTC, dzhwinter commented on ltr/README.md
> +其中代表真实概率的
意思是“其中$\bar{P_{i,j}}$代表真实概率，记做”， fix

2017-05-16 09:45 UTC, dzhwinter commented on ltr/README.md
> +\lambda _{i,j}=\frac{\partial C}{\partial s_{i}} = \frac{1}{2}(1-S_{i,j})-\frac{1}{1+e^{\sigma (s_{i}-s_{j})}}
fix done

2017-05-16 09:46 UTC, dzhwinter commented on ltr/README.md
> +- 全连接层(fully connected layer) : 指上一层中的每个节点都连接到下层网络。本例子中同样使用paddle.layer.fc实现，注意输入到RankCost层的全连接层输出为1x1的层结构
fix

2017-05-16 09:47 UTC, dzhwinter commented on ltr/README.md
> +- RankCost层： RankCost层是排序网络RankNet的核心，度量docA相关性是否比docB好，给出预测值并和label比较。使用了交叉熵(cross enctropy)作为度量损失函数，使用梯度下降方法进行优化。细节可见[RankNet](http://icml.cc/2015/wp-content/uploads/2015/06/icml_ranking.pdf)[4]
fix done

2017-05-16 09:48 UTC, dzhwinter commented on ltr/README.md
> +上述结构中使用了和前述图表相同的模型结构，使用了两层隐藏层，分别使用了`hidden_size=10`的全连接层和`hidden_size=1`的全连接层。本例子中的input_dim指输入**单个文档**的特征dense_vector的维度，label取值为1，-1。每条输入样本为`<label>，<docA, docB>`的结构，以docA为例，输入`input_dim`的文档特征，依次变换
fix

2017-05-16 09:51 UTC, dzhwinter commented on ltr/README.md
> +用户运行`python ranknet.py`将会将每个轮次的模型存下来，并在测试数据上测试效果。
👍

2017-05-16 09:53 UTC, dzhwinter commented on ltr/README.md
> +\<query_id\> \<relevance_score\> \<feature_vector\>的格式
libsvm的数据格式是最常用的吧？只是为了方便举例和应用。
已加入注释

2017-05-16 09:53 UTC, dzhwinter commented on ltr/README.md
> +```
fix done

2017-05-16 09:54 UTC, dzhwinter commented on ltr/README.md
> +$$\lambda _{i,j}=\frac{\partial C}{\partial s_{i}}=-\frac{\sigma }{1+e^{\sigma (s_{i}-s{j})}}|\Delta NDCG|$$
这个怎么在github preview？ 本地显示正常的

2017-05-16 09:56 UTC, dzhwinter commented on ltr/README.md
> +上述结构中使用了和前述图表相同的模型结构，和RankNet相似，分别使用了`hidden_size=10`的全连接层和`hidden_size=1`的全连接层。本例子中的input_dim指输入**单个文档**的特征dense_vector的维度，label取值为1，-1。每条输入样本为label，\<docA, docB\>的结构，以docA为例，输入input_dim的文档特征，依次变换成
fix

2017-05-16 09:56 UTC, dzhwinter commented on ltr/README.md
> +用户运行`python lambdaRank.py`将会把每个轮次的模型存下来，并在测试数据上测试效果。
fix

2017-05-16 09:58 UTC, dzhwinter commented on ltr/README.md
> +上面的代码使用了paddle内置的mq2007数据，如果希望使用自定义格式数据。可以参考Paddle内置的`mq2007`数据集，编写一个生成器函数。例如输入数据为如下格式，只包含doc0-doc2三个文档。
我考虑有用户只看LambdaRank部分？ 这个例子和RankNet是分离独立的，介绍如何构造自己数据的过程用户不会到前文去找

2017-05-16 10:00 UTC, dzhwinter commented on ltr/lambdaRank.py
> +import sqlite3
fix

2017-05-16 10:01 UTC, dzhwinter commented on ltr/lambdaRank.py
> +    lambdaRank_infer(pass_id=2)
我觉得放在一起好一些。用户不需要再去看新的参数，直接运行，log会显示infer的过程。

2017-05-16 10:02 UTC, dzhwinter commented on ltr/lambdaRank.py
> +    lambdaRank_infer(pass_id=2)
而且python 这种script类型的文件，可以随时更改

2017-05-16 10:02 UTC, dzhwinter commented on ltr/lambdaRank.py
> +  """
fix

2017-05-16 10:02 UTC, dzhwinter commented on ltr/lambdaRank.py
> +        paddle.reader.shuffle(fill_default_test, buf_size=100), batch_size=32)
fix

2017-05-16 10:04 UTC, dzhwinter commented on ltr/metrics.py
> +def ndcg(score_list):
ok

2017-05-16 10:07 UTC, dzhwinter commented on ltr/ranknet.py
> +from metrics import ndcg
ndcg在training过程中，作为函数传不进去

2017-05-16 10:16 UTC, dzhwinter commented on ltr/lambdaRank.py
> +        paddle.reader.shuffle(fill_default_test, buf_size=100), batch_size=32)
done

2017-05-16 10:16 UTC, dzhwinter commented on ltr/lambdaRank.py
> +  """
done

2017-05-16 10:16 UTC, dzhwinter commented on ltr/ranknet.py
> +from metrics import ndcg
这个是排序的基准函数，python里不能传递到training过程中

2017-05-16 10:16 UTC, dzhwinter commented on ltr/ranknet.py
> +        paddle.reader.buffered(paddle.dataset.mq2007.test, size=100),
因为test不用shuffle，使用buffered比lambda函数接口用的人员门槛更低

2017-05-16 10:16 UTC, dzhwinter commented on ltr/ranknet.py
> +        batch_size=100)
因为lambdaRank对的是List，数量比rankNet少得多。否则看不到训练过程

2017-05-16 10:16 UTC, dzhwinter commented on ltr/lambdaRank.py
> +import sqlite3
fix done

2017-05-17 04:58 UTC, qingqing01 commented on ltr/ranknet.py
> +        paddle.reader.buffered(paddle.dataset.mq2007.test, size=100),
buffered是有特殊用途的，并不是为了避免"lambda函数接口"设计的。book里很多例子也不用lambda函数的，如果非得用lambda，还是paddle.dataset.mq2007.test没有写正确~

2017-05-17 09:19 UTC, dzhwinter commented on ltr/ranknet.py
> +        paddle.reader.buffered(paddle.dataset.mq2007.test, size=100),
噢 fixit

2017-05-17 12:39 UTC, qingqing01 requested changes
文档写的挺好的~

2017-05-17 12:39 UTC, qingqing01 commented on ltr/README.md
> +  Pointwise方法是通过近似为回归问题解决排序问题，输入的单条样本为得分-文档，将每个查询-文档对的相关性得分作为实数分数或者序数分数，使得单个查询-文档对作为样本点(Pointwise的由来)，训练排序模型。预测时候对于指定输入，给出查询-文档对的相关性得分
“得分-文档“ 加粗突出

2017-05-17 12:39 UTC, qingqing01 commented on ltr/README.md
> +  Pairwise方法是通过近似为分类问题解决排序问题，输入的单条样本为标签-文档对。对于一次查询的多个结果文档，组合任意两个文档形成文档对作为输入样本。即学习一个二分类器，对输入的一对文档对AB（Pairwise的由来），根据A相关性是否比B好，二分类器给出分类标签+1或-1。对所有文档对进行分类，就可以得到一组偏序关系，从而构造文档全集的排序关系。该类方法的原理是对给定的文档全集S，降低排
“标签-文档对” 加粗突出

2017-05-17 12:39 UTC, qingqing01 commented on ltr/README.md
> +  Listwise方法是直接优化排序列表，输入为单条样本为一个文档排列。通过构造合适的度量函数衡量当前文档排序和最优排序差值，优化度量函数得到排序模型。由于度量函数很多具有非连续性，优化困难。
“文档排列” 加粗突出

2017-05-17 12:39 UTC, qingqing01 commented on ltr/README.md
> + `python ranknet.py`
注意格式：
```python
python ranknet.py
```

2017-05-17 12:39 UTC, qingqing01 commented on ltr/README.md
> +由于Pairwise中的网络结构是左右对称，可定义一半网络结构，另一半共享网络参数。使用PaddlePaddle实现RankNet排序模型，定义网络结构的示例代码如下：
需要说明参数是如何共享的~

2017-05-17 12:39 UTC, qingqing01 commented on ltr/README.md
> +\<query_id\> \<relevance_score\> \<feature_vector\>的格式(feature_vector采用libsvm数据格式)
libsvm数据格式是啥？可以加参考链接

2017-05-17 12:39 UTC, qingqing01 commented on ltr/README.md
> +[6]Schölkopf B, Platt J, Hofmann T. Learning to Rank with Nonsmooth Cost Functions[C]// Conference on Advances in Neural Information Processing Systems. MIT Press, 2006:193-200.
参考文献格式不统一，双引号貌似是中文的。

2017-05-17 12:39 UTC, qingqing01 commented on ltr/ranknet.py
> +from metrics import ndcg
也就是说没用到？ 文档中说明下metrics.py函数用途吧。

2017-05-17 12:39 UTC, qingqing01 commented on ltr/README.md
> +`python ranknet.py`
使用代码格式

2017-05-17 12:39 UTC, qingqing01 commented on ltr/README.md
> +`python lambdaRank.py`
使用代码格式~

2017-05-17 12:39 UTC, qingqing01 commented on ltr/README.md
> +将会自动下载数据，训练RankNet模型，并将每个轮次的模型存下来，并在测试数据上测试效果。
需要说明下这个脚本包含啥：训练和预测，预测的结果是啥？

2017-05-17 12:39 UTC, qingqing01 commented on ltr/ranknet.py
> +    predicitons = paddle.infer(
预测只返回predicitons，没有任何说明和打印信息，不知道predicitons是啥~

2017-05-17 12:39 UTC, qingqing01 commented on ltr/lambdaRank.py
> +    lambdaRank_infer(pass_id=2)
ok~

2017-05-17 12:39 UTC, qingqing01 commented on ltr/README.md
> +```
按照看reader设计格式写吧：https://github.com/PaddlePaddle/Paddle/tree/develop/doc/design/reader#data-reader-interface

这样直接yield，训练时就得用lambda吧。下面同样需要修改。

2017-05-17 12:41 UTC, qingqing01 commented
另外，两种方法都提供训练结果~

2017-05-19 09:11 UTC, qingqing01 commented
提到的一些问题还没有修改，另外 @luotao1 麻烦再帮忙看下?

2017-05-22 08:42 UTC, dzhwinter commented on ltr/ranknet.py
> +from metrics import ndcg
fix done.

2017-05-22 08:48 UTC, dzhwinter commented on ltr/ranknet.py
> +    predicitons = paddle.infer(
add more helper information

2017-05-22 08:48 UTC, dzhwinter commented on ltr/ranknet.py
> +from metrics import ndcg
thanks for the recommendation!

2017-05-22 08:48 UTC, dzhwinter commented on ltr/lambdaRank.py
> +    lambdaRank_infer(pass_id=2)
已经在文档中分节注释

2017-05-22 09:11 UTC, dzhwinter commented on ltr/README.md
> + `python ranknet.py`
fix done

2017-05-22 09:11 UTC, dzhwinter commented on ltr/README.md
> +  Pointwise方法是通过近似为回归问题解决排序问题，输入的单条样本为得分-文档，将每个查询-文档对的相关性得分作为实数分数或者序数分数，使得单个查询-文档对作为样本点(Pointwise的由来)，训练排序模型。预测时候对于指定输入，给出查询-文档对的相关性得分
fix done

2017-05-22 09:11 UTC, dzhwinter commented on ltr/README.md
> +  Pairwise方法是通过近似为分类问题解决排序问题，输入的单条样本为标签-文档对。对于一次查询的多个结果文档，组合任意两个文档形成文档对作为输入样本。即学习一个二分类器，对输入的一对文档对AB（Pairwise的由来），根据A相关性是否比B好，二分类器给出分类标签+1或-1。对所有文档对进行分类，就可以得到一组偏序关系，从而构造文档全集的排序关系。该类方法的原理是对给定的文档全集S，降低排
fix done

2017-05-22 09:11 UTC, dzhwinter commented on ltr/README.md
> +  Listwise方法是直接优化排序列表，输入为单条样本为一个文档排列。通过构造合适的度量函数衡量当前文档排序和最优排序差值，优化度量函数得到排序模型。由于度量函数很多具有非连续性，优化困难。
fix done

2017-05-22 09:11 UTC, dzhwinter commented on ltr/README.md
> +由于Pairwise中的网络结构是左右对称，可定义一半网络结构，另一半共享网络参数。使用PaddlePaddle实现RankNet排序模型，定义网络结构的示例代码如下：
fix done

2017-05-22 09:11 UTC, dzhwinter commented on ltr/README.md
> +`python ranknet.py`
fix

2017-05-22 09:11 UTC, dzhwinter commented on ltr/README.md
> +将会自动下载数据，训练RankNet模型，并将每个轮次的模型存下来，并在测试数据上测试效果。
补充了预测部分

2017-05-22 09:11 UTC, dzhwinter commented on ltr/README.md
> +\<query_id\> \<relevance_score\> \<feature_vector\>的格式(feature_vector采用libsvm数据格式)
fix done

2017-05-22 09:11 UTC, dzhwinter commented on ltr/README.md
> +`python lambdaRank.py`
fix done

2017-05-22 09:11 UTC, dzhwinter commented on ltr/README.md
> +[6]Schölkopf B, Platt J, Hofmann T. Learning to Rank with Nonsmooth Cost Functions[C]// Conference on Advances in Neural Information Processing Systems. MIT Press, 2006:193-200.
fix done

2017-05-22 09:11 UTC, dzhwinter commented on ltr/README.md
> +```
fix done

2017-05-23 13:41 UTC, lcy-seso requested changes
some small modifications.

2017-05-23 13:41 UTC, lcy-seso commented on ltr/lambdaRank.py
> +#lambdaRank is listwise learning to rank algorithm
LambdaRank is a listwise learning to rank algorithm.

2017-05-23 13:41 UTC, lcy-seso commented on ltr/lambdaRank.py
> +    name="/hidden_1",
@qingqing01 数据集和原来不太一样，可以接受这个变化。

2017-05-23 13:41 UTC, lcy-seso commented on ltr/README.md
> +排序学习技术[1] 是构建排序模型的机器学习方法，在信息检索，自然语言处理，数据挖掘等机器学场景中具有重要作用。排序学习的主要目的是对给定一组文档，对任意查询请求给出反映相关性的文档排序。在本例子中，利用标注过的语料库训练两种经典排序模型RankNet[4]和LamdaRank[6]，分别可以生成对应的排序模型，能够对任意查询请求，给出相关性文档排序。
参考文献这里的markdown标记不太对，请用下面这种标记方式：
\[[1](#参考文献)\]

2017-05-23 13:41 UTC, lcy-seso commented on ltr/README.md
> +同时，得到文档Ui在排序优化过程的梯度信息为
Ui --> $U_i$

2017-05-23 13:41 UTC, lcy-seso commented on ltr/README.md
> +而Sij = {+1,-1}，表示Ui和Uj组成的Pair的标签，即Ui相关性是否好于Uj。
这一行的几个符号请都改成Latex公式。
1. Sij = {+1,-1} --> $S_{ij} = {+1,-1}$
2. Ui --> $U_i$
3. Uj --> $U_j$

2017-05-23 13:41 UTC, lcy-seso commented on ltr/README.md
> +由于排序度量函数大多数非连续，非光滑，因此RankNet需要一个可以优化的度量函数C。首先使用交叉熵作为度量函数衡量预测代价，将损失函数C记做
这一行中的C都用Latex公式表示。
C --> $C$

2017-05-23 13:41 UTC, lcy-seso commented on ltr/README.md
> +[RankNet](http://icml.cc/2015/wp-content/uploads/2015/06/icml_ranking.pdf)是一种经典的Pairwise的排序学习方法，是典型的前向神经网络排序模型。在文档集合S中的第i个文档记做$U_i$，它的文档特征向量记做$x_i$，对于给定的一个文档对$U_i, U_j$，RankNet将输入的单个文档特征向量x映射到$f(x)$，
请把这一行中的字母都修改为Latex公式。
1. S--> $S$
2. i --> $i$
3. Uj --> $U_j$
4. x --> $x$

2017-05-23 13:41 UTC, lcy-seso commented on ltr/README.md
> +
98 ~ 99 是多余的空格吗？

2017-05-23 13:41 UTC, lcy-seso commented on ltr/README.md
> +需要将输入样本转换为PairWise的输入格式，例如组合生成格式与mq2007 PairWise格式相同的结构
PairWise --> Pairwise 和文章其它部分保持一致。

2017-05-23 13:41 UTC, lcy-seso commented on ltr/README.md
> +```
63 ~ 64 行多余空格吗？

2017-05-23 13:41 UTC, lcy-seso commented on ltr/README.md
> +
这些多余的空格都去掉吧，空一行即可。

2017-05-23 13:41 UTC, lcy-seso commented on ltr/README.md
> +
99~100行多余空格去掉

2017-05-23 13:41 UTC, lcy-seso commented on ltr/README.md
> +LearningToRank是和业务场景结合非常紧密的常用机器学习方法，排序模型构造方法一般可划分为PointWise方法，PairWise方法，ListWise方法，本例子中以LETOR的mq2007数据为例，阐述了PairWise的经典方法RankNet和ListWise方法中的LambdaRank，展示如何使用Paddle框架构造对应的排序模型结构，并提供了自定义数据类型样例。Paddle
PairWise 在文章中不统一，建议全文替换成统一的，Pairwise或则PairWise 都可以，但保持统一。

2017-05-23 13:41 UTC, lcy-seso commented on ltr/README.md
> +[1] https://en.wikipedia.org/wiki/Learning_to_rank
参考文献改为markdown的list表示，去掉方括号。
1.

2017-05-24 08:06 UTC, dzhwinter commented on ltr/README.md
> +```
deleted

2017-05-24 10:32 UTC, qingqing01 approved these changes
LGTM.

2017-05-24 10:35 UTC, lcy-seso approved these changes
LGTM.

2017-05-24 10:36 UTC, merged

2017-05-24 11:16 UTC, dzhwinter commented on ltr/README.md
> +排序学习技术[1] 是构建排序模型的机器学习方法，在信息检索，自然语言处理，数据挖掘等机器学场景中具有重要作用。排序学习的主要目的是对给定一组文档，对任意查询请求给出反映相关性的文档排序。在本例子中，利用标注过的语料库训练两种经典排序模型RankNet[4]和LamdaRank[6]，分别可以生成对应的排序模型，能够对任意查询请求，给出相关性文档排序。
fixed

2017-05-24 11:16 UTC, dzhwinter commented on ltr/README.md
> +
done

2017-05-24 11:16 UTC, dzhwinter commented on ltr/README.md
> +[RankNet](http://icml.cc/2015/wp-content/uploads/2015/06/icml_ranking.pdf)是一种经典的Pairwise的排序学习方法，是典型的前向神经网络排序模型。在文档集合S中的第i个文档记做$U_i$，它的文档特征向量记做$x_i$，对于给定的一个文档对$U_i, U_j$，RankNet将输入的单个文档特征向量x映射到$f(x)$，
done

2017-05-24 11:16 UTC, dzhwinter commented on ltr/README.md
> +由于排序度量函数大多数非连续，非光滑，因此RankNet需要一个可以优化的度量函数C。首先使用交叉熵作为度量函数衡量预测代价，将损失函数C记做
done

2017-05-24 11:16 UTC, dzhwinter commented on ltr/README.md
> +同时，得到文档Ui在排序优化过程的梯度信息为
done

2017-05-24 11:16 UTC, dzhwinter commented on ltr/README.md
> +需要将输入样本转换为PairWise的输入格式，例如组合生成格式与mq2007 PairWise格式相同的结构
done