add scene_text_recognition
PaddlePaddle/models pull request #329
Opened 2017-09-27 09:09 UTC by peterzhang2029

resolve https://github.com/PaddlePaddle/models/issues/328

2017-09-27 12:44 UTC, lcy-seso requested changes

2017-09-27 12:44 UTC, lcy-seso commented on scene_text_recognition/README.md
> +本文将针对 **场景文字识别 (STR, Scene Text Recognition)** 任务，演示如何用 PaddlePaddle 实现 一个端对端 CTC 的模型 **CRNN(Convolutional Recurrent Neural Network)**
本例演示如何用 PaddlePaddle 完成场景文字识别任务。

2017-09-27 12:44 UTC, lcy-seso commented on scene_text_recognition/README.md
> +训练脚本参照 [./train.py](./train.py)，设置了如下命令行参数：
- 什么叫：”训练脚本参照 `train.py`，设置了如下命令行参数“ ？这句话并不通顺。

2017-09-27 12:44 UTC, lcy-seso commented on scene_text_recognition/README.md
> +预测部分由infer.py完成，本示例对于ctc的预测使用的是最优路径解码算法(CTC greedy decoder)，即在每个时间步选择一个概率最大的字符。在使用过程中，需要在infer.py中指定具体的模型目录、图片固定尺寸、batch_size和图片文件的列表文件。例如：
预测使用的是最优路径解码算法，即：

2017-09-27 12:44 UTC, lcy-seso commented on scene_text_recognition/data_provider.py
> +import cv2
- 请按照 Paddle repo的风格，统一docstring的风格。

2017-09-27 12:44 UTC, lcy-seso commented on scene_text_recognition/model.py
> +
- 用for循环来定义 17 ~ 56 行。
- 如果要用 Class 来封装模型的定义，不要混用。把这个函数移入 Model 类中。

2017-09-27 12:44 UTC, lcy-seso commented on scene_text_recognition/model.py
> +        if self.is_infer == False:
请加上 ctc error evaluator。

2017-09-27 12:44 UTC, lcy-seso commented on scene_text_recognition/train.py
> +import paddle.v2 as paddle
请把python 本身的model 放在前面，空一行，然后是自定义的module。

2017-09-27 12:44 UTC, lcy-seso commented on scene_text_recognition/train.py
> +                params.to_tar(f)
请为这个脚本写一个main 函数。

2017-09-27 12:44 UTC, lcy-seso commented on scene_text_recognition/README.md
> +\[[2](#参考文献)\]，具体的，本文使用如下图片进行训练，需要识别文字对应的文字 "keep"。
- 请不要写本文使用如下图片进行训练，需要识别文字对应的文字 "keep"。
- 如果要使用这个例子，请简单以这个图作为一个实例，介绍STR需要作什么。

2017-09-27 12:44 UTC, lcy-seso commented on scene_text_recognition/README.md
> +- `train_file_list` 训练数据的列表文件，每行一个路径加对应的text，格式类似：
- 不要用 ”格式类似：“，格式是什么样子就是什么样子，不是 ”格式类似：“

2017-09-28 07:57 UTC, peterzhang2029 commented
@lcy-seso update the commit

2017-09-28 07:58 UTC, peterzhang2029 commented on scene_text_recognition/README.md
> +本文将针对 **场景文字识别 (STR, Scene Text Recognition)** 任务，演示如何用 PaddlePaddle 实现 一个端对端 CTC 的模型 **CRNN(Convolutional Recurrent Neural Network)**
DONE

2017-09-28 07:58 UTC, peterzhang2029 commented on scene_text_recognition/README.md
> +\[[2](#参考文献)\]，具体的，本文使用如下图片进行训练，需要识别文字对应的文字 "keep"。
DONE

2017-09-28 07:58 UTC, peterzhang2029 commented on scene_text_recognition/README.md
> +训练脚本参照 [./train.py](./train.py)，设置了如下命令行参数：
DONE

2017-09-28 07:58 UTC, peterzhang2029 commented on scene_text_recognition/README.md
> +- `train_file_list` 训练数据的列表文件，每行一个路径加对应的text，格式类似：
DONE

2017-09-28 07:58 UTC, peterzhang2029 commented on scene_text_recognition/README.md
> +预测部分由infer.py完成，本示例对于ctc的预测使用的是最优路径解码算法(CTC greedy decoder)，即在每个时间步选择一个概率最大的字符。在使用过程中，需要在infer.py中指定具体的模型目录、图片固定尺寸、batch_size和图片文件的列表文件。例如：
DONE

2017-09-28 07:58 UTC, peterzhang2029 commented on scene_text_recognition/data_provider.py
> +import cv2
DONE

2017-09-28 07:58 UTC, peterzhang2029 commented on scene_text_recognition/train.py
> +import paddle.v2 as paddle
DONE

2017-09-28 07:59 UTC, peterzhang2029 commented on scene_text_recognition/train.py
> +                params.to_tar(f)
DONE

2017-10-25 06:23 UTC, ranqiu92 requested changes

2017-10-25 06:23 UTC, ranqiu92 commented on scene_text_recognition/README.md
> +```
\```bash
以下还有几个地方须做同样修改

2017-10-25 06:23 UTC, ranqiu92 commented on scene_text_recognition/README.md
> +本例将演示如何用 PaddlePaddle 完成 **场景文字识别 (STR, Scene Text Recognition)** 任务。以下图为例，给定一个场景图片，STR需要从图片中识别出对应的文字"keep":
句末用句号

2017-10-25 06:23 UTC, ranqiu92 commented on scene_text_recognition/data_provider.py
> +        # resize all images to a fixed shape
注释前可空行，注释后不要空行

2017-10-25 06:23 UTC, ranqiu92 commented on scene_text_recognition/infer.py
> +    model_path = "model.ctc-pass-9-batch-150-test.tar.gz"
预测用的具体参数通过命令行传入会比较方便

2017-10-25 06:23 UTC, ranqiu92 commented on scene_text_recognition/model.py
> +        :param with_bn: whether with batch normal.
batch normalization

2017-10-25 06:23 UTC, ranqiu92 commented on scene_text_recognition/train.py
> +                    params.to_tar(f)
trainer.save_parameter_to_tar(f)

2017-10-25 06:23 UTC, ranqiu92 commented on scene_text_recognition/infer.py
> +    model_path = "model.ctc-pass-9-batch-150-test.tar.gz"
此处的多个参数都是如此

2017-10-25 08:45 UTC, ranqiu92 requested changes

2017-10-25 08:45 UTC, ranqiu92 commented on scene_text_recognition/model.py
> +        :param num_classes: size of the character dict.
参数解释的首字母大写，以下也需要修改

2017-10-25 08:45 UTC, ranqiu92 commented on scene_text_recognition/data_provider.py
> +        :param train_image_paths_generator:
参数含义解释首字母大写，下同

2017-10-25 08:45 UTC, ranqiu92 commented on scene_text_recognition/data_provider.py
> +        load image and transform to 1-dimention vector
函数解释首字母大写

2017-10-25 08:45 UTC, ranqiu92 commented on scene_text_recognition/data_provider.py
> +        transform a word to a list of ids.
函数解释首字母大写

2017-10-25 08:45 UTC, ranqiu92 commented on scene_text_recognition/model.py
> +        # cutting CNN output into a sequence of feature vectors, which are
cut ...

2017-10-25 08:45 UTC, ranqiu92 commented on scene_text_recognition/model.py
> +        # map each step of RNN to character distribution.
map the output of RNNs to ...

2017-10-25 08:45 UTC, ranqiu92 commented on scene_text_recognition/model.py
> +        # label input as a ID list
a -> an

2017-10-25 12:11 UTC, ranqiu92 requested changes

2017-10-25 12:11 UTC, ranqiu92 commented on scene_text_recognition/utils.py
> +    Generate the file list for train and test data.
train -> training

2017-10-25 12:13 UTC, peterzhang2029 commented on scene_text_recognition/README.md
> +本例将演示如何用 PaddlePaddle 完成 **场景文字识别 (STR, Scene Text Recognition)** 任务。以下图为例，给定一个场景图片，STR需要从图片中识别出对应的文字"keep":
Done

2017-10-25 12:13 UTC, peterzhang2029 commented on scene_text_recognition/README.md
> +```
Done

2017-10-25 12:13 UTC, peterzhang2029 commented on scene_text_recognition/data_provider.py
> +        transform a word to a list of ids.
Done

2017-10-25 12:13 UTC, peterzhang2029 commented on scene_text_recognition/data_provider.py
> +        :param train_image_paths_generator:
Done

2017-10-25 12:13 UTC, peterzhang2029 commented on scene_text_recognition/infer.py
> +    model_path = "model.ctc-pass-9-batch-150-test.tar.gz"
Done

2017-10-25 12:13 UTC, peterzhang2029 commented on scene_text_recognition/model.py
> +        :param num_classes: size of the character dict.
Done

2017-10-25 12:13 UTC, peterzhang2029 commented on scene_text_recognition/model.py
> +        # cutting CNN output into a sequence of feature vectors, which are
Done

2017-10-25 12:13 UTC, peterzhang2029 commented on scene_text_recognition/model.py
> +        :param with_bn: whether with batch normal.
Done

2017-10-25 12:13 UTC, peterzhang2029 commented on scene_text_recognition/train.py
> +                    params.to_tar(f)
Done

2017-10-25 13:07 UTC, peterzhang2029 commented on scene_text_recognition/utils.py
> +    Generate the file list for train and test data.
Done

2017-10-26 08:58 UTC, ranqiu92 requested changes

2017-10-26 08:58 UTC, ranqiu92 commented on scene_text_recognition/README.md
> +- `model_save_dir` 模型参数会的保存目录目录， 默认为当前目录下的`models`目录。
请修改  "模型参数会的保存目录目录"

2017-10-27 02:03 UTC, peterzhang2029 commented on scene_text_recognition/README.md
> +- `model_save_dir` 模型参数会的保存目录目录， 默认为当前目录下的`models`目录。
Done

2017-10-27 02:34 UTC, ranqiu92 requested changes

2017-10-27 02:34 UTC, ranqiu92 commented on scene_text_recognition/README.md
> +- `model_save_dir` ：模型参数的保存目录，默认为当前路径下的`models`目录。
默认为`./models`。

2017-10-27 02:34 UTC, ranqiu92 commented on scene_text_recognition/README.md
> + `config.py` 脚本中包含了模型配置的参数以及对应的详细解释，代码如下：
模型配置和训练相关的参数

2017-10-27 02:34 UTC, ranqiu92 commented on scene_text_recognition/README.md
> +在现实生活中，许多图片中的文字为图片所处场景的理解提供了丰富的语义信息（例如：路牌、菜单、街道标语等）。同时，针对场景图片的文字识别技术的发展也促进了一些新型应用的产生，例如：\[[1](#参考文献)\]通过使用深度学习模型来自动识别路牌中的文字，帮助街景应用获取更加准确的地址信息。
场景图片文字识别技术，    去掉“针对” 和 第一个 “的”

2017-10-27 02:34 UTC, ranqiu92 commented on scene_text_recognition/README.md
> +通过修改 `config.py` 脚本可以实现对参数的调整。例如，通过修改 `use_gpu` 参数来指定是否使用 GPU 进行训练。
去掉 第一个 “通过”

2017-10-27 02:34 UTC, ranqiu92 commented on scene_text_recognition/README.md
> +预测部分由 `infer.py` 完成，使用的是最优路径解码算法，即：在每个时间步选择一个概率最大的字符。在使用过程中，需要在 `infer.py` 中指定具体的模型保存路径、图片固定尺寸、batch_size（默认设置为10）、标记词典路径和图片文件的列表文件。执行如下代码：
默认值为10

2017-10-27 02:34 UTC, ranqiu92 commented on scene_text_recognition/README.md
> +- 本示例使用的数据集较小，如有需要，可以选用其他更大的数据集\[[3](#参考文献)\]来训练模型。
保持前后一致 ，“本示例” -> “本例”

2017-10-27 03:26 UTC, peterzhang2029 commented on scene_text_recognition/README.md
> +在现实生活中，许多图片中的文字为图片所处场景的理解提供了丰富的语义信息（例如：路牌、菜单、街道标语等）。同时，场景图片文字识别技术的发展也促进了一些新型应用的产生，例如：\[[1](#参考文献)\]通过使用深度学习模型来自动识别路牌中的文字，帮助街景应用获取更加准确的地址信息。
Done

2017-10-27 03:26 UTC, peterzhang2029 commented on scene_text_recognition/README.md
> -通过 `config.py` 脚本修改训练和模型配置参数，脚本中有对可配置参数的详细解释，示例如下：
Done

2017-10-27 03:26 UTC, peterzhang2029 commented on scene_text_recognition/README.md
> +修改 `config.py` 脚本可以实现对参数的调整。例如，通过修改 `use_gpu` 参数来指定是否使用 GPU 进行训练。
Done

2017-10-27 03:26 UTC, peterzhang2029 commented on scene_text_recognition/README.md
> +预测部分由 `infer.py` 完成，使用的是最优路径解码算法，即：在每个时间步选择一个概率最大的字符。在使用过程中，需要在 `infer.py` 中指定具体的模型保存路径、图片固定尺寸、batch_size（默认为10）、标记词典路径和图片文件的列表文件。执行如下代码：
Done

2017-10-27 03:26 UTC, peterzhang2029 commented on scene_text_recognition/README.md
> +- `model_save_dir` ：模型参数的保存目录，默认为`./models`。
Done

2017-10-27 03:26 UTC, peterzhang2029 commented on scene_text_recognition/README.md
> +- 本例使用的数据集较小，如有需要，可以选用其他更大的数据集\[[3](#参考文献)\]来训练模型。
Done

2017-10-27 03:26 UTC, peterzhang2029 commented on scene_text_recognition/model.py
> +        # Get the image features with CNN.
Done

2017-10-27 03:26 UTC, peterzhang2029 commented on scene_text_recognition/model.py
> +        # Map the output of RNN to character distribution.
Done

2017-10-27 13:15 UTC, lcy-seso reviewed
Almost LGTM.

2017-10-27 13:15 UTC, lcy-seso commented on scene_text_recognition/network_conf.py
> +            tmp = img_conv_group(
return img_conv_group

2017-10-27 13:15 UTC, lcy-seso commented on scene_text_recognition/README.md
> +在现实生活中，许多图片中的文字为图片所处场景的理解提供了丰富的语义信息（例如：路牌、菜单、街道标语等）。同时，场景图片文字识别技术的发展也促进了一些新型应用的产生，例如：\[[1](#参考文献)\]通过使用深度学习模型来自动识别路牌中的文字，帮助街景应用获取更加准确的地址信息。
- "许多图片中的文字为图片所处场景的理解提供了丰富的语义信息 " 这句话不通顺。
- 第二句话：同时，场景图片文字识别技术的发展也促进了一些新型应用的产生，请先给“场景图片文字识别”下定义。

2017-10-27 13:15 UTC, lcy-seso commented on scene_text_recognition/README.md
> +本例将演示如何用 PaddlePaddle 完成 **场景文字识别 (STR, Scene Text Recognition)** 任务。如下图所示，给定一张场景图片，`STR` 需要从中识别出对应的文字"keep"。
如下图所示， --> 任务如下图所示

2017-10-27 13:15 UTC, lcy-seso commented on scene_text_recognition/README.md
> +图 1. 数据示例 "keep"
输入数据示例

2017-10-27 13:15 UTC, lcy-seso commented on scene_text_recognition/README.md
> +### 指定训练配置参数
修改配置参数

2017-10-27 13:15 UTC, lcy-seso commented on scene_text_recognition/README.md
> + `config.py` 脚本中包含了模型配置和训练相关的参数以及对应的详细解释，代码如下：
代码片段如下。

2017-10-27 13:15 UTC, lcy-seso commented on scene_text_recognition/README.md
> +修改 `config.py` 脚本可以实现对参数的调整。例如，通过修改 `use_gpu` 参数来指定是否使用 GPU 进行训练。
- 通过修改

2017-10-27 13:15 UTC, lcy-seso commented on scene_text_recognition/README.md
> +- `train_file_list` ：训练数据的列表文件，每行由图片的存储路径和对应的标记文本组成，具体格式为：
格式为：

2017-10-27 14:01 UTC, ranqiu92 commented on scene_text_recognition/README.md
> +修改 `config.py` 脚本可以实现对参数的调整。例如，通过修改 `use_gpu` 参数来指定是否使用 GPU 进行训练。
加 ”通过” 就缺乏主语了 @lcy-seso

2017-10-27 14:12 UTC, lcy-seso commented on scene_text_recognition/README.md
> +修改 `config.py` 脚本可以实现对参数的调整。例如，通过修改 `use_gpu` 参数来指定是否使用 GPU 进行训练。
祈使句可以不需要主语~ 不过这里都可以。我觉得可以按照个人意愿酌情修改。

2017-10-27 14:56 UTC, lcy-seso approved these changes
LGMT.

2017-10-27 15:34 UTC, ranqiu92 approved these changes

2017-10-29 03:05 UTC, merged