add nest text classification
PaddlePaddle/models pull request #367
Opened 2017-10-12 02:29 UTC by peterzhang2029

resolve https://github.com/PaddlePaddle/models/issues/366

2017-10-13 03:11 UTC, lcy-seso requested changes
please refine the doc first.

2017-10-13 03:11 UTC, lcy-seso commented on nested_sequence/text_classification/README.md
> +# 双层序列文本分类
基于双层序列的文本分类

2017-10-13 03:11 UTC, lcy-seso commented on nested_sequence/text_classification/README.md
> +序列数据是自然语言处理任务面对的一种主要输入数据类型：一句话是由词语构成的序列，多句话进一步构成了段落。因此，段落可以看作是一个嵌套的双层的序列，这个序列的每个元素又是一个序列。
1. 序列数据 --> 序列
2.  一句话是由词语构成的序列，多句话进一步构成了段落。 --> 句子由词语构成，而多个句子进一步构成了段落。
3. 因此，段落可以看作是一个嵌套的双层的序列 --> 这句话有错误：段落可以看作是一个嵌套的序列（或者叫作：双层序列），这个序列的每个元素又是一个序列。

2017-10-13 03:11 UTC, lcy-seso commented on nested_sequence/text_classification/README.md
> +双层序列是`PaddlePaddle`支持的一种非常灵活的数据组织方式，帮助我们更好地描述段落、多轮对话等更为复杂的语言数据。基于双层序列输入，我们可以设计一个层次化的网络，分别从词语和句子级别编码输入数据，更好地完成一些复杂的语言理解任务。
- 帮助我们 --> 能够帮助我们
- 基于双层序列输入 --> 以双层序列作为输入
- 更好地完成--> 从而更好地完成

2017-10-13 03:11 UTC, lcy-seso commented on nested_sequence/text_classification/README.md
> +本示例将演示如何使用`PaddlePaddle`来组织双层序列文本数据，完成文本分类任务。
- 本示例 --> 本例
- 本例演示如何在`PaddlePaddle` 中将长文本输入（通常能达到段落或者篇章基本）组织为双层序列，完成对长文本的分类任务。

2017-10-13 03:11 UTC, lcy-seso commented on nested_sequence/text_classification/README.md
> +对于文本分类，我们将一段文本看成句子的数组，每个句子又是单词的数组，这便是一种双层序列的输入数据。而将这个段落的每一句话用卷积神经网络编码为一个向量，再将每句话的表示向量经过池化层编码成一个段落的向量, 即可得到段落的表示向量。对于分类任务，将段落表示向量作为分类器的输入可以得到分类结果。
1. 删掉第一句“对于文本分类”
2. 单词 --> 词语
3. 删掉“这便是一种双层序列的输入数据。”
4. 请不要使用“数组”而是使用“序列”，请保证关键名词在行文过程中的一致性。

> 我们将一段文本看成句子的序列，而每个句子又是词语的序列。

5. 下面这些内容请另起一段。

> 我们首先用卷积神经网络编码段落中的每一句话；然后，将每句话的表示向量经过池化层得到段落的编码向量；最后将段落的编码向量作为分类器（以softmax层的全连接层）输入，得到最终的分类结果。

2017-10-13 03:11 UTC, lcy-seso commented on nested_sequence/text_classification/README.md
> +图1. 本例中的文本分类模型
基于双层序列的文本分类模型

2017-10-13 03:11 UTC, lcy-seso commented on nested_sequence/text_classification/README.md
> +PaddlePaddle 实现该网络结构的代码见 `network_conf.py`。
- 如果要对 PaddlePaddle 加上文本块标记，就请在全文中保持统一。
- 请去掉对 PaddlePaddle 的文本块标记，在models其它篇章中并不特殊处理。

2017-10-13 03:11 UTC, lcy-seso commented on nested_sequence/text_classification/README.md
> +对于双层序列的处理，需要先将双层时间序列数据先变换成单层时间序列数据，再对每一个单层时间序列进行处理。 PaddlePaddle提供了 `recurrent_group` 接口进行转换，在本例中，我们将文本数据的每一段，通过 recurrent_group 进行拆解，拆解成的每一句话再通过一个 CNN网络学习对应的向量表示。
1. 请区分 “对于” 和 “对” 的使用。
2. 这样描述并没有很好地反映   `recurrent_group` 的设计思想，这一段先简化处理，保证尽快merge。。

> 在 PaddlePaddle 中 ，`recurrent_group`  是帮助我们构建处理双层序列的层次化模型的主要工具。这里，我们使用2个嵌套的 `recurrent_group`。外层的 `recurrent_group` 将段落拆解为句子，`step` 函数中拿到的输入是句子序列；内层的`recurrent_group` 将句子拆解为词语，`step` 函数中拿到的输入是非序列的词语。

在词语级别，我们通过 CNN 网络以词向量为输入学习句子表示；在段落级别，将每个句子的表示通过池化作用得到段落表示。

2017-10-13 03:11 UTC, lcy-seso commented on nested_sequence/text_classification/README.md
> +对于双层序列的处理，需要先将双层时间序列数据先变换成单层时间序列数据，再对每一个单层时间序列进行处理。 PaddlePaddle提供了 `recurrent_group` 接口进行转换，在本例中，我们将文本数据的每一段，通过 recurrent_group 进行拆解，拆解成的每一句话再通过一个 CNN网络学习对应的向量表示。
1. 请区分 “对于” 和 “对” 的使用。
2. 这样描述并没有很好地反映   `recurrent_group` 的设计思想，这一段先简化处理，保证尽快merge。。

> 在 PaddlePaddle 中 ，`recurrent_group`  是帮助我们构建处理双层序列的层次化模型的主要工具。这里，我们使用2个嵌套的 `recurrent_group`。外层的 `recurrent_group` 将段落拆解为句子，`step` 函数中拿到的输入是句子序列；内层的`recurrent_group` 将句子拆解为词语，`step` 函数中拿到的输入是非序列的词语。

在词语级别，我们通过 CNN 网络以词向量为输入输出学习到的句子表示；在段落级别，将每个句子的表示通过池化作用得到段落表示。

2017-10-13 03:11 UTC, lcy-seso commented on nested_sequence/text_classification/README.md
> +对于双层序列的处理，需要先将双层时间序列数据先变换成单层时间序列数据，再对每一个单层时间序列进行处理。 PaddlePaddle提供了 `recurrent_group` 接口进行转换，在本例中，我们将文本数据的每一段，通过 recurrent_group 进行拆解，拆解成的每一句话再通过一个 CNN网络学习对应的向量表示。
1. 请区分 “对于” 和 “对” 的使用。
2. 这样描述并没有很好地反映   `recurrent_group` 的设计思想，这一段先简化处理，保证尽快merge。。

> 在 PaddlePaddle 中 ，`recurrent_group`  是帮助我们构建处理双层序列的层次化模型的主要工具。这里，我们使用2个嵌套的 `recurrent_group`。外层的 `recurrent_group` 将段落拆解为句子，`step` 函数中拿到的输入是句子序列；内层的`recurrent_group` 将句子拆解为词语，`step` 函数中拿到的输入是非序列的词语。

在词语级别，我们通过 CNN 网络以词向量为输入输出学习到的句子表示；在段落级别，将每个句子的表示通过池化作用得到段落表示。

2017-10-13 03:11 UTC, lcy-seso commented on nested_sequence/text_classification/README.md
> +使用`recurrent_group`接口进行变换时，需要将输入序列传入 `input` 属性。 由于本例要实现的变换是`双层时间序列 => 单层时间序列`，所以我们需要将输入数据标记成 `SubsequenceInput`。
先删掉这句话。文档应保证一定的技术精确性。

2017-10-13 03:11 UTC, lcy-seso commented on nested_sequence/text_classification/README.md
> +假设有如下格式的训练数据：每一行为一条样本，以 `\t` 分隔，第一列是类别标签，第二列是输入文本的内容。以下是两条示例数据：
假设有如下格式的训练数据 --> 输入数据格式如下：

2017-10-13 06:41 UTC, peterzhang2029 commented on nested_sequence/text_classification/README.md
> +PaddlePaddle 实现该网络结构的代码见 `network_conf.py`。
Done

2017-10-13 07:19 UTC, lcy-seso requested changes
1. 请统一加上docstring；
2. 加上 requirements.txt 文件；

2017-10-13 07:19 UTC, lcy-seso commented on nested_sequence/text_classification/README.md
> +1.修改 `infer.py` 中以下变量，指定使用的模型、指定测试数据。
1. 请把 `infer.py` 的使用方式也改成指定命令行参数，不要让用户来修改代码。
1. 今后 models 下模型的使用方式都保持统一，从命令行指定运行参数。请参考 generate chinese potery 的例子。

2017-10-13 07:19 UTC, lcy-seso commented on nested_sequence/text_classification/data/infer.txt
> +The original Vampires (1998) is one of my favorites. I was curious to see how a sequel would work considering they used none of the original characters. I was quite surprised at how this played out.
这个示例数据比较长，减少到能够说明问题的最少数据。

2017-10-13 07:19 UTC, lcy-seso commented on nested_sequence/text_classification/data/test_data/test.txt
> +1	I liked the film. Some of the action scenes were very interesting, tense and well done. I especially liked the opening scene which had a semi truck in it. A very tense action scene that seemed well
示例数据太长，减少到能够说明问题的最少数据。

2017-10-13 07:19 UTC, lcy-seso commented on nested_sequence/text_classification/data/train_data/train.txt
> +0	I admit that I am a vampire addict: I have seen so many vampire movies I have lost count and this one is definitely in the top ten. I was very impressed by the original John Carpenter's Vampires an
数据太长，减少到能够说明问题的最少数据。

2017-10-13 07:19 UTC, lcy-seso commented on nested_sequence/text_classification/infer.py
> +# -*- coding: utf-8 -*-
删掉 line 1 ~ 2

2017-10-13 07:19 UTC, lcy-seso commented on nested_sequence/text_classification/infer.py
> +if __name__ == "__main__":
用 python 下面的 import click 包，改成指定命令行参数，不要让用户来改代码。

2017-10-13 07:19 UTC, lcy-seso commented on nested_sequence/text_classification/reader.py
> +"""
删掉 line 1 ~ 2

2017-10-13 07:19 UTC, lcy-seso commented on nested_sequence/text_classification/train.py
> +import os
删掉line 1 ~ 2

2017-10-13 07:19 UTC, lcy-seso commented on nested_sequence/text_classification/utils.py
> +import logging
删掉line 1 ~ 2

2017-10-13 07:19 UTC, lcy-seso commented on nested_sequence/text_classification/utils.py
> +def parse_train_cmd():
可以直接用 click 包。

2017-10-13 07:22 UTC, lcy-seso reviewed
这个配置现在写的比较简单，希望后面可以加上文本卷积上的batch norm示例。可以在下一个PR里面做。

2017-10-13 10:29 UTC, peterzhang2029 commented on nested_sequence/text_classification/README.md
> +1.修改 `infer.py` 中以下变量，指定使用的模型、指定测试数据。
DONE

2017-10-13 10:29 UTC, peterzhang2029 commented on nested_sequence/text_classification/data/infer.txt
> +The original Vampires (1998) is one of my favorites. I was curious to see how a sequel would work considering they used none of the original characters. I was quite surprised at how this played out.
DONE

2017-10-13 10:29 UTC, peterzhang2029 commented on nested_sequence/text_classification/data/test_data/test.txt
> +1	I liked the film. Some of the action scenes were very interesting, tense and well done. I especially liked the opening scene which had a semi truck in it. A very tense action scene that seemed well
DONE

2017-10-13 10:29 UTC, peterzhang2029 commented on nested_sequence/text_classification/data/train_data/train.txt
> +0	I admit that I am a vampire addict: I have seen so many vampire movies I have lost count and this one is definitely in the top ten. I was very impressed by the original John Carpenter's Vampires an
DONE

2017-10-13 10:29 UTC, peterzhang2029 commented on nested_sequence/text_classification/infer.py
> +# -*- coding: utf-8 -*-
DONE

2017-10-13 10:29 UTC, peterzhang2029 commented on nested_sequence/text_classification/infer.py
> +if __name__ == "__main__":
DONE

2017-10-13 10:29 UTC, peterzhang2029 commented on nested_sequence/text_classification/reader.py
> +"""
DONE

2017-10-13 10:29 UTC, peterzhang2029 commented on nested_sequence/text_classification/train.py
> +import os
DONE

2017-10-13 10:29 UTC, peterzhang2029 commented on nested_sequence/text_classification/utils.py
> +import logging
DONE

2017-10-13 10:29 UTC, peterzhang2029 commented on nested_sequence/text_classification/utils.py
> +def parse_train_cmd():
DONE

2017-10-13 10:35 UTC, lcy-seso requested changes

2017-10-13 10:35 UTC, lcy-seso commented on nested_sequence/text_classification/infer.py
> +    default='models/params_pass_00000.tar.gz',
1. 不要设置这个默认参数，让这个字段变成 required 的，让用户来指定。
2. 需要的是一个目录来存储所有保存的模型，而不是一个文件名。不要让后面轮次的模型，覆盖前面的。留下来让用户做模型选择。

2017-10-13 10:35 UTC, lcy-seso commented on nested_sequence/text_classification/infer.py
> +          "if this parameter is not set, "
注释是一句独立的话，请英文首字母大写，以句号结束。

2017-10-13 10:35 UTC, lcy-seso commented on nested_sequence/text_classification/network_conf.py
> +    #output_group = paddle.layer.concat(input=[conv3, conv4])
这一行被删掉的代码是必须的吗？如果是请加注释，如果不是，请删掉。

2017-10-13 12:20 UTC, peterzhang2029 commented on nested_sequence/text_classification/infer.py
> +          "if this parameter is not set, "
DONE

2017-10-13 12:20 UTC, peterzhang2029 commented on nested_sequence/text_classification/infer.py
> +    default='models/params_pass_00000.tar.gz',
DONE

2017-10-13 12:20 UTC, peterzhang2029 commented on nested_sequence/text_classification/network_conf.py
> +    #output_group = paddle.layer.concat(input=[conv3, conv4])
DONE

2017-10-13 23:08 UTC, lcy-seso requested changes
1. 请把 docstring 全部补全；
2. 调整代码结构，增加配置文件，把所有网络结构，学习相关的超参数都独立到配置中，可以快速直接修改超参数，而不要在代码中找这些超参数。

2017-10-13 23:08 UTC, lcy-seso commented on nested_sequence/text_classification/network_conf.py
> +    conv3 = paddle.networks.sequence_conv_pool(
1. 请按照 rnn language model , GNR 的例子，将网络结构中的所有超参数全部独立出来。包括不限于：
    - 隐层大小；层数；
    - 正则，初始化等学习相关参数；

models 下新增的例子，请保持清晰地结构：让用户可以直接找到学习相关的超参数，直接进行修改，而不要让用户修改时在代码中找。

2017-10-13 23:25 UTC, lcy-seso requested changes

2017-10-13 23:25 UTC, lcy-seso commented on nested_sequence/text_classification/train.py
> +    "--class_num", type=int, default=2, help="The class number (default: 2).")
- 不要硬质定类别数目，让用户指定一个label字典，将 label 名字映射到编码，自动判断类别数目。

2017-10-13 23:25 UTC, lcy-seso commented on nested_sequence/text_classification/train.py
> +    hidden_size = 128
把超参数全部独立放在配置文件中。

2017-10-13 23:25 UTC, lcy-seso commented on nested_sequence/text_classification/train.py
> +    paddle.init(use_gpu=True, trainer_count=4)
1. models 下所有例子默认CPU，单线程执行。不要默认GPU四卡执行。
2. 把这两个设置放在配置中，在文档中提示修改这两个参数可以使用GPU多机多卡训练。

2017-10-13 23:25 UTC, lcy-seso commented on nested_sequence/text_classification/train.py
> +    # network config
代码里面的注释也尽量保证是完整的符合语法的一句话。不要只写几个名字，并且用并不是广泛接受的缩写。

2017-10-13 23:25 UTC, lcy-seso commented on nested_sequence/text_classification/train.py
> +    # create trainer
create the trainer instance.

2017-10-13 23:25 UTC, lcy-seso commented on nested_sequence/text_classification/train.py
> +    # create parameters
create all the trainable parameters.

2017-10-13 23:25 UTC, lcy-seso commented on nested_sequence/text_classification/train.py
> +    feeding = {"word": 0, "label": 1}
这个注释的位置不对，这里是指定feeding字典，不是 begin training.

2017-10-13 23:25 UTC, lcy-seso commented on nested_sequence/text_classification/train.py
> +        Define end batch and end pass event handler
如果是一句完整的话，请首字母大写，以句号结尾，注意必要的地方，名词前加冠词。

2017-10-13 23:33 UTC, lcy-seso commented on nested_sequence/text_classification/train.py
> +    # create optimizer
把 optimizer 的定义放在网络定义之前。

2017-10-15 10:26 UTC, peterzhang2029 commented on nested_sequence/text_classification/network_conf.py
> +    conv3 = paddle.networks.sequence_conv_pool(
Done

2017-10-15 10:26 UTC, peterzhang2029 commented on nested_sequence/text_classification/train.py
> +    "--class_num", type=int, default=2, help="The class number (default: 2).")
DONE

2017-10-15 10:26 UTC, peterzhang2029 commented on nested_sequence/text_classification/train.py
> +    hidden_size = 128
DONE

2017-10-15 10:26 UTC, peterzhang2029 commented on nested_sequence/text_classification/train.py
> +    paddle.init(use_gpu=True, trainer_count=4)
DONE

2017-10-15 10:26 UTC, peterzhang2029 commented on nested_sequence/text_classification/train.py
> +    # network config
DONE

2017-10-15 10:26 UTC, peterzhang2029 commented on nested_sequence/text_classification/train.py
> +    # create parameters
DONE

2017-10-15 10:26 UTC, peterzhang2029 commented on nested_sequence/text_classification/train.py
> +    # create optimizer
DONE

2017-10-15 10:26 UTC, peterzhang2029 commented on nested_sequence/text_classification/train.py
> +    # create trainer
DONE

2017-10-15 10:26 UTC, peterzhang2029 commented on nested_sequence/text_classification/train.py
> +    feeding = {"word": 0, "label": 1}
DONE

2017-10-15 10:26 UTC, peterzhang2029 commented on nested_sequence/text_classification/train.py
> +        Define end batch and end pass event handler
DONE

2017-10-15 10:50 UTC, lcy-seso requested changes

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/README.md
> +```
```python ，``` 后面少了 python

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/README.md
> +python train.py --train_data_dir 'data/train_data' --test_data_dir 'data/test_data' --word_dict_path 'word_dict.txt' --label_dict_path 'label_dict.txt'
命令加上换行符，放在一行之内太长了。
```bash
python train.py \
  --train_data_dir 'data/train_data'  \
  --test_data_dir 'data/test_data' \
  --word_dict_path 'word_dict.txt' \
  --label_dict_path 'label_dict.txt'
```

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/README.md
> +python infer.py --data_path 'data/infer.txt' --word_dict_path 'word_dict.txt' --label_dict_path 'label_dict.txt' --model_path 'models/params_pass_00000.tar.gz'
命令加上换行符，放在一行太长了。
```bash
python infer.py \
  --data_path 'data/infer.txt' \
  --word_dict_path 'word_dict.txt' \
  --label_dict_path 'label_dict.txt' \
  --model_path 'models/params_pass_00000.tar.gz'
```

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/config.py
> +    # whether to use GPU for training
whether to use GPU int training or not.

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/config.py
> +    # the number of threads used in one machine
The number of computing threads.

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/config.py
> +    # train batch size
The trainning batch size.

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/config.py
> +    # number of pass during training
The epoch number.

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/config.py
> +    # learning rate for optimizer
The global learning rate.

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/config.py
> +    # learning rate for L2Regularization
Please do not call it learning rate. Commonly this parameter is called the decay rate.

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/config.py
> +    # average_window for ModelAverage
This parameter is used for the averaged SGD. 
About the average_window * (number of the processed batch) parameters are used
for average. To be accurate, between average_window *(number of the processed batch)  and 2 * average_window * (number of the processed batch)  parameters are used for average.

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/config.py
> +    # embedding vector dimension
The dimension of embedding vector.

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/config.py
> +    # size of sentence vector representation and fc layer in cnn
The hidden size of sentence vectors.

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/config.py
> +    # log progress every log_period batches
The parameter to control logging period. Training log will be printed very log_period.

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/config.py
> +    # buffer size for shuffling
The buffer size of the data reader. The number of buffer size samples will be shuffled in training.

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/README.md
> +    Covolution group definition
- a typo.
- Convolution group definition.

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/index.html
> +    Covolution group definition
- a typo.
- The convolution group definition.

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/index.html
> +    :params hidden_size: Size of FC layer.
The size of the fully connected layer.
- 注释中名词是特指，前加 the。

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/index.html
> +`config.py`脚本中包含训练配置和模型配置的参数设置, 示例代码如下：
通过`config.py`脚本修改训练和模型配置参数，脚本中有对可配置参数的详细解释，示例如下：

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/index.html
> + 进行训练。
- 这句话不通顺。
- 修改 `config.py` 对参数进行调整。例如，通过修改 `use_gpu` 参数来指定是否使用 GPU进行训练。

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/infer.py
> +        label_reverse_dict = {0: "positive", 1: "negative"}
这个字典不要写死，写死了，替换为自己数据的时候要出错。

2017-10-15 10:50 UTC, lcy-seso commented on nested_sequence/text_classification/utils.py
> +def build_word_dict(data_dir, save_path, use_col=1, cutoff_fre=1):
这个文件中的函数，请加上docstring。

2017-10-15 13:08 UTC, peterzhang2029 commented on nested_sequence/text_classification/utils.py
> +def build_word_dict(data_dir, save_path, use_col=1, cutoff_fre=1):
DONE

2017-10-15 13:08 UTC, peterzhang2029 commented on nested_sequence/text_classification/infer.py
> +        label_reverse_dict = {0: "positive", 1: "negative"}
这里是内置imdb数据集的字典，不会与用户自定义的字典冲突，已经添加注释说明。

2017-10-15 13:19 UTC, lcy-seso approved these changes
LGTM.

2017-10-15 13:20 UTC, merged