Inpainting lbam
PaddlePaddle/models pull request #3714
Opened 2019-10-22 09:03 UTC by xhuanlc

release image inpainting codes for LBAM ICCV19, resolve  #3713

2019-10-25 10:03 UTC, HUSTLX commented
checking

2019-10-29 02:29 UTC, HUSTLX requested changes
good

2019-10-31 05:19 UTC, SunGaofeng commented on PaddleCV/Research/inpainting-lbam/ActivationFunction.py
> +    a = fluid.layers.clip(a, min=1.01, max=6.0)
这里创建的参数a需要在神经网络训练过程中不断迭代调整吗？还是固定值？

2019-10-31 05:19 UTC, SunGaofeng commented on PaddleCV/Research/inpainting-lbam/ActivationFunction.py
> +    out = fluid.layers.elementwise_pow(out, alpha_t)
此处用到了pow操作，从数学上来讲要求out > 0， 不然计算梯度的时候会出问题，实际使用过程中是否碰到问题了？

2019-10-31 05:19 UTC, SunGaofeng commented on PaddleCV/Research/inpainting-lbam/README.md
> +PaddlePaddle version == 1.4
这部分代码是在PaddlePaddle1.4上验证的？有没有在Paddle1.6上验证过？

2019-10-31 05:19 UTC, SunGaofeng commented on PaddleCV/Research/inpainting-lbam/test.py
> +    test()
只有test过程，没有training吗？

2019-11-04 04:06 UTC, SunGaofeng approved these changes
approved

2019-11-04 05:07 UTC, merged