Add post training quantization docs and demo
PaddlePaddle/models pull request #3948
Opened 2019-11-19 11:35 UTC by juncaipeng

Add post training quantization docs and demo

2019-11-21 03:35 UTC, wzzju commented on PaddleSlim/quant_low_level_api/README.md
> -<div align="center">
文档前面写一些总结性的话语。然后下面使用无序列表列举两个文档内容标题。
三篇文章使用一样的文章跳转表头，保持文档一致性。

2019-11-21 03:35 UTC, wzzju commented on PaddleSlim/quant_low_level_api/post_training_quantization.md
> +# 离线量化
加上一致的文章跳转表头。

2019-11-21 03:35 UTC, wzzju commented on PaddleSlim/quant_low_level_api/quantization_aware_training.md
> +> **注意:** 目前PaddlePaddle框架在Server端只支持使用float目录下的量化模型做预测。
同离线量化一样，量化训练也加上同样的模型量化后的精度对比。

2019-11-25 13:47 UTC, juncaipeng commented on PaddleSlim/quant_low_level_api/README.md
> -<div align="center">
> 文档前面写一些总结性的话语。然后下面使用无序列表列举两个文档内容标题。
> 三篇文章使用一样的文章跳转表头，保持文档一致性。

使用了相同的表头，链接相关内容。

2019-11-25 13:47 UTC, juncaipeng commented on PaddleSlim/quant_low_level_api/post_training_quantization.md
> +# 离线量化
> 加上一致的文章跳转表头。

Done

2019-11-25 13:47 UTC, juncaipeng commented on PaddleSlim/quant_low_level_api/quantization_aware_training.md
> +> **注意:** 目前PaddlePaddle框架在Server端只支持使用float目录下的量化模型做预测。
> 同离线量化一样，量化训练也加上同样的模型量化后的精度对比。

Done

2019-11-28 08:23 UTC, wzzju commented on PaddleSlim/quant_low_level_api/quantization_aware_training.md
> +-|:-:|:-:|:-:|:-:|:-:|:-:
精度提升请用正值，精度下降请用负值。

2019-11-28 08:23 UTC, wzzju commented on PaddleSlim/quant_low_level_api/post_training_quantization.md
> +googlenet   | 70.50% | 89.59% | 70.12% | 89.38% | 0.38% | 0.21%
精度提升请用正值，精度下降请用负值。

2019-11-28 11:54 UTC, juncaipeng commented on PaddleSlim/quant_low_level_api/quantization_aware_training.md
> +-|:-:|:-:|:-:|:-:|:-:|:-:
> 精度提升请用正值，精度下降请用负值。

两个表格都改了。

2019-11-28 15:06 UTC, wzzju requested changes

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/docs/tutorial.md
> +#### 1.2.3 离线量化
`#### 1.2.3 训练后量化`

PS: 将离线量化都统一写为“训练后量化”吧

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/docs/tutorial.md
建议：
`#### 1.2.2 量化训练框架` --> `#### 1.2.2 量化训练`
`#### 1.2.3 确定量化参数` --> `#### 1.2.2.3 确定量化训练比例系数`

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/docs/tutorial.md
> +离线量化是基于采样数据，采用KL散度等方法计算量化比例因子的方法。相比QAT量化，离线量化不需要重新训练，可以快速得到量化模型。
相比量化训练

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/docs/tutorial.md
> +离线量化的目标是求取量化比例因子，主要有两种方法：非饱和量化方法 ( No Saturation) 和饱和量化方法 (Saturation)。非饱和量化方法计算FP32类型Tensor中绝对值的最大值`abs_max`，将其映射为127，则量化比例因子等于`abs_max/127`。饱和量化方法使用KL散度计算一个合适的阈值`T` (`T<mab_max`)，将其映射为127，则量化比例因子等于
合适的阈值`T` (`0 < T < abs_max`)

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/docs/tutorial.md
> +* 读取样本数据，执行模型的前向推理，保存待量化op的激活Tensor的数值；
保存待量化op激活Tensor的数值；

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/quant_low_level_api/README.md
>      </a>
感觉标题太长了，可以考虑将`Low-Level API`这些去掉，另外，全文不要出现QAT量化，将其改为量化训练。离线量化也改成训练后量化，这样才是业界统一的说法。

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/quant_low_level_api/README.md
> +* [量化训练Low-Level API使用方法和示例](./quantization_aware_training.md)
这里的Low-Level API字眼保存，但是标题链接跳转中的`Low-Level API`（否则太丑了）。

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/quant_low_level_api/post_training_quantization.md
> +首先，需要准备已经训练好的FP32预测模型，即 `save_inference_model()` 保存的模型。离线量化读取样本数据进行前向计算，所以需要准备样本数据。样本数据最好是预测数据的中具有代表性的一部分，这样可以计算得到更加准确的量化比例因子。样本数据的数量可以是100~500，当然样本数据越多，计算的的量化比例因子越准确。
所以需要准备校准数据集。校准数据集应为测试集（或训练集）中具有代表性的一部分，如随机取出的部分数据， ......

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/docs/tutorial.md
>  <strong>表2：模型量化前后精度对比</strong>
全文不要出现QAT量化，将其改为量化训练。离线量化也改成训练后量化，这样才是业界统一的说法。
TODO：
1. 增加量化训练中QuantizationTransformPass和AddQuantDequantPass的使用说明，如可配置参数的说明；
2. 给出AddQuantDequantPass的使用方法及示例代码，注明需要在QuantizationTransformPass之后使用AddQuantDequantPass以达到对"elementwise_add", "pool2d"量化的效果；
3. 给出部分量化功能的使用方法及示例代码。

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/quant_low_level_api/post_training_quantization.md
> +2）**配置读取样本数据的接口**
2）**配置校准数据集生成器**

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/quant_low_level_api/post_training_quantization.md
> +* sample_generator：第二步中配置的读取样本数据的接口。
第二步中配置的校准数据集生成器。

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/quant_low_level_api/post_training_quantization.md
> +* model_filename：待量化模型的模型文件名，如果模型文件名不是`__model__`，则需要自行设置模型文件名。
则需要使用`model_filename`设置模型文件名。

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/quant_low_level_api/post_training_quantization.md
> +* params_filename：待量化模型的权重文件名，如果所有权重保存成一个文件，则需要自行设置权重文件名。
则需要使用`params_filename`设置权重文件名。

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/quant_low_level_api/post_training_quantization.md
> +* batch_size：一次读取样本数据的数量，可以随意设置。
去掉“可以随意设置”。

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/quant_low_level_api/post_training_quantization.md
> +* scope：模型scope，默认为None，则会使用global_scope()。
模型运行时使用的scope，...

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/quant_low_level_api/post_training_quantization.md
> +* algo：计算待量化激活Tensor的量化比例因子的方法。设置为KL，则使用KL散度方法，设置为direct，则使用abs max方法。
algo默认是什么，说清楚。

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/quant_low_level_api/post_training_quantization.md
> +调用上述接口开始离线量化。根据样本数量、模型的大小和量化op类型不同，离线量化需要的时间也不一样。比如使用100图片对`MobileNetV1`进行离线量化，花费大概1分钟。
比如使用ImageNet数据集100张图片...

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/quant_low_level_api/post_training_quantization.md
> +> 该示例的代码放在[models/PaddleSlim/quant_low_level_api/](https://github.com/PaddlePaddle/models/tree/develop/PaddleSlim/quant_low_level_api)目录下。如果需要执行该示例，首先clone下来[models](https://github.com/PaddlePaddle/m
最后量化模型保存在`mobilenetv1_int8_model`目录下。

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/quant_low_level_api/post_training_quantization.md
> +准备样本数据，文件结构如下。val文件夹中有100张图片，val_list.txt文件中包含图片的label。如果特定输入不会影响模型的前向计算，则该输入的数据可以随意设置。
“如果特定输入不会影响模型的前向计算，则该输入的数据可以随意设置。“这句话什么意思，你想表达什么？

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/quant_low_level_api/post_training_quantization.md
> +使用100张样本图像，对'conv2d', 'depthwise_conv2d', 'mul', 'pool2d', 'elementwise_add'和'concat'进行量化，然后在ImageNet2012验证集上测试预测。下表列出了常见分类模型离线量化前后的精度。
使用ImageNet 100张图片做完校准数据集，...

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/quant_low_level_api/post_training_quantization.py
> +sample_generator = reader.val(data_dir=args.data_path)
提示：reader.val返回的不是随机取出的100张图片，你评估一下影响。
你这测试就是验证集合的前面一百张图片，感觉不好。
![image](https://user-images.githubusercontent.com/17102274/69816061-983caf00-1232-11ea-9849-e33bca035431.png)

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/quant_low_level_api/quantization_aware_training.md
> +<div align="center">
Low-Level API 去掉
QAT量化 --> 量化训练
离线量化 --> 训练后量化

2019-11-28 15:06 UTC, wzzju commented on PaddleSlim/quant_low_level_api/quantization_aware_training.md
> +### 2.2 测试QAT量化模型精度
`### 2.2 测试量化训练模型精度。`

为什么你这里给的量化训练精度还没有离线量化的好？
训练了多少轮注明清楚

2019-11-29 07:37 UTC, juncaipeng commented on PaddleSlim/docs/tutorial.md
Done

2019-11-29 07:37 UTC, juncaipeng commented on PaddleSlim/quant_low_level_api/README.md
>      </a>
Done

2019-11-29 07:37 UTC, juncaipeng commented on PaddleSlim/quant_low_level_api/README.md
> +* [量化训练Low-Level API使用方法和示例](./quantization_aware_training.md)
Done

2019-11-29 07:37 UTC, juncaipeng commented on PaddleSlim/quant_low_level_api/post_training_quantization.py
> +sample_generator = reader.val(data_dir=args.data_path)
数据集就是随机的

2019-11-29 07:37 UTC, juncaipeng commented on PaddleSlim/quant_low_level_api/quantization_aware_training.md
> +<div align="center">
Done

2019-11-29 07:37 UTC, juncaipeng commented on PaddleSlim/quant_low_level_api/quantization_aware_training.md
> +### 2.2 测试QAT量化模型精度
Done，可能是加入pool2d的影响，周末再测一次。

2019-11-29 13:49 UTC, wzzju approved these changes
LGTM.

2019-11-29 13:50 UTC, merged