modify classification inference func and readme
PaddlePaddle/models pull request #4116
Opened 2019-12-23 17:30 UTC by littletomatodonkey

1. modify inference py
2. update readme, add more params for scripts.

2019-12-24 04:35 UTC, shippingwang requested changes

2019-12-24 04:35 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +参数微调(Finetune)是指在特定任务上微调已训练模型的参数。可以下载[已发布模型及其性能](#已发布模型及其性能)并且设置```pretrained_model```为模型所在路径，微调一个模型可以采用如下的命令：
不需要改，这里指的是下面那个 path_to_pretrain_model

2019-12-24 04:35 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +export CUDA_VISIBLE_DEVICES=0,1,2,3
这里用把所有参数都列出来么？默认的我们就hide掉？

2019-12-24 04:35 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +        --model=ResNet50_vd \
不要改这里的默认model，还是写ResNet50

2019-12-24 04:35 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +- 如果需要训练自己的数据集，则需要修改根据自己的数据集修改`data_dir`, `total_images`, `class_dim`参数；如果因为GPU显存不够而需要调整`batch_size`，则参数`lr`也需要根据`batch_size`进行线性调整。
这部分可以写在下面的 自定义数据集 里， 另外“如果因为GPU显存不够而需要调整`batch_size`，则参数`lr`也需要根据`batch_size`进行线性调整” 这句话是不是应该详细说一下怎么改。

2019-12-24 04:35 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +- 如果不希望在训练中评测模型，则可以设置参数`validate=0`。
这句话，如果不希望在训练中评测模型，则可以设置参数`validate=0`，在参数解释中加吧

2019-12-24 04:35 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +        --pretrained_model=./ResNet50_vd_pretrained/ \
还有，pretrained_model不要指定具体的值，用户clone下来./没有pretrained model

2019-12-24 04:35 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +- 在自己的数据集上进行微调时，则需要修改根据自己的数据集修改`data_dir`, `total_images`, `class_dim`参数；如果因为GPU显存不够而需要调整`batch_size`，则参数`lr`也需要根据`batch_size`进行线性调整。
同上

2019-12-24 04:35 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +* `model`: 模型名称，与训练时需保持一致。
与 预训练 模型一致吧？或者说预训练模型要和它一致？

2019-12-24 04:35 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +python predict.py \
image_path给成这样$,model用resnet50吧

2019-12-24 04:35 UTC, shippingwang commented on PaddleCV/image_classification/eval.py
> +    if args.save_json_path:
写了两遍？

2019-12-24 04:35 UTC, shippingwang commented on PaddleCV/image_classification/infer.py
> +    os.remove(".tmp.txt")
这块只是 改成with了么？

2019-12-24 04:35 UTC, shippingwang commented on PaddleCV/image_classification/reader.py
> +    if img is None:
需要报warning么？

2019-12-24 04:35 UTC, shippingwang commented on PaddleCV/image_classification/reader.py
> +                                     rotate)
这块为什么改了？

2019-12-24 04:35 UTC, shippingwang commented on PaddleCV/image_classification/reader.py
> +                    if imghdr.what(file_path) not in imgType_list:
需要这个module来做么？

2019-12-24 09:58 UTC, littletomatodonkey commented on PaddleCV/image_classification/README.md
> +export CUDA_VISIBLE_DEVICES=0,1,2,3
> 这里用把所有参数都列出来么？默认的我们就hide掉？

2019-12-24 09:58 UTC, littletomatodonkey commented on PaddleCV/image_classification/README.md
> +export CUDA_VISIBLE_DEVICES=0,1,2,3
建议是将一些参数暴露出来，用户可以更方便地修改~我在底下加了更换数据集需要修改的参数~

2019-12-24 09:58 UTC, littletomatodonkey commented on PaddleCV/image_classification/README.md
> +        --model=ResNet50_vd \
已沟通~

2019-12-24 09:59 UTC, littletomatodonkey commented on PaddleCV/image_classification/README.md
> +- 如果需要训练自己的数据集，则需要修改根据自己的数据集修改`data_dir`, `total_images`, `class_dim`参数；如果因为GPU显存不够而需要调整`batch_size`，则参数`lr`也需要根据`batch_size`进行线性调整。
已补充~

2019-12-24 09:59 UTC, littletomatodonkey commented on PaddleCV/image_classification/README.md
> +参数微调(Finetune)是指在特定任务上微调已训练模型的参数。可以下载[已发布模型及其性能](#已发布模型及其性能)并且设置```pretrained_model```为模型所在路径，微调一个模型可以采用如下的命令：
fixed

2019-12-24 09:59 UTC, littletomatodonkey commented on PaddleCV/image_classification/README.md
> +        --pretrained_model=./ResNet50_vd_pretrained/ \
好的，已修改~

2019-12-24 09:59 UTC, littletomatodonkey commented on PaddleCV/image_classification/README.md
> +- 在自己的数据集上进行微调时，则需要修改根据自己的数据集修改`data_dir`, `total_images`, `class_dim`参数；如果因为GPU显存不够而需要调整`batch_size`，则参数`lr`也需要根据`batch_size`进行线性调整。
已修改~

2019-12-24 10:00 UTC, littletomatodonkey commented on PaddleCV/image_classification/README.md
> +python predict.py \
已修改~model已沟通~

2019-12-24 10:00 UTC, littletomatodonkey commented on PaddleCV/image_classification/README.md
> +* `model`: 模型名称，与训练时需保持一致。
已修改~

2019-12-24 10:00 UTC, littletomatodonkey commented on PaddleCV/image_classification/eval.py
> +    if args.save_json_path:
已删除~

2019-12-24 10:00 UTC, littletomatodonkey commented on PaddleCV/image_classification/infer.py
> +    os.remove(".tmp.txt")
是的，之前只会保存最后一次的结果，这里可以保存所有图片的结果~

2019-12-24 10:01 UTC, littletomatodonkey commented on PaddleCV/image_classification/reader.py
> +                                     rotate)
img为None的时候不做处理~

2019-12-24 10:01 UTC, littletomatodonkey commented on PaddleCV/image_classification/reader.py
> +                    if imghdr.what(file_path) not in imgType_list:
用于获取文件后缀~找到文件夹中的图片列表~

2019-12-24 10:07 UTC, littletomatodonkey commented on PaddleCV/image_classification/README.md
> +- 如果不希望在训练中评测模型，则可以设置参数`validate=0`。
fixed~

2019-12-24 10:11 UTC, littletomatodonkey commented on PaddleCV/image_classification/reader.py
> +    if img is None:
已添加~

2019-12-24 12:44 UTC, shippingwang requested changes

2019-12-24 12:44 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +        --validate=1 \
--validate=True

2019-12-24 12:44 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +- 如果需要训练自己的数据集，则需要修改根据自己的数据集修改`data_dir`, `total_images`, `class_dim`参数；如果因为GPU显存不够而需要调整`batch_size`，则参数`lr`也需要根据`batch_size`进行线性调整。
remind: add a finetune doc(WIP)

2019-12-24 12:44 UTC, shippingwang commented on PaddleCV/image_classification/reader.py
> +            if settings.image_path:
with 是不是应该放在if里面

2019-12-24 12:44 UTC, shippingwang commented on PaddleCV/image_classification/utils/utility.py
> +    logger = logging.getLogger(__name__)
这个函数里应该不用声明了，最上面已经写过了

2019-12-24 13:04 UTC, littletomatodonkey commented on PaddleCV/image_classification/README.md
> +        --validate=1 \
这个已经修改了呀

2019-12-24 13:06 UTC, littletomatodonkey commented on PaddleCV/image_classification/reader.py
> +            if settings.image_path:
image path或者imgset的时候，都需要写这个文件，因此把它放在了外面~

2019-12-24 13:09 UTC, littletomatodonkey commented on PaddleCV/image_classification/utils/utility.py
> +    logger = logging.getLogger(__name__)
fixed~

2019-12-25 02:27 UTC, shippingwang approved these changes
LGTM

2019-12-25 05:09 UTC, merged