add acnet based on resnet
PaddlePaddle/models pull request #4224
Opened 2020-01-20 17:20 UTC by littletomatodonkey

add acnet based on resnet

2020-01-21 07:04 UTC, parap1uie-s reviewed
LGTM

2020-01-21 07:04 UTC, parap1uie-s commented on PaddleCV/image_classification/models/__init__.py
> +from .resnet_acnet import ResNet18ACNet, ResNet34ACNet, ResNet50ACNet, ResNet101ACNet, ResNet152ACNet
模型名称似乎不符合官方模型库的风格

2020-01-21 07:04 UTC, parap1uie-s commented on PaddleCV/image_classification/models/resnet_acnet.py
> +    "ResNetACNet", "ResNet18ACNet", "ResNet34ACNet", "ResNet50ACNet",
同init.py，模型命名风格是否符合规范？

2020-01-21 14:00 UTC, shippingwang requested changes
1. add training scripts
2. please explain how to use the weight_aggregrator.py ?
3. reference?

2020-01-21 14:00 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +### ResNet_ACMet Series
AC 'N' et

2020-01-21 14:00 UTC, shippingwang commented on PaddleCV/image_classification/README.md
> +|Model | deploy mode | Top-1 | Top-5 | Paddle Fluid inference time(ms) | Paddle TensorRT inference time(ms) |
不用写deploy mode 复杂了和别的也不统一，就在model下 加注释就行
比如 ResNet50_ACNet 1 和ResNet50_ACNet 2
之后写成链接的形式

2020-01-21 14:00 UTC, shippingwang commented on PaddleCV/image_classification/README_en.md
> +### ResNet_ACMet Series
same as mentioned above

2020-01-21 14:00 UTC, shippingwang commented on PaddleCV/image_classification/models/__init__.py
> +from .resnet_acnet import ResNet18ACNet, ResNet34ACNet, ResNet50ACNet, ResNet101ACNet, ResNet152ACNet
改成 ACNet_ResNet18 这种 来代表不同backbone？

2020-01-21 14:00 UTC, shippingwang commented on PaddleCV/image_classification/models/resnet_acnet.py
> +train_parameters = {
Remove this then test

2020-01-21 14:00 UTC, shippingwang commented on PaddleCV/image_classification/models/resnet_acnet.py
> +                bias_attr=False,
Not a good params name, should use '_' as delimiter instead of '.'
btw, we should create a naming rule in the future

2020-01-21 14:00 UTC, shippingwang commented on PaddleCV/image_classification/models/resnet_acnet.py
> +        assert isinstance(
Is this unnecessary?

2020-01-21 14:00 UTC, shippingwang commented on PaddleCV/image_classification/utils/acnet/eval_deploy.py
> +#copyright (c) 2019 PaddlePaddle Authors. All Rights Reserve.
It should  integrate into the eval.py

2020-01-21 14:00 UTC, shippingwang commented on PaddleCV/image_classification/utils/acnet/weights_aggregator.py
> +# -*- coding: UTF-8 -*-
remove the first line and the license should be authored by paddlepaddle

2020-01-21 14:00 UTC, shippingwang commented on PaddleCV/image_classification/utils/acnet/weights_aggregator.py
> +    class_num = 1000
Is this hard code?

2020-01-21 14:00 UTC, shippingwang commented on PaddleCV/image_classification/utils/acnet/weights_aggregator.py
> +            _ = model_train.net(image, class_dim=1000)
return a '_' ?  so why do you call it?

2020-01-21 16:02 UTC, littletomatodonkey commented on PaddleCV/image_classification/models/resnet_acnet.py
> +                bias_attr=False,
Here, I just refer to the resnet.py

2020-01-21 16:04 UTC, littletomatodonkey commented on PaddleCV/image_classification/models/resnet_acnet.py
> +        assert isinstance(
removed

2020-01-21 16:04 UTC, littletomatodonkey commented on PaddleCV/image_classification/utils/acnet/eval_deploy.py
> +#copyright (c) 2019 PaddlePaddle Authors. All Rights Reserve.
ok, fixed~

2020-01-21 16:04 UTC, littletomatodonkey commented on PaddleCV/image_classification/utils/acnet/weights_aggregator.py
> +# -*- coding: UTF-8 -*-
done

2020-01-21 16:04 UTC, littletomatodonkey commented on PaddleCV/image_classification/utils/acnet/weights_aggregator.py
> +    class_num = 1000
removed

2020-01-21 16:05 UTC, littletomatodonkey commented on PaddleCV/image_classification/README_en.md
> +### ResNet_ACMet Series
fixed~

2020-01-21 16:05 UTC, littletomatodonkey commented on PaddleCV/image_classification/README.md
> +### ResNet_ACMet Series
fixed~

2020-01-21 16:05 UTC, littletomatodonkey commented on PaddleCV/image_classification/models/resnet_acnet.py
> +    "ResNetACNet", "ResNet18ACNet", "ResNet34ACNet", "ResNet50ACNet",
已修改~

2020-01-21 16:05 UTC, littletomatodonkey commented on PaddleCV/image_classification/models/__init__.py
> +from .resnet_acnet import ResNet18ACNet, ResNet34ACNet, ResNet50ACNet, ResNet101ACNet, ResNet152ACNet
已修改

2020-01-21 16:05 UTC, littletomatodonkey commented on PaddleCV/image_classification/models/resnet_acnet.py
> +train_parameters = {
fixed

2020-01-21 16:06 UTC, littletomatodonkey commented on PaddleCV/image_classification/README.md
> +|Model | deploy mode | Top-1 | Top-5 | Paddle Fluid inference time(ms) | Paddle TensorRT inference time(ms) |
好的，已修改

2020-01-21 16:07 UTC, littletomatodonkey commented on PaddleCV/image_classification/utils/acnet/weights_aggregator.py
> +            _ = model_train.net(image, class_dim=1000)
just to build model and get weights in the programs, I remove the `_` flag. thx~

2020-01-22 03:44 UTC, shippingwang approved these changes
Good job！

2020-01-22 03:44 UTC, merged