add electra pretrain and modify style of electra modeling
PaddlePaddle/models pull request #4990
Opened 2020-12-07 12:45 UTC by jeff41404

1. add electra pretain
2. modify style of electra modeling

2020-12-07 12:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/models?pullRequest=4990) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/models?pullRequest=4990) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/models?pullRequest=4990) it.</sub>

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/predict_classifer.py
> +from paddlenlp.data.batchify import *
batchify.py已经改为了collate.py，这里可以直接使用`from paddlenlp.data import *`

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/predict_classifer.py
> -    test_dataset = dataset_class.get_datasets(["test"])
修改可能覆盖了一些更新后的代码，这里的`test_dataset = dataset_class.get_datasets(["test"])`以及上面的`from paddlenlp.data import *`可能都是覆盖了之前的修改。

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/predict_classifer.py
> +        test_dataset_mismatched = dataset_class("test_mismatched")
dataset可以类似上面`test_dataset = dataset_class.get_datasets(["test"])`的方式获取
`test_dataset_matched = dataset_class.get_datasets("test_matched")`

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/predict_classifer.py
> +        test_dataset_mismatched = SimpleDataset(test_dataset_mismatched).apply(
`SimpleDataset`已经更新成为`MapDatasetWrapper`，另外使用`get_datasets`获取的dataset已经转换成了`MapDatasetWrapper`类型，可以无需再用`MapDatasetWrapper`封装。

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/predict_classifer.py
> +        test_dataset = SimpleDataset(test_dataset).apply(trans_func, lazy=True)
这里dataset的处理和上面类似即可

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/run_glue.py
> +from paddlenlp.data.batchify import Stack, Tuple, Pad
同`predict_classifier.py`中，这里使用此前的代码即可。
```python
from paddlenlp.datasets import GlueCoLA, GlueSST2, GlueMRPC, GlueSTSB, GlueQQP, GlueMNLI, GlueQNLI, GlueRTE
from paddlenlp.data import Stack, Tuple, Pad
```

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/run_glue.py
> +class Accu_and_F1(Metric):
建议class name最好使用驼峰命名。

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/run_glue.py
> +        }
`accumulate`可否先直接返回list或tuple，dict的话暂时会和高级API中不适配。

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/run_glue.py
> +        return {"mcc": mcc, }
同上，可否直接返回mcc

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/run_glue.py
> +    def update(self, preds_and_labels):
请按照metric文档中的示例规范，predict结果和label的参数拆开实现

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/run_glue.py
> +        preds = paddle.argsort(preds_and_labels[0], descending=True)[:, :1]
按照metric的设计规范，`update`中使用numpy计算，可以将需要使用paddle tensor和layer计算的内容放入`compute`中，高级API传给`update`的也会是numpy array。可以都参照类似Accuracy的方式实现。

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/run_glue.py
> +class Pearson_and_Spearman(Metric):
同上，注意使用驼峰命名；另外可否换一个名字，如果无法准确表意也可以拆开为多个metric来实现。

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/run_glue.py
> +        preds = paddle.reshape(preds_and_labels[0], (-1, 1))
同上。按照metric的设计规范，`update`中使用numpy计算，可以将需要使用paddle tensor和layer计算的内容放入`compute`中，高级API传给`update`的也会是numpy array。可以都参照类似Accuracy的方式实现。

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/run_glue.py
> +    def update(self, preds_and_labels):
同上。请按照metric文档中的示例规范，predict结果和label的参数拆开实现

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/run_glue.py
> +    "sts-b": (GlueSTSB, Pearson_and_Spearman),
新增的metric中可以看下是否可以作为API提出。

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/run_glue.py
> +    train_dataset = dataset_class("train")
可以使用`train_dataset = dataset_class.get_datasets("train")`

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/run_glue.py
> +    train_dataset = SimpleDataset(train_dataset).apply(trans_func, lazy=True)
同上。`SimpleDataset`已经更新成为`MapDatasetWrapper`，另外使用`get_datasets`获取的dataset已经转换成了`MapDatasetWrapper`类型，可以无需再用`MapDatasetWrapper`封装。

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/run_glue.py
> +        dev_dataset_mismatched = SimpleDataset(dev_dataset_mismatched).apply(
同上。`SimpleDataset`已经更新成为`MapDatasetWrapper`，另外使用`get_datasets`获取的dataset已经转换成了`MapDatasetWrapper`类型，可以无需再用`MapDatasetWrapper`封装。

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/paddlenlp/transformers/electra/tokenizer.py
> +        "chinese-electra-small": {
是否vocab_file中少了部分中文模型对应的配置。

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/examples/electra/run_pretrain.py
> +        total_indices = paddle.bernoulli(probability_matrix).astype("bool")
当前Paddle的dataloader中其实不太支持使用Paddle Tensor和layer（dataloader的num_worker>0时），这里可能要注意下，可以试下验证下。如果确实如此，还请加个注释说明`num_worker`必须为0吧。

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/paddlenlp/transformers/electra/modeling.py
> +        self.layer_norm = nn.LayerNorm(embedding_size, epsilon=1e-12)
这里可以看情况，init参数是可以不要求一致的。

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/paddlenlp/transformers/electra/modeling.py
> +        #        axis=[1, 2])
这里`attention_mask  is None`的表现建议和BERT中一致。按照BERT中那种run_glue.py中才可以不输入attention_mask，可以确认下`run_glue.py`中的代码。

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/paddlenlp/transformers/electra/modeling.py
> +        gen_loss_fct = nn.CrossEntropyLoss(
layer的创建最好放在`__init__`中。

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/paddlenlp/transformers/electra/modeling.py
> +                                      mask_positions)
可以加个TODO，说明以后CrossEntropyLoss中reduction行为修改后删掉这些代码。

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/paddlenlp/transformers/electra/modeling.py
>                  self.generator_lm_head_bias)
不建议这里每次forward都要对weight进行transpose，可以使用matmul后加bias。

2020-12-08 09:29 UTC, guoshengCS commented on PaddleNLP/paddlenlp/transformers/electra/modeling.py
>          if use_softmax_sample:
注意这里的`ins_softmax = nn.Softmax(axis=-1)`，layer的创建最好放在__init__中，也可以使用functional的api。

2020-12-09 02:50 UTC, jeff41404 commented on PaddleNLP/examples/electra/predict_classifer.py
> +from paddlenlp.data.batchify import *
已修改

2020-12-09 03:03 UTC, jeff41404 commented on PaddleNLP/examples/electra/predict_classifer.py
> -    test_dataset = dataset_class.get_datasets(["test"])
发现是最近才更新的新用法，已修改

2020-12-09 03:03 UTC, jeff41404 commented on PaddleNLP/examples/electra/predict_classifer.py
> +        test_dataset_mismatched = dataset_class("test_mismatched")
发现是最近才更新的新用法，已修改

2020-12-09 03:10 UTC, jeff41404 commented on PaddleNLP/examples/electra/predict_classifer.py
> +        test_dataset_mismatched = SimpleDataset(test_dataset_mismatched).apply(
发现是最近才更新的新用法，已修改

2020-12-09 03:10 UTC, jeff41404 commented on PaddleNLP/examples/electra/predict_classifer.py
> +        test_dataset = SimpleDataset(test_dataset).apply(trans_func, lazy=True)
发现是最近才更新的新用法，已修改

2020-12-09 03:12 UTC, jeff41404 commented on PaddleNLP/paddlenlp/transformers/electra/modeling.py
> +        #        axis=[1, 2])
Huggingface(Pytorch)中是这样实现，为了比较效果，所以才这样写，没有和我们Bert中一致

2020-12-09 03:21 UTC, jeff41404 commented on PaddleNLP/paddlenlp/transformers/electra/modeling.py
> +        gen_loss_fct = nn.CrossEntropyLoss(
已放在__init__中

2020-12-09 03:22 UTC, jeff41404 commented on PaddleNLP/paddlenlp/transformers/electra/modeling.py
> +                                      mask_positions)
已加TODO

2020-12-09 04:11 UTC, jeff41404 commented on PaddleNLP/paddlenlp/transformers/electra/modeling.py
>          if use_softmax_sample:
已换成functional的softmax

2020-12-09 05:16 UTC, jeff41404 commented on PaddleNLP/paddlenlp/transformers/electra/modeling.py
>                  self.generator_lm_head_bias)
已修改为 matmul+add的方式，线下构造数据实测，这两种性能差不多
F.linear done, total : 1.938603401184082 s
matmul/add done, total : 2.024595022201538 s

2020-12-09 06:13 UTC, guoshengCS commented on PaddleNLP/examples/electra/run_pretrain.py
> +            input_ids, raw_input_ids, gen_labels = batch
输入是否需要`input_mask`呢，或者将模型中的`input_mask`换为和BERT中一致的话应该也可以不输入。

2020-12-09 07:21 UTC, jeff41404 commented on PaddleNLP/paddlenlp/transformers/electra/modeling.py
> +        #        axis=[1, 2])
当前已经改成和Bert一致

2020-12-09 08:33 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_glue.py
> +from paddlenlp.data.batchify import Stack, Tuple, Pad
发现是最近才更新的新用法，已修改

2020-12-09 08:39 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_glue.py
> +class Accu_and_F1(Metric):
已修改名称

2020-12-09 09:01 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_glue.py
> +        }
已统一修改返回tuple

2020-12-09 09:01 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_glue.py
> +        return {"mcc": mcc, }
已统一修改返回tuple

2020-12-09 09:02 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_glue.py
> +class Pearson_and_Spearman(Metric):
已修改名称

2020-12-09 09:02 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_glue.py
> +    train_dataset = dataset_class("train")
发现是最近才更新的新用法，已修改

2020-12-09 09:02 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_glue.py
> +    train_dataset = SimpleDataset(train_dataset).apply(trans_func, lazy=True)
发现是最近才更新的新用法，已修改

2020-12-09 09:04 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_glue.py
> +        dev_dataset_mismatched = SimpleDataset(dev_dataset_mismatched).apply(
发现是最近才更新的新用法，已修改

2020-12-09 09:07 UTC, jeff41404 commented on PaddleNLP/paddlenlp/transformers/electra/tokenizer.py
> +        "chinese-electra-small": {
已补上

2020-12-09 09:10 UTC, jeff41404 commented on PaddleNLP/paddlenlp/transformers/electra/modeling.py
> +        self.layer_norm = nn.LayerNorm(embedding_size, epsilon=1e-12)
看了下layer_norm_eps这个参数也很少改动，google  electra-small/base/large的配置也都是1e-12，就先这样写了，有需求再改成配置

2020-12-09 09:16 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_pretrain.py
> +            input_ids, raw_input_ids, gen_labels = batch
input_mask 和 raw_input_ids 需要1个就可以，两者可以等价转换，这里也权衡过用谁，因为在 generator和discriminator中间需要额外的数据处理，而这个处理使用raw_input_ids 更高效，所以使用raw_input_ids 替代input_mask

2020-12-09 09:21 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_glue.py
> +    "sts-b": (GlueSTSB, Pearson_and_Spearman),
上周泽阳说他那边已经提了，如果进了metric api，可能统一迁移过去

2020-12-09 10:52 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_glue.py
> +        preds = paddle.reshape(preds_and_labels[0], (-1, 1))
已经修改，update中不再包括tensor相关的reshape等操作

2020-12-09 10:55 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_glue.py
> +    def update(self, preds_and_labels):
之所以合并在一起，是考虑了用统一的metric框架和统一的使用方法（compute/update/accumulate），如果拆成2个参数，update的调用会不统一，即需根据不同的metric判断调用不同的update，和郭晟同学讨论，权衡再三，先保留此使用方法

2020-12-09 10:56 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_glue.py
> +    def update(self, preds_and_labels):
之所以合并在一起，是考虑了用统一的metric框架和统一的使用方法（compute/update/accumulate），如果拆成2个参数，update的调用会不统一，即需根据不同的metric判断调用不同的update，和郭晟同学讨论，权衡再三，先保留此使用方法

2020-12-09 10:56 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_glue.py
> +        preds = paddle.argsort(preds_and_labels[0], descending=True)[:, :1]
已经修改，update中不再包括tensor相关的reshape等操作

2020-12-09 10:57 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_pretrain.py
> +        total_indices = paddle.bernoulli(probability_matrix).astype("bool")
可以，先加了num_worker的说明

2020-12-09 15:27 UTC, ZeyuChen requested changes
Accu命名修正
另外是否可以考虑直接把评估进paddlenlp.metrics

2020-12-09 15:27 UTC, ZeyuChen commented on PaddleNLP/examples/electra/run_glue.py
> +class Mcc(Metric):
这个指标可以考虑进metrics

2020-12-09 15:27 UTC, ZeyuChen commented on PaddleNLP/examples/electra/run_glue.py
> +class Pearson_and_Spearman(Metric):
对python类名推荐用大坨峰

2020-12-09 15:27 UTC, ZeyuChen commented on PaddleNLP/examples/electra/run_glue.py
> +class Pearson_and_Spearman(Metric):
驼峰

2020-12-09 15:27 UTC, ZeyuChen commented on PaddleNLP/examples/electra/run_glue.py
> +class Pearson_and_Spearman(Metric):
这个指标是否也可以考虑进框架？

2020-12-09 15:27 UTC, ZeyuChen commented on PaddleNLP/examples/electra/run_glue.py
> +class AccuAndF1(Metric):
建议完整命名 AccuracyAndF1，或者AccAndF1
一般来说机器学习领域用ACC作为Accuracy的缩写，而不常用Accu

2020-12-09 15:27 UTC, ZeyuChen commented on PaddleNLP/examples/electra/run_glue.py
> +class AccuAndF1(Metric):
建议下方accu的变量名同步为acc

2020-12-10 03:07 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_glue.py
> +class Pearson_and_Spearman(Metric):
这点已在之前郭晟同学的review中修改

2020-12-10 03:09 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_glue.py
> +class Mcc(Metric):
当前是解燃眉之急，观察一段时间稳定再加一些异常分支后提进metrics

2020-12-10 03:22 UTC, jeff41404 commented on PaddleNLP/examples/electra/run_glue.py
> +class AccuAndF1(Metric):
已都改成 acc和AccuracyAndF1，当时写accu可能受Bert evaluate中accu影响

2020-12-10 08:55 UTC, ZeyuChen approved these changes
LGTM

2020-12-10 08:58 UTC, merged