Add dureader robust prototype
PaddlePaddle/models pull request #4992
Opened 2020-12-08 03:45 UTC by smallv0221

Add dureader robust prototype

2020-12-08 05:07 UTC, ZeyuChen requested changes
一些命名风格需要改进

2020-12-08 05:07 UTC, ZeyuChen commented on PaddleNLP/examples/machine_reading_comprehension/Dureader2020/args.py
> +import argparse
DuReader 2020这个文件名好像不太合理，要不跟千言数据集的规定一致
DuReader-robust
DuReader-yesno

2020-12-08 05:07 UTC, ZeyuChen commented on PaddleNLP/examples/machine_reading_comprehension/Dureader2020/dataset.py
> +class RobustExample(object):
可否改为DuReaderExample？
感觉RobustExample从英文翻译来看就不表意

2020-12-08 05:07 UTC, ZeyuChen commented on PaddleNLP/examples/machine_reading_comprehension/Dureader2020/dataset.py
> +class DuRobust(Dataset):
DuReaderRobust

2020-12-08 05:07 UTC, ZeyuChen commented on PaddleNLP/examples/machine_reading_comprehension/Dureader2020/run_du.py
> +class RobustFeature(object):
改为InputFeature吧，还是那个问题Robust表意不准确

2020-12-10 11:43 UTC, ZeyuChen requested changes
看一下一些基本的修改意见

2020-12-10 11:43 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/datasets/dureaderyesno.py
> +        Return labels of the GlueCoLA object.
GlueCoLA？

2020-12-10 11:43 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/datasets/dureaderyesno.py
> +import copy
dureader的所有数据集统一放到一个dureader.py里面去。

2020-12-10 11:43 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/datasets/dureaderrobust.py
> +import copy
所有DuReader相关数据集统一放到一个文件dureader.py

2020-12-10 11:43 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/datasets/dureaderrobust.py
> +import copy
然后在`__all__`里面拓展

2020-12-10 11:43 UTC, ZeyuChen commented on PaddleNLP/examples/bert/run_glue.py
>      ### TODO: use hapi
这里先明确下，先去掉hapi吧。相关bert hapi的使用代码后续在aistudio中体现即可。

2020-12-10 11:43 UTC, ZeyuChen commented on PaddleNLP/examples/machine_reading_comprehension/DuReader-robust/run_du.py
> +    dev_batchify_fn = lambda samples, fn=Tuple(
确认下，如果dev_batchify_fn和test_batchify_fn都一样的话是否还需要写两次  @guoshengCS

2020-12-10 11:43 UTC, ZeyuChen commented on PaddleNLP/examples/machine_reading_comprehension/DuReader-robust/run_du.py
> +    train_ds, dev_ds, test_ds = ppnlp.datasets.DuReaderRobust.get_datasets(
这里的代码太不优雅了，后续不要这种*3的写法。

2020-12-10 11:43 UTC, ZeyuChen commented on PaddleNLP/examples/machine_reading_comprehension/DuReader-robust/run_du.py
> +    lr_scheduler = paddle.optimizer.lr.LambdaDecay(
和郭晟确认下这里的写法有没有更好的写法
我觉得我们的lr scheduler的写法实在是太复杂了，完全没体现任何动态图的特性

2020-12-10 11:43 UTC, ZeyuChen commented on PaddleNLP/examples/machine_reading_comprehension/DuReader-robust/run_du.py
> +    lr_scheduler = paddle.optimizer.lr.LambdaDecay(
@guoshengCS

2020-12-11 04:05 UTC, guoshengCS commented on PaddleNLP/examples/machine_reading_comprehension/DuReader-robust/run_du.py
> +    dev_batchify_fn = lambda samples, fn=Tuple(
一样的话应该是可以只写一次

2020-12-11 06:55 UTC, ZeyuChen approved these changes
LGTM

2020-12-11 06:56 UTC, merged

2020-12-11 07:05 UTC, guoshengCS commented on PaddleNLP/paddlenlp/datasets/dureader.py
> +        default_root = os.path.join(DATA_HOME, 'DuReader')
可否看看将`default_root = os.path.join(DATA_HOME, 'DuReader')`中的DuReader用class_name代替，后续将`_get_data`加入到基类中或提出来，然后glue和按照glue方式实现数据集下载数据就可以统一用`_get_data `来下载数据了。

2020-12-12 06:53 UTC, guoshengCS commented on PaddleNLP/paddlenlp/datasets/dureader.py
> +        default_root = os.path.join(DATA_HOME, 'DuReader')
@LiuChiachi  @FrostML  翻译数据注意类似的问题。

2020-12-12 06:55 UTC, smallv0221 commented on PaddleNLP/paddlenlp/datasets/dureader.py
> +        default_root = os.path.join(DATA_HOME, 'DuReader')
好的