Update perplexity, inherited from Metric
PaddlePaddle/models pull request #4995
Opened 2020-12-08 07:21 UTC by LiuChiachi

Suitable for common machine translation task and language model.

2020-12-09 03:24 UTC, smallv0221 requested changes

2020-12-09 03:24 UTC, smallv0221 commented on PaddleNLP/paddlenlp/metrics/perplexity.py
> +        self.word_num = seq_len
这个参数想办法在update中找到。

2020-12-09 03:24 UTC, smallv0221 commented on PaddleNLP/paddlenlp/metrics/perplexity.py
> +        self.total_cost = 0
ppl是基于cross-entropy的，cost都改成ce比较直观

2020-12-09 03:24 UTC, smallv0221 commented on PaddleNLP/paddlenlp/metrics/perplexity.py
> +        word_num = self.word_num
这里的累加在语言模型中结果不对。

2020-12-09 05:21 UTC, LiuChiachi commented on PaddleNLP/paddlenlp/metrics/perplexity.py
> +        word_num = self.word_num
感谢，已经修改并在语言模型下验证了

2020-12-09 05:21 UTC, LiuChiachi commented on PaddleNLP/paddlenlp/metrics/perplexity.py
> +        self.total_cost = 0
Thanks! Done.

2020-12-09 05:22 UTC, LiuChiachi commented on PaddleNLP/paddlenlp/metrics/perplexity.py
> +        self.word_num = seq_len
感谢，已经修改~

2020-12-09 07:36 UTC, smallv0221 commented on PaddleNLP/paddlenlp/metrics/perplexity.py
> +        self.word_count += word_num
感觉word_count和word_num有点混淆，是不是第一个改成self.total_word好一点

2020-12-10 12:38 UTC, LiuChiachi commented on PaddleNLP/paddlenlp/metrics/perplexity.py
> +        self.word_count += word_num
Done. Thanks!

2020-12-10 13:53 UTC, ZeyuChen approved these changes
LGTM

2020-12-10 13:53 UTC, merged