add model api
PaddlePaddle/models pull request #4998
Opened 2020-12-08 11:13 UTC by Steffy-zxf

1.  add models api (paddlenlp.models.Senta, paddlenlp.models.Simnet, paddlenlp.models.Ernie)
2. rename ernie config (ernie -> ernie-1.0, ernie_v2_eng_base -> ernie-2.0-en, ernie_v2_eng_large -> ernie-2.0-large-en) 
3. add text matching datatset (paddlenlp.datasets.LCQMC)

2020-12-08 13:24 UTC, ZeyuChen requested changes
一些类名和文件名需要修改

2020-12-08 13:24 UTC, ZeyuChen commented on PaddleNLP/examples/text_matching/rnn/predict.py
> +        ['光眼睛大就好看吗', '眼睛好看吗？'],
这里给的样例都有正有负吗？怎么感觉看上去都是正的

2020-12-08 13:24 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/datasets/lcqmc.py
> +        Return labels of the ChnSentiCorp object.
ChnSentiCorp -> LCQMC

2020-12-08 13:24 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/models/simnet.py
> +class Simnet(nn.Layer):
SimNet

2020-12-08 13:24 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/models/simnet.py
> +            self.model = LSTMModel(vocab_size, num_classes, emb_dim, direction='forward', padding_idx=pad_token_id)
SimNet只有三种基础结构
BoW，GRU，CNN
非这三种结构的不要加进来

2020-12-08 13:24 UTC, ZeyuChen commented on PaddleNLP/examples/text_matching/rnn/predict.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
text_matching/rnn的目录就起名为simnet吧

2020-12-08 13:24 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/models/ernie.py
> +        elif self.task == 'token-classification':
看是否可以改成用枚举类型，枚举类名定义为Task，就在Ernie中定义
Task.SeqCLS, Task.TokenCLS, Task.QA
用这种方式来处理，可能会更简洁一点

2020-12-08 13:24 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/models/simnet.py
> +        if network_name == 'bow':
同样看是否在SimNet的类中注册一个枚举类型
使用SimNet.BoW, SimNet.CNN, SimNet.GRU这三个枚举变量来顶替这里的network_name

2020-12-09 02:37 UTC, Steffy-zxf commented on PaddleNLP/paddlenlp/models/simnet.py
> +            self.model = LSTMModel(vocab_size, num_classes, emb_dim, direction='forward', padding_idx=pad_token_id)
models/PaddleNLP/similarity_net 有 Bow，GRU，LSTM，CNN 网络

https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/similarity_net/config
https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/shared_modules/models/matching

2020-12-09 02:52 UTC, Steffy-zxf commented on PaddleNLP/examples/text_matching/rnn/predict.py
> +        ['光眼睛大就好看吗', '眼睛好看吗？'],
有相似， 有不相似。

```
Data: ['世界上什么东西最小', '世界上什么东西最小？'] 	 Label: similar
Data: ['光眼睛大就好看吗', '眼睛好看吗？'] 	 Label: dissimilar
Data: ['小蝌蚪找妈妈怎么样', '小蝌蚪找妈妈是谁画的'] 	 Label: dissimilar
```

2020-12-09 10:03 UTC, Steffy-zxf commented on PaddleNLP/paddlenlp/datasets/lcqmc.py
> +        Return labels of the ChnSentiCorp object.
已修改

2020-12-09 10:03 UTC, Steffy-zxf commented on PaddleNLP/paddlenlp/models/simnet.py
> +class Simnet(nn.Layer):
已修改

2020-12-09 10:03 UTC, Steffy-zxf commented on PaddleNLP/examples/text_matching/rnn/predict.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
已修改

2020-12-09 10:04 UTC, Steffy-zxf commented on PaddleNLP/paddlenlp/models/ernie.py
> +        elif self.task == 'token-classification':
已修改为 task short cut

2020-12-09 10:04 UTC, Steffy-zxf commented on PaddleNLP/paddlenlp/models/simnet.py
> +        if network_name == 'bow':
这里名称较短，感觉还好， 保留

2020-12-09 10:14 UTC, ZeyuChen approved these changes
LGTM

2020-12-09 10:14 UTC, merged