Upgrade plato2 using paddle2.0
PaddlePaddle/models pull request #5002
Opened 2020-12-09 08:09 UTC by xiemoyuan

Upgrade the plato2 inference model.

2020-12-12 12:49 UTC, ZeyuChen requested changes
去掉py2兼容的代码

2020-12-12 12:49 UTC, ZeyuChen commented on PaddleNLP/examples/dialogue/plato2/utils/tokenization.py
> +    elif six.PY2:
去掉这些py2兼容代码

2020-12-12 12:49 UTC, ZeyuChen commented on PaddleNLP/examples/dialogue/plato2/utils/tokenization.py
> +import six
去掉six

2020-12-12 12:49 UTC, ZeyuChen commented on PaddleNLP/examples/dialogue/plato2/utils/tokenization.py
> +import sentencepiece as spm
记得readme里面把setencepiece作为依赖

2020-12-14 13:37 UTC, ZeyuChen requested changes
改一下README，然后也让何煌帮忙review下解码部分的动态图用法是否合理。

2020-12-14 13:37 UTC, ZeyuChen commented on PaddleNLP/examples/dialogue/plato2/README.md
> +   pip install paddlenlp
我们alpha版本和beta版本的安装，都需要注明b版本号才行
pip install paddlenlp>=2.0.0a

2020-12-14 13:37 UTC, ZeyuChen commented on PaddleNLP/examples/dialogue/plato2/README.md
> +   pip install paddlenlp
到时beta版本发布的安装命令是pip install paddlenlp>=2.0.0b

2020-12-14 13:37 UTC, ZeyuChen commented on PaddleNLP/examples/dialogue/plato2/README.md
> +    其它环境依赖请参考 PaddlePaddle [安装说明](https://www.paddlepaddle.org.cn/install/quick/zh/2.0rc-linux-docker) 部分的内容
这句话有意义吗？

2020-12-14 13:37 UTC, ZeyuChen commented on PaddleNLP/examples/dialogue/plato2/README.md
> +# PLATO2
标准写法应该是PLATO-2
https://github.com/PaddlePaddle/Knover/tree/master/plato-2

2020-12-14 13:37 UTC, ZeyuChen commented on PaddleNLP/examples/dialogue/plato2/README.md
> +* Plato2, 24-layers, 16-heads, 1024-hidden, EN: [预训练模型](https://paddlenlp.bj.bcebos.com/models/transformers/plato2/24L.pdparams)
PLATO-2

2020-12-14 13:37 UTC, ZeyuChen commented on PaddleNLP/examples/dialogue/plato2/README.md
> +* init_from_ckpt：Plato2预训练模型路径。
最后补充下对话示意截图吧

2020-12-14 13:37 UTC, ZeyuChen commented on PaddleNLP/examples/dialogue/plato2/README.md
> +**NOTE:** Plato2网络参数量较大，本项目已在22G显存上测试可以支持24层和32层网络，用户可根据显存自行选择合适层数及预训练模型。
PLATO-2
看能不能把24L和32L的显存开销列出来，直接著名显存开销就好

2020-12-15 02:23 UTC, xiemoyuan commented on PaddleNLP/examples/dialogue/plato2/README.md
> +**NOTE:** Plato2网络参数量较大，本项目已在22G显存上测试可以支持24层和32层网络，用户可根据显存自行选择合适层数及预训练模型。
显存波动较大，不太好注明，何煌说他在16G机器上跑24层的网络，能跑，但我在22G机器上跑，最高时也占用到了20G，这块儿不知道咋写

2020-12-15 02:38 UTC, xiemoyuan commented
> 让何煌帮忙review下解码部分的动态图用法是否合理

解码部分的代码在开发的时候何煌已经帮我修改过了

2020-12-15 02:39 UTC, xiemoyuan commented on PaddleNLP/examples/dialogue/plato2/README.md
> +    其它环境依赖请参考 PaddlePaddle [安装说明](https://www.paddlepaddle.org.cn/install/quick/zh/2.0rc-linux-docker) 部分的内容
已删除

2020-12-15 02:39 UTC, xiemoyuan commented on PaddleNLP/examples/dialogue/plato2/README.md
> +   pip install paddlenlp
已修改

2020-12-15 02:39 UTC, xiemoyuan commented on PaddleNLP/examples/dialogue/plato2/README.md
> +# PLATO2
已修改

2020-12-15 02:40 UTC, xiemoyuan commented on PaddleNLP/examples/dialogue/plato2/README.md
> +* Plato2, 24-layers, 16-heads, 1024-hidden, EN: [预训练模型](https://paddlenlp.bj.bcebos.com/models/transformers/plato2/24L.pdparams)
已修改

2020-12-15 07:27 UTC, xiemoyuan commented on PaddleNLP/examples/dialogue/plato2/README.md
> +* init_from_ckpt：Plato2预训练模型路径。
已添加

2020-12-15 07:28 UTC, xiemoyuan commented on PaddleNLP/examples/dialogue/plato2/README.md
> +**NOTE:** Plato2网络参数量较大，本项目已在22G显存上测试可以支持24层和32层网络，用户可根据显存自行选择合适层数及预训练模型。
已修改

2020-12-15 09:43 UTC, guoshengCS approved these changes

2020-12-15 09:43 UTC, guoshengCS commented on PaddleNLP/examples/dialogue/plato-2/model.py
> +        pred_ids = self.decoder(inputs, new_caches)
后面`def decoder`这个method可以看看改成个decode，decoder作为方法明可能不太合适

2020-12-15 09:43 UTC, guoshengCS commented on PaddleNLP/examples/dialogue/plato-2/model.py
> +                example = Example(
后面可以看看能否把model部分处理的干净些，感觉略微有些混杂了

2020-12-15 09:47 UTC, merged

2020-12-15 10:34 UTC, xiemoyuan commented on PaddleNLP/examples/dialogue/plato-2/model.py
> +        pred_ids = self.decoder(inputs, new_caches)
好的

2020-12-15 10:34 UTC, xiemoyuan commented on PaddleNLP/examples/dialogue/plato-2/model.py
> +                example = Example(
好的，后续把模型分为两步进行处理