update docs
PaddlePaddle/models pull request #5004
Opened 2020-12-09 13:56 UTC by Steffy-zxf

update text cls & text matching docs

2020-12-09 14:06 UTC, ZeyuChen requested changes
细节文字意见修改

2020-12-09 14:06 UTC, ZeyuChen commented on PaddleNLP/examples/text_matching/simnet/README.md
> +# 使用传统SimNet完成pointwise文本匹配任务
不要在SimNet前面+传统这个词

2020-12-09 14:06 UTC, ZeyuChen commented on PaddleNLP/examples/text_matching/simnet/README.md
> +# CUDA_VSIBLE_DEVICES指定想要利用的GPU卡号，可以是单卡，也可以多卡
这句注释不用

2020-12-09 14:06 UTC, ZeyuChen commented on PaddleNLP/examples/text_matching/simnet/README.md
> +# CUDA_VISIBLE_DEVICES=0 python train.py --vocab_path='./simnet_word_dict.txt' --use_gpu=True --network=lstm --lr=5e-4 --batch_size=64 --epochs=5 --save_dir='./checkpoints'
这里不应该“#“加注释

2020-12-09 14:06 UTC, ZeyuChen commented on PaddleNLP/examples/text_matching/simnet/README.md
> +* vocab_path: 词汇表文件路径。
所以args参数我们统一用`vocab_path`阔起来

2020-12-09 14:06 UTC, ZeyuChen commented on PaddleNLP/examples/text_matching/simnet/train.py
> +parser.add_argument('--network', type=str, default="lstm", help="Which network you would like to choose bow, lstm, bilstm, gru, bigru, rnn, birnn, bilstm_attn and textcnn?")
simnet没这么多选项了吧？

2020-12-09 14:06 UTC, ZeyuChen commented on PaddleNLP/examples/text_matching/README.md
> +[SentenceBert](./sentence_bert) 展示了如何使用以ERNIE为代表的模型Fine-tune完成pointwise文本匹配任务。
这类外部模型的，最后要价格todo，把相关论文的reference 和citation加上

2020-12-09 14:06 UTC, ZeyuChen commented on PaddleNLP/examples/text_classification/rnn/README.md
> +# CUDA_VISIBLE_DEVICES=0 python train.py --vocab_path='./senta_word_dict.txt' --use_gpu=True --network_name=bilstm --lr=5e-4 --batch_size=64 --epochs=5 --save_dir='./checkpoints'
为啥GPU启动要加#呢？

2020-12-10 01:56 UTC, Steffy-zxf commented on PaddleNLP/examples/text_classification/rnn/README.md
> +# CUDA_VISIBLE_DEVICES=0 python train.py --vocab_path='./senta_word_dict.txt' --use_gpu=True --network_name=bilstm --lr=5e-4 --batch_size=64 --epochs=5 --save_dir='./checkpoints'
因为前面有cpu启动方式

GPU启动方式只是给个示例作用

2020-12-10 01:56 UTC, Steffy-zxf commented on PaddleNLP/examples/text_matching/simnet/README.md
> +# CUDA_VISIBLE_DEVICES=0 python train.py --vocab_path='./simnet_word_dict.txt' --use_gpu=True --network=lstm --lr=5e-4 --batch_size=64 --epochs=5 --save_dir='./checkpoints'
因为前面有cpu启动方式

GPU启动方式只是给个示例作用

2020-12-10 15:44 UTC, ZeyuChen commented on PaddleNLP/examples/text_matching/simnet/README.md
> +# CUDA_VISIBLE_DEVICES=0 python train.py --vocab_path='./simnet_word_dict.txt' --use_gpu=True --network=lstm --lr=5e-4 --batch_size=64 --epochs=5 --save_dir='./checkpoints'
那是否可以采用分成两个代码block的方式说明呢？为什么GPU这里只是个示意？
CPU启动
```shell
xxxxxx
```
GPU启动
```shell
xxxxxx
```

2020-12-10 15:44 UTC, ZeyuChen commented on PaddleNLP/examples/text_matching/simnet/README.md
> +
建议分拆成两个code block

2020-12-11 10:20 UTC, ZeyuChen requested changes
还有2个小的修改需要修改

2020-12-11 10:20 UTC, ZeyuChen commented on PaddleNLP/examples/text_matching/sentence_transformers/train.py
> +    metric = paddle.metric.Accuracy(name='acc_accumulation')
去掉这里的acc accumulate

2020-12-11 10:20 UTC, ZeyuChen commented on PaddleNLP/examples/text_matching/simnet/README.md
> +# 使用传统SimNet完成pointwise文本匹配任务
去掉传统

2020-12-11 13:23 UTC, Steffy-zxf commented on PaddleNLP/examples/text_matching/simnet/README.md
> +# 使用传统SimNet完成pointwise文本匹配任务
已修改

2020-12-11 13:23 UTC, Steffy-zxf commented on PaddleNLP/examples/text_matching/simnet/README.md
> +# CUDA_VSIBLE_DEVICES指定想要利用的GPU卡号，可以是单卡，也可以多卡
已修改

2020-12-11 13:23 UTC, Steffy-zxf commented on PaddleNLP/examples/text_matching/simnet/README.md
> +# CUDA_VISIBLE_DEVICES=0 python train.py --vocab_path='./simnet_word_dict.txt' --use_gpu=True --network=lstm --lr=5e-4 --batch_size=64 --epochs=5 --save_dir='./checkpoints'
已修改

2020-12-11 13:23 UTC, Steffy-zxf commented on PaddleNLP/examples/text_matching/simnet/README.md
> +* vocab_path: 词汇表文件路径。
已修改

2020-12-11 13:23 UTC, Steffy-zxf commented on PaddleNLP/examples/text_matching/simnet/train.py
> +parser.add_argument('--network', type=str, default="lstm", help="Which network you would like to choose bow, lstm, bilstm, gru, bigru, rnn, birnn, bilstm_attn and textcnn?")
已修改

2020-12-11 13:24 UTC, Steffy-zxf commented on PaddleNLP/examples/text_matching/README.md
> +[SentenceBert](./sentence_bert) 展示了如何使用以ERNIE为代表的模型Fine-tune完成pointwise文本匹配任务。
已添加

2020-12-11 13:24 UTC, Steffy-zxf commented on PaddleNLP/examples/text_classification/rnn/README.md
> +# CUDA_VISIBLE_DEVICES=0 python train.py --vocab_path='./senta_word_dict.txt' --use_gpu=True --network_name=bilstm --lr=5e-4 --batch_size=64 --epochs=5 --save_dir='./checkpoints'
已修改

2020-12-11 13:24 UTC, Steffy-zxf commented on PaddleNLP/examples/text_matching/simnet/README.md
> +
已修改

2020-12-11 13:28 UTC, Steffy-zxf commented on PaddleNLP/examples/text_matching/sentence_transformers/train.py
> +    metric = paddle.metric.Accuracy(name='acc_accumulation')
已修改

2020-12-11 13:30 UTC, ZeyuChen approved these changes
LGTM

2020-12-11 13:30 UTC, merged