Add ofa bert
PaddlePaddle/models pull request #5006
Opened 2020-12-10 03:28 UTC by ceci3

add slimofa for bert

2020-12-15 02:27 UTC, wanghaoshuang approved these changes
LGTM

2020-12-15 09:06 UTC, ZeyuChen requested changes
注释标准统一下
建议使用pip方式安装

2020-12-15 09:06 UTC, ZeyuChen commented on PaddleNLP/examples/slim/README.md
> +| Task  | Metric                       | Result            | Result with PaddleSlim |
补充下ModelParam缩小的百分比，或者预测速度的提升百分比？

2020-12-15 09:06 UTC, ZeyuChen commented on PaddleNLP/examples/slim/README.md
> +git clone https://github.com/PaddlePaddle/PaddleSlim.git
可以pip install吗？

2020-12-15 09:06 UTC, ZeyuChen commented on PaddleNLP/examples/slim/run_glue_ofa.py
> +    # train_batch_sampler = SamplerHelper(train_ds).shuffle().batch(
删除

2020-12-15 09:06 UTC, ZeyuChen commented on PaddleNLP/examples/slim/run_glue_ofa.py
> +    ### step1: init a dict to save origin weights
所有注释统一为1个单井号
同时按英文句子语法撰写
eg. 
Step1: Initialize a dic to save original weights

2020-12-15 09:06 UTC, ZeyuChen commented on PaddleNLP/examples/slim/README.md
> +</p>
是否需要补充相关技术的Reference？

2020-12-15 12:15 UTC, ceci3 commented on PaddleNLP/examples/slim/README.md
> +| Task  | Metric                       | Result            | Result with PaddleSlim |
上面有写加速约200%，这是通过之前的静态图代码导出的模型测试的速度，因为压缩后的模型是一样的，所以加速我理解也是相同的，这里就没再单独写一列。

2020-12-15 12:15 UTC, ceci3 commented on PaddleNLP/examples/slim/README.md
> +git clone https://github.com/PaddlePaddle/PaddleSlim.git
目前pip install这种方式安装的paddleslim还不包含ofa这个功能，等包含ofa功能的paddleslim发布包的时候我再再readme这里更新一下？

2020-12-15 12:16 UTC, ceci3 commented on PaddleNLP/examples/slim/run_glue_ofa.py
> +    # train_batch_sampler = SamplerHelper(train_ds).shuffle().batch(
done, thanks

2020-12-15 12:16 UTC, ceci3 commented on PaddleNLP/examples/slim/run_glue_ofa.py
> +    ### step1: init a dict to save origin weights
done, thanks

2020-12-15 12:16 UTC, ceci3 commented on PaddleNLP/examples/slim/README.md
> +</p>
done, thanks

2020-12-15 13:25 UTC, ceci3 commented on PaddleNLP/examples/slim/README.md
> +| Task  | Metric                       | Result            | Result with PaddleSlim |
> 补充下ModelParam缩小的百分比，或者预测速度的提升百分比？

done, thanks

2020-12-16 05:39 UTC, guoshengCS approved these changes
LGTM

2020-12-16 05:39 UTC, guoshengCS commented on PaddleNLP/examples/slim/run_glue_ofa.py
> +            "width_mult: %f, eval loss: %f, acc: %s\n" %
`acc`可以换成metric.name，应该是之前run_glue.py中的遗留问题

2020-12-16 05:39 UTC, guoshengCS commented on PaddleNLP/examples/slim/run_glue_ofa.py
> +        "--eager_run", type=eval, default=True, help="Use dygraph mode.")
这里的eager_run可以去掉，也是之前run_glue.py中的遗留问题

2020-12-16 06:04 UTC, ceci3 commented on PaddleNLP/examples/slim/run_glue_ofa.py
> +            "width_mult: %f, eval loss: %f, acc: %s\n" %
done, thanks

2020-12-16 06:04 UTC, ceci3 commented on PaddleNLP/examples/slim/run_glue_ofa.py
> +        "--eager_run", type=eval, default=True, help="Use dygraph mode.")
done, thanks

2020-12-16 06:18 UTC, ZeyuChen approved these changes
LGTM

2020-12-16 06:18 UTC, merged