Add couplet examples
PaddlePaddle/models pull request #5007
Opened 2020-12-10 06:42 UTC by LiuChiachi

Add couplet examples

2020-12-10 08:19 UTC, ZeyuChen requested changes
有些小意见

2020-12-10 08:19 UTC, ZeyuChen commented on PaddleNLP/examples/text_generation/couplet/README.md
> +## 代码下载
将并设置`PYTHONPATH`环境变量 转换为PaddleNLP的pip安装

2020-12-10 08:19 UTC, ZeyuChen commented on PaddleNLP/examples/text_generation/couplet/README.md
> +cd examples/machine_translation/couplet
要在text generation这目录才对，不用写这些复杂的代码了，安装完paddlenlp就直接跑你的东西
默认认为用户会进来到这个目录

2020-12-10 08:19 UTC, ZeyuChen commented on PaddleNLP/examples/text_generation/couplet/README.md
> +git checkout develop
不用做这些复杂的checkout，因为到时会发release分支
直接认为用户就在你这个目录下操作即可

2020-12-10 08:19 UTC, ZeyuChen commented on PaddleNLP/examples/text_generation/couplet/model.py
> +        # print(cost.shape, trg_mask.shape)
删除无用代码

2020-12-10 08:19 UTC, ZeyuChen commented on PaddleNLP/examples/text_generation/couplet/model.py
> +            weight_attr=paddle.ParamAttr(initializer=I.Uniform(
看能不能代码组网这一侧弱化下这些默认参数的配置，尽量让组网代码进一步简洁
如果用默认参数效果也ok，就用默认的初始化参数

2020-12-10 08:19 UTC, ZeyuChen commented on PaddleNLP/examples/text_generation/couplet/model.py
> +            weight_attr=paddle.ParamAttr(initializer=I.Uniform(
简化下组网的构造成本，如果默认初始化效果不差就用默认的了，减少理解负担

2020-12-10 08:19 UTC, ZeyuChen commented on PaddleNLP/examples/text_generation/couplet/train.py
> +class Perplexity(paddle.metric.Metric):
也看下这个Metrics是否可以复用了，有可复用的话，教程代码可以进一步简化。

2020-12-10 08:19 UTC, ZeyuChen commented on PaddleNLP/examples/text_generation/couplet/train.py
> +    grad_clip = nn.ClipGradByGlobalNorm(args.max_grad_norm)
从这个对联的角度来说，我倾向继续简化训练的配置，看是否可以在默认配置下就出来不错的效果。

这样教程可以减少很多指导负担，用户理解起来也比较容易

2020-12-10 13:52 UTC, ZeyuChen requested changes
继续简化下组网的代码，省略下不必要的参数。
然后需要把BLUE的metrics从框架那里用上

2020-12-10 13:52 UTC, ZeyuChen commented on PaddleNLP/examples/text_generation/couplet/README.md
> +## 环境安装
不用写安装，这块到时也会都默认用户都安装了paddlenlp的。
因为你这里写了a0，后面需要不断改版本很麻烦

2020-12-10 13:52 UTC, ZeyuChen commented on PaddleNLP/examples/text_generation/couplet/data.py
> +DATA_HOME = "/root/.paddlenlp/datasets"
怎么写死DATA HOME了？还给了root？他自己不回用home目录吗？

2020-12-10 13:52 UTC, ZeyuChen commented on PaddleNLP/examples/text_generation/couplet/model.py
> +            dropout=dropout_prob if num_layers > 1 else 0.)
简化在简化，你确定下是否需要去控制这些dropoutprob, 如果一训基本能收敛的话就不要太复杂了。

2020-12-10 13:52 UTC, ZeyuChen commented on PaddleNLP/examples/text_generation/couplet/model.py
> +            direction="forward",
如果是单项的，这个参数forward本身为默认参数了，不需要额外配置

2020-12-10 13:52 UTC, ZeyuChen commented on PaddleNLP/examples/text_generation/couplet/model.py
> +                 dropout_prob=0.):
教程的组网代码要再精简，如果这个参数可以去掉就去掉吧

2020-12-11 06:51 UTC, LiuChiachi commented on PaddleNLP/examples/text_generation/couplet/model.py
> +                 dropout_prob=0.):
Thanks. Done.

2020-12-11 06:51 UTC, LiuChiachi commented on PaddleNLP/examples/text_generation/couplet/model.py
> +            direction="forward",
Thanks. Done.

2020-12-11 06:51 UTC, LiuChiachi commented on PaddleNLP/examples/text_generation/couplet/model.py
> +            dropout=dropout_prob if num_layers > 1 else 0.)
Thanks. Done.

2020-12-11 06:51 UTC, LiuChiachi commented on PaddleNLP/examples/text_generation/couplet/data.py
> +DATA_HOME = "/root/.paddlenlp/datasets"
Thanks. Done.

2020-12-11 06:51 UTC, LiuChiachi commented on PaddleNLP/examples/text_generation/couplet/README.md
> +## 环境安装
Thanks. Done.

2020-12-11 06:51 UTC, LiuChiachi commented on PaddleNLP/examples/text_generation/couplet/train.py
> +    grad_clip = nn.ClipGradByGlobalNorm(args.max_grad_norm)
Thanks. Done.

2020-12-11 06:51 UTC, LiuChiachi commented on PaddleNLP/examples/text_generation/couplet/model.py
> +        # print(cost.shape, trg_mask.shape)
Thanks. Done.

2020-12-11 06:51 UTC, LiuChiachi commented on PaddleNLP/examples/text_generation/couplet/README.md
> +git checkout develop
Thanks. Done.

2020-12-11 06:51 UTC, LiuChiachi commented on PaddleNLP/examples/text_generation/couplet/README.md
> +cd examples/machine_translation/couplet
Thanks. Done.

2020-12-11 07:04 UTC, guoshengCS commented on PaddleNLP/examples/text_generation/couplet/data.py
> +    def read_raw_data(self, corpus_path):
感觉自定义数据集还是有些复杂，可否将`get_data, build_vocab, read_raw_data, get_vocab `等看情况加入TranslationDataset基类中，感觉应该都差不多，自定义数据集只需要设置数据路径相关和init。

2020-12-11 07:36 UTC, ZeyuChen reviewed
一些小comments，其他意见郭晟决定。

2020-12-11 07:36 UTC, ZeyuChen commented on PaddleNLP/examples/text_generation/couplet/data.py
> +            print("IWSLT will be downloaded at ", root)
IWSLT不太对？

2020-12-11 07:36 UTC, ZeyuChen commented on PaddleNLP/examples/text_generation/couplet/data.py
> +            print("Downloaded success......")
`Download succeed.`

2020-12-11 07:36 UTC, ZeyuChen commented on PaddleNLP/examples/text_generation/couplet/data.py
> +                    print("Downloaded success......")
Download succeed. or Successfully downloaded

2020-12-11 07:36 UTC, ZeyuChen commented on PaddleNLP/examples/text_generation/couplet/data.py
> +    def read_raw_data(self, corpus_path):
嗯，我也同感

2020-12-12 11:39 UTC, guoshengCS commented on PaddleNLP/paddlenlp/datasets/translation.py
> +                    src_vocab._token_to_idx, tgt_vocab._idx_to_token)
Vocab本身具有`to_indices, to_indices, idx_to_token, token_to_idx`完成str序列和id序列转换以及获取两个转换词典的接口。 这里直接返回Vocab即可，也无需添加reverse参数。 还请 @LiuChiachi  @FrostML  注意。

2020-12-12 11:39 UTC, guoshengCS commented on PaddleNLP/paddlenlp/datasets/translation.py
> +    def build_vocab(cls, root=None, reverse=False):
如讨论，`build_vocab`可回`get_vocab`用于作为返回vocab的接口。

2020-12-12 11:39 UTC, guoshengCS commented on PaddleNLP/examples/text_generation/couplet/predict.py
> +    trg_idx2word, _ = CoupletDataset.build_vocab(reverse=True)
同TranslationDataset中修改内容的comment

2020-12-12 11:39 UTC, guoshengCS commented on PaddleNLP/examples/text_generation/couplet/data.py
> +        self.vocab, _ = CoupletDataset.build_vocab(root)
尽量还是优先使用self吧

2020-12-12 11:39 UTC, guoshengCS commented on PaddleNLP/examples/text_generation/couplet/data.py
> +            return func
vocab本身具有这些接口，应该可以直接使用to_indices

2020-12-12 11:39 UTC, guoshengCS commented on PaddleNLP/paddlenlp/datasets/translation.py
>          src_filename, tgt_filename, _, _ = self.SPLITS[mode]
SPLITS是class的属性，是否read_raw_data也改为classmethod

2020-12-12 14:11 UTC, guoshengCS approved these changes

2020-12-12 14:11 UTC, guoshengCS commented on PaddleNLP/examples/text_generation/couplet/data.py
> +        self.data = self.read_raw_data(root, mode)
后面可以看看能否将`get_data`（数据下载）也加到到`read_raw_data`中，没有的时候自动下载。

2020-12-12 16:07 UTC, LiuChiachi commented on PaddleNLP/paddlenlp/datasets/translation.py
>          src_filename, tgt_filename, _, _ = self.SPLITS[mode]
Done. Thanks

2020-12-12 16:07 UTC, ZeyuChen approved these changes
LGTM

2020-12-12 16:08 UTC, merged

2020-12-14 01:53 UTC, guoshengCS commented on PaddleNLP/paddlenlp/datasets/translation.py
> +                path = get_path_from_url(cls.URL, root, cls.MD5)
刚才 @FrostML  反馈这里的修改和之前的不一致，还要 @LiuChiachi  确认下。另外之前glue数据集里的root参数也不是下载数据用的目录（文档中有误），而是无需下载时提供的本地数据用的目录，这里处理方式也请 @smallv0221  注意下，已经看下是否要调整。

2020-12-14 02:06 UTC, guoshengCS commented on PaddleNLP/paddlenlp/datasets/translation.py
> +                path = get_path_from_url(cls.URL, root, cls.MD5)
> 后面可以看看能否将get_data（数据下载）也加到到read_raw_data中，没有的时候自动下载。

另外也把这个数据下载的get_data接口与数据合并吧，要不就先统一到glue的那种。