move [PAD] to the end
PaddlePaddle/models pull request #5022
Opened 2020-12-11 13:09 UTC by joey12300

1. move [PAD] to the end
2. Add Readme.md

2020-12-11 13:15 UTC, ZeyuChen requested changes
优化下README

2020-12-11 13:15 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/embeddings/README.md
> +* embedding_name：string，预训练embedding名称，可通过paddlenlp.embeddings.list_embedding_name查询。
用单括号扩下变量名，看起来不回太累

2020-12-11 13:15 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/embeddings/README.md
> +   0.043538  0.116647 -0.210486 -0.217972 -0.320675  0.293977  0.277564
不要给这么长的结果，中间要类似numpy print的那种省略

2020-12-11 15:00 UTC, joey12300 commented on PaddleNLP/paddlenlp/embeddings/README.md
> +* embedding_name：string，预训练embedding名称，可通过paddlenlp.embeddings.list_embedding_name查询。
已修改为表格形式
![image](https://user-images.githubusercontent.com/10826371/101918704-a161a980-3c04-11eb-823a-ab935ca8ffa1.png)

2020-12-11 15:01 UTC, joey12300 commented on PaddleNLP/paddlenlp/embeddings/README.md
> +   0.043538  0.116647 -0.210486 -0.217972 -0.320675  0.293977  0.277564
已修改为省略号形式。

![image](https://user-images.githubusercontent.com/10826371/101918788-be967800-3c04-11eb-8edd-77bb58b77de8.png)

![image](https://user-images.githubusercontent.com/10826371/101918813-c6561c80-3c04-11eb-98b0-635bdb8a3c14.png)

2020-12-12 11:03 UTC, ZeyuChen approved these changes
LGTM

2020-12-12 11:04 UTC, merged