Add more embedding
PaddlePaddle/models pull request #5036
Opened 2020-12-13 01:13 UTC by joey12300

1.  add more pretrained embedding  name
2. add embedding example

2020-12-13 13:53 UTC, ZeyuChen requested changes

2020-12-13 13:53 UTC, ZeyuChen commented on PaddleNLP/examples/word_embedding/utils.py
> +def convert_example(example, vocab, unk_token_id=1, is_test=False):
怎么会有两个convert example

2020-12-13 13:53 UTC, ZeyuChen commented on PaddleNLP/examples/word_embedding/utils.py
> +def convert_example(example, vocab, unk_token_id=1, is_test=False):
怎么会有两个convert example

2020-12-13 13:53 UTC, ZeyuChen commented on PaddleNLP/examples/word_embedding/utils.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
文件名改为data.py

2020-12-13 13:53 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/embeddings/token_embedding.py
>  EMBEDDING_HOME = _get_sub_home('embeddings', parent_home=MODEL_HOME)
为什么不再这里将EMBDDINGHOME直接跟MODEL_HOME join一下？

2020-12-13 13:53 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/embeddings/constant.py
> +EMBEDDING_NAME_LIST = [
https://github.com/PaddlePaddle/models/blob/develop/PaddleNLP/docs/embeddings.md
整理多一份文档放在此处

2020-12-13 13:53 UTC, ZeyuChen commented on PaddleNLP/examples/word_embedding/train.py
> +    if not args.use_token_embedding:
为什么185和172都有这个判断逻辑，是否可以简化

2020-12-13 13:53 UTC, ZeyuChen commented on PaddleNLP/examples/word_embedding/train.py
> +    label_list = train_ds.get_labels()
是否可以这里就直接计算num_labels？ 因为label_list没有在被其他人用过

2020-12-13 13:53 UTC, ZeyuChen commented on PaddleNLP/examples/word_embedding/utils.py
> +def convert_ids_to_tokens(wids, inversed_vocab):
这个函数有用吗？

2020-12-13 13:55 UTC, wawltor commented on PaddleNLP/examples/word_embedding/train.py
> +from utils import load_vocab, generate_batch, convert_example, set_tokenizer
这种场景下，使用代码规范更好 
import utils
utils.load_vocab("args.vocab_path")  # 这样能知道组织组织关系 

from的使用场景一半都是多级目录
例如上面的
from paddlenlp.data import JiebaTokenizer, Vocab

2020-12-13 13:55 UTC, wawltor commented on PaddleNLP/examples/word_embedding/train.py
> +    "--vdl_dir", type=str, default="vdl_dir/", help="VisualDL directory")
VisualDL log directory

2020-12-13 13:55 UTC, wawltor commented on PaddleNLP/examples/word_embedding/train.py
> +            dataset=dataset, batch_size=batch_size, shuffle=True)
因为这个示例只支持单机单卡训练，这里直接BatchSampler

2020-12-13 14:05 UTC, wawltor commented on PaddleNLP/examples/word_embedding/train.py
> +            dataset=dataset, batch_size=batch_size, shuffle=shuffle)
这里的逻辑统一下，直接BatchSampler, 在训练的时候需要shuffle，validation/test场景不需要shuffle

2020-12-13 14:05 UTC, wawltor commented on PaddleNLP/examples/word_embedding/train.py
> +        vocab['[PAD]'] = len(vocab)
这块的逻辑是否有点随意？ 
是否要判断一下'[PAD]' 在vocab里面再增加？ 还有这里是否考虑直接给voab增加一个'[PAD]' 了，不需要判断use_token_embedding，正常情况下如果在token_embedding要判断'[PAD]' 是否在vocab里面，没有的话再增加

2020-12-13 14:05 UTC, wawltor commented on PaddleNLP/examples/word_embedding/utils.py
> +    #v = Vocab.from_dict(vocab, unk_token="[UNK]", pad_token="[PAD]")
这行去掉

2020-12-14 02:22 UTC, joey12300 commented on PaddleNLP/examples/word_embedding/train.py
> +            dataset=dataset, batch_size=batch_size, shuffle=shuffle)
done

2020-12-14 02:23 UTC, joey12300 commented on PaddleNLP/examples/word_embedding/train.py
> +    "--vdl_dir", type=str, default="vdl_dir/", help="VisualDL directory")
done

2020-12-14 02:25 UTC, joey12300 commented on PaddleNLP/examples/word_embedding/utils.py
> +def convert_example(example, vocab, unk_token_id=1, is_test=False):
已删除

2020-12-14 02:26 UTC, joey12300 commented on PaddleNLP/examples/word_embedding/utils.py
> +def convert_ids_to_tokens(wids, inversed_vocab):
已删除

2020-12-14 02:31 UTC, joey12300 commented on PaddleNLP/paddlenlp/embeddings/token_embedding.py
>  EMBEDDING_HOME = _get_sub_home('embeddings', parent_home=MODEL_HOME)
因为该函数作了判断，判断join后的目录是否存在，不存在则创建。直接join的话没有做判断，需要把判断下放到调用的地方，增加了复杂度

2020-12-14 07:22 UTC, joey12300 commented on PaddleNLP/paddlenlp/embeddings/constant.py
> +EMBEDDING_NAME_LIST = [
done

2020-12-14 07:37 UTC, joey12300 commented on PaddleNLP/examples/word_embedding/train.py
> +        vocab['[PAD]'] = len(vocab)
已修改。在TokenEmbedding那里也添加了判断。

2020-12-14 07:38 UTC, joey12300 commented on PaddleNLP/examples/word_embedding/train.py
> +    if not args.use_token_embedding:
172逻辑有点问题，已修改判断的条件

2020-12-14 11:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/models?pullRequest=5036) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/models?pullRequest=5036) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: joey12300<br/>:x: wawltor<br/><hr/>**wawltor** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/models?pullRequest=5036) it.</sub>

2020-12-14 12:44 UTC, wawltor approved these changes
LGTM

2020-12-14 12:45 UTC, merged