support AMP training
PaddlePaddle/models pull request #5067
Opened 2020-12-16 06:00 UTC by zhangting2020

support AMP training

2020-12-16 06:27 UTC, ZeyuChen requested changes
distutils的import看上去没用到？
另外AMP什么时候能有非fluid的正式API

2020-12-16 06:27 UTC, ZeyuChen commented on PaddleNLP/benchmark/transformer/static/train.py
> +            amp_list = paddle.fluid.contrib.mixed_precision.AutoMixedPrecisionLists(
现在还没有paddel目录下的API吗？

2020-12-16 06:27 UTC, ZeyuChen commented on PaddleNLP/benchmark/transformer/static/train.py
> +import distutils.util
添加这个是为了？

2020-12-16 07:23 UTC, zhangting2020 commented on PaddleNLP/benchmark/transformer/static/train.py
> +            amp_list = paddle.fluid.contrib.mixed_precision.AutoMixedPrecisionLists(
这个PR暂时不合入，待AMP接口这两天迁移完后，会改成paddle.xx

2020-12-17 08:45 UTC, Xreki commented on PaddleNLP/benchmark/transformer/static/train.py
> +            amp_list = paddle.fluid.contrib.mixed_precision.AutoMixedPrecisionLists(
已经有了paddle.static.amp API了，不过没有cherry-pick到2.0rc1，@zhangting2020 可以改成新的接口了。

2020-12-17 11:45 UTC, zhangting2020 commented on PaddleNLP/benchmark/transformer/static/train.py
> +            amp_list = paddle.fluid.contrib.mixed_precision.AutoMixedPrecisionLists(
Done.

2020-12-17 11:45 UTC, zhangting2020 commented on PaddleNLP/benchmark/transformer/static/train.py
> +import distutils.util
已删除

2021-01-15 03:12 UTC, FrostML approved these changes
LGTM

2021-01-16 06:44 UTC, ZeyuChen approved these changes
LGTM

2021-01-18 03:03 UTC, merged