[WIP]Add data.md
PaddlePaddle/models pull request #5071
Opened 2020-12-16 08:08 UTC by xiemoyuan

Add data.md for paddlenlp.data APIs.

2020-12-16 10:19 UTC, ZeyuChen requested changes
反馈了一些意见

2020-12-16 10:19 UTC, ZeyuChen commented on PaddleNLP/docs/data.md
> +```
这个有例子吗？看不太出Tuple的作用

2020-12-16 10:19 UTC, ZeyuChen commented on PaddleNLP/docs/data.md
> +
在这里补充下介绍更加好，API的说明

2020-12-16 10:19 UTC, ZeyuChen commented on PaddleNLP/docs/data.md
> +```
最后面再补充下与collate_fn结合的一些用法示例

2020-12-16 12:16 UTC, xiemoyuan commented on PaddleNLP/docs/data.md
> +```
已经修改了示例程序

2020-12-16 12:17 UTC, xiemoyuan commented on PaddleNLP/docs/data.md
> +
已经修改了示例程序

2020-12-16 13:07 UTC, ZeyuChen requested changes
@guoshengCS 进一步指导吧，SamplerHelper这块感觉还不够清晰

2020-12-16 13:07 UTC, ZeyuChen commented on PaddleNLP/docs/data.md
> +tokens = tokenizer.cut('我爱你中国')
像这种API，下面要加 
>>> 然后把对应结果print出来，可能更有API示例的感觉。

2020-12-16 13:07 UTC, ZeyuChen commented on PaddleNLP/docs/data.md
> +result = Pad(axis=0, pad_val=0)([a, b, c])
axis的说明样例没体现出来

2020-12-16 13:07 UTC, ZeyuChen commented on PaddleNLP/docs/data.md
> +```
能有可视化的样例体现这个Tuple的作用吗？现在确实不太好理解

2020-12-16 13:07 UTC, ZeyuChen commented on PaddleNLP/docs/data.md
> +batch_sampler = SamplerHelper(dataset).shuffle().batch(
需要示例，一个个清晰可感知的示例体现出
shuffle，sort，batch，shard的作用比较好

2020-12-17 01:59 UTC, guoshengCS commented on PaddleNLP/docs/data.md
> +): fn(samples)
这里应该直接用创建的Tuple实例就可以
```python
batchify_fn = Tuple(
    Pad(axis=0, pad_val=pad_id),  # ids
    Stack(dtype='int64')  # label
)
```

2020-12-17 01:59 UTC, guoshengCS commented on PaddleNLP/docs/data.md
> +    drop_last=True)
感觉drop_last用默认的False好些，一方面能稍微简短些，另一方面对特殊情况（不足batch size）的处理也能表现的更清楚些。

2020-12-17 01:59 UTC, guoshengCS commented on PaddleNLP/docs/data.md
> +batch_sampler = SamplerHelper(dataset).shuffle().batch(
这里可以用个简单的dataset，比如就是100到110的list，shuffle，sort，batch，shard的每一步后都写出迭代打印的结果，注意这里产生的是index的迭代器非数据本身

2020-12-17 01:59 UTC, guoshengCS commented on PaddleNLP/docs/data.md
> +dataset = GlueCoLA('train')
如果用JiebaTokenizer都话是否这里需要换用个中文数据集

2020-12-17 01:59 UTC, guoshengCS commented on PaddleNLP/docs/data.md
> +    batch_size=batch_size,
这里就直接`batch_size=16`吧，示例文档能简洁些还是简洁些吧

2020-12-17 01:59 UTC, guoshengCS commented on PaddleNLP/docs/data.md
> +## API使用方法
是否可以就这些API的作用分类说明，从dataloader中dataset、sampler和collate_fn三个参数展开。Stack/Pad/Tuple用来做collate_fn，SamplerHelper用来做batch_sampler，Tokenizer/Vocab用于dataset（对dataset做transform）。

2020-12-17 07:20 UTC, guoshengCS commented on PaddleNLP/docs/data.md
> +# SamplerHelper返回的是数据的索引
`SamplerHelper返回的是数据索引的可迭代对象`  是否更准确些

2020-12-17 07:20 UTC, guoshengCS commented on PaddleNLP/docs/data.md
> +sampler = sampler.batch(batch_size=2) #[[2, 0], [1]]
shuffle、sort、batch这里的注释说明可能还要更详细些
如sort可以说明是 `按照样本的首个字段的长度为key并在buffer_size大小个样本中排序，产生的迭代的索引为：[2, 0, 1]
`
shard的使用也可以在最后加上去

2020-12-17 07:20 UTC, guoshengCS commented on PaddleNLP/docs/data.md
> +vocab3 = Vocab.from_json(json_str)
json的话会对能加载的格式有一定要求，配合to_json先to_json再from_json使用吧，

2020-12-17 09:57 UTC, guoshengCS approved these changes

2020-12-17 10:00 UTC, merged