export text classification model in static graph
PaddlePaddle/models pull request #5226
Opened 2021-01-25 07:29 UTC by Steffy-zxf

* add export_model.py 
* update lstm/gru/rnn directional parameter setting (bidirectional -> bidirect)

2021-01-25 07:56 UTC, wawltor approved these changes
LSTM

2021-01-25 07:56 UTC, wawltor commented on PaddleNLP/examples/text_classification/pretrained_models/README.md
> +```
这块是否再解释一下 --model_name --params_path 等变量名字

2021-01-25 07:56 UTC, wawltor commented on PaddleNLP/examples/text_classification/pretrained_models/export_model.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
2020 -> 2021

2021-01-25 07:56 UTC, wawltor commented on PaddleNLP/examples/text_classification/rnn/export_model.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
同上

2021-01-25 07:56 UTC, wawltor commented on PaddleNLP/examples/text_classification/rnn/export_model.py
> +from utils import load_vocab, generate_batch, preprocess_prediction_data
这块的preprocess_prediction_data, generate_batch import好像没有用到

2021-01-25 07:56 UTC, wawltor commented on PaddleNLP/examples/text_matching/simnet/predict.py
> +        probs = F.softmax(logits, axis=1)
这里有个疑问，为啥要把softmax放到外部了？

2021-01-25 07:56 UTC, wawltor commented on PaddleNLP/paddlenlp/models/senta.py
> +        att_weight = self.att_weight.tile(shape=(paddle.shape(h)[0], 1, 1))
repeat_times

2021-01-25 08:17 UTC, Steffy-zxf commented on PaddleNLP/paddlenlp/models/senta.py
> +        att_weight = self.att_weight.tile(shape=(paddle.shape(h)[0], 1, 1))
done

2021-01-25 08:18 UTC, Steffy-zxf commented on PaddleNLP/examples/text_matching/simnet/predict.py
> +        probs = F.softmax(logits, axis=1)
`paddle.nn.CrossEntropyLoss` 内部使用的是 softmax_with_cross_entropy

2021-01-25 08:21 UTC, Steffy-zxf commented on PaddleNLP/examples/text_classification/pretrained_models/export_model.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
done

2021-01-25 08:21 UTC, Steffy-zxf commented on PaddleNLP/examples/text_classification/rnn/export_model.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
done

2021-01-25 08:21 UTC, Steffy-zxf commented on PaddleNLP/examples/text_classification/rnn/export_model.py
> +from utils import load_vocab, generate_batch, preprocess_prediction_data
done

2021-01-25 08:25 UTC, Steffy-zxf commented on PaddleNLP/examples/text_classification/pretrained_models/README.md
> +```
`model_name`, `model_type` 上面的文档已有相应的解释。增加补充了`params_path `和`output_path `参数解释。

2021-01-25 09:48 UTC, ZeyuChen requested changes
重新调整下注释。
如果当作正常语句组织，要用标准英文单词 bidirectional
如果需要告知用户是代码片段或变量，则要用单引号括起来。

2021-01-25 09:48 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/seq2vec/encoder.py
> +    The output is of shape `(batch_size, hidden_size*2)` if GRU is bidirect;
我觉得就文档注释而言，应该保留原始英文语义bidirectional

2021-01-25 09:48 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/seq2vec/encoder.py
> +    And if direction is bidirect, the we concat the hidden state of the last forward
如果你要这里使用bidirect, 就需要用单引号括起来，表示他是代码参数变量

2021-01-25 09:48 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/seq2vec/encoder.py
> +            It can be "forward" and "bidirect".
应该用单引号，表示代码变量

2021-01-25 09:48 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/seq2vec/encoder.py
> +        The output is of shape `(batch_size, hidden_size*2)` if GRU is bidirect;
The output is of shape `(batch_size, hidden_size*2)` if use bidirectional GRU.

2021-01-25 09:48 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/seq2vec/encoder.py
> +            # If gru is not bidirect, then output is the hidden state of the last time step
还是要用bidirectional，不然注释都有词法错误

2021-01-25 09:48 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/seq2vec/encoder.py
> +    The output is of shape `(batch_size, hidden_size*2)` if LSTM is bidirect;
if use Bi-LSTM

2021-01-25 09:49 UTC, ZeyuChen requested changes
重新调整下注释。
如果当作正常语句组织，要用标准英文单词 bidirectional
如果需要告知用户是代码片段或变量，则要用单引号括起来。

2021-01-27 17:24 UTC, ZeyuChen reviewed
这里的英文注释存在严重语法和流畅性问题，是否考虑先合入后再整体专项做一次优化。

2021-01-27 17:24 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/seq2vec/encoder.py
> +            It can be "forward" and "bidirect" (it means bidirection network).
and -> or

2021-01-27 17:24 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/seq2vec/encoder.py
> +            When "bidirection", the way to merge outputs of forward and backward is concatenating.
这里的注释存在不少病句，语言不通

2021-01-27 17:24 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/seq2vec/encoder.py
> +            When "bidirection", the way to merge outputs of forward and backward is concatenating.
不通畅

2021-01-27 17:24 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/seq2vec/encoder.py
> +            # If rnn is bidirection, then output is shape of `(batch_size, hidden_size*2)`.
The output shape is `(batch_size, hidden_size*2)` if use bidirectional RNN, otherwise the output shape is `(batch_size, hidden_size*2)`

需要用简洁的语言来表达，整个模块的API文档注释存在比较大的不通顺问题。后续都需要优化。

2021-01-27 17:24 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/seq2vec/encoder.py
>          direction (obj:`str`, optional, defaults to obj:`forwrd`): The direction of the network.
forwrd->forward

2021-01-27 17:24 UTC, ZeyuChen commented on PaddleNLP/paddlenlp/seq2vec/encoder.py
> +            When "bidirection", the way to merge outputs of forward and backward is concatenating.
If `biderect`, becomes a birectional RNN, and will return the concat output from both directions.

这样是否会更简洁点？

2021-01-28 03:39 UTC, wawltor approved these changes
LGTM

2021-01-28 03:39 UTC, wawltor approved these changes
LGTM

2021-01-28 03:40 UTC, merged