[WIP] Baseline of lic2021 dialogue competition.
PaddlePaddle/models pull request #5241
Opened 2021-01-28 03:35 UTC by xiemoyuan

Upgrade the baseline of lic2021 dialogue competition using Paddle2.0

2021-02-01 17:10 UTC, sserdoubleh commented on PaddleNLP/examples/dialogue/lic2021/data.py
> +        fp = gzip.open(filename, "rt")
add `import gzip`

2021-02-01 17:10 UTC, sserdoubleh commented on PaddleNLP/examples/dialogue/lic2021/data.py
> +                cols = list(map(lambda x: list(map(int, x.split(" "))), cols))
只支持序列化数据吗？

2021-02-01 17:10 UTC, sserdoubleh commented on PaddleNLP/examples/dialogue/lic2021/finetune.py
> +        grad_clip=nn.ClipGradByGlobalNorm(args.max_grad_norm))
weight decay exclude LN parameters

2021-02-02 02:30 UTC, xiemoyuan commented on PaddleNLP/examples/dialogue/lic2021/data.py
> +        fp = gzip.open(filename, "rt")
Done. Thanks.

2021-02-02 02:32 UTC, xiemoyuan commented on PaddleNLP/examples/dialogue/lic2021/data.py
> +                cols = list(map(lambda x: list(map(int, x.split(" "))), cols))
数据读取这边的要求是怎样的呢？给到我这边的数据集是序列化后的，是先运行一个数据转换脚本转成序列化的数据吗？后续需要直接用原始数据作为输入吗？

2021-02-02 03:42 UTC, xiemoyuan commented on PaddleNLP/examples/dialogue/lic2021/finetune.py
> +        grad_clip=nn.ClipGradByGlobalNorm(args.max_grad_norm))
Done. Thanks.

2021-02-02 06:55 UTC, ZeyuChen requested changes
精简下args参数这地方，简化下代码，目前这里他Icahn过了

2021-02-02 06:55 UTC, ZeyuChen commented on PaddleNLP/examples/dialogue/lic2021/args.py
> +def parse_args():
后续统一下标准，parse_args这里
一个flag一行代码，使用yapf:disable 和yapf:enable 隔开，避免语法检查。减少下代码行数

2021-02-02 06:55 UTC, ZeyuChen commented on PaddleNLP/examples/dialogue/lic2021/finetune.py
> +    model = BaselineModel(
感觉BaselineModel不是个好名称，是否有一个基础模型名称，如XXTransformer？

2021-02-02 07:17 UTC, xiemoyuan commented on PaddleNLP/examples/dialogue/lic2021/finetune.py
> +    model = BaselineModel(
原来的名字叫UnifiedTransformer，那我改成这个

2021-02-03 09:21 UTC, xiemoyuan commented on PaddleNLP/examples/dialogue/lic2021/args.py
> +def parse_args():
Done. Thanks.

2021-04-25 16:24 UTC, closed without merging