add paddle lite doc
PaddlePaddle/models pull request #5434
Opened 2021-12-22 11:45 UTC by xingjing1

2021-12-22 11:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/models?pullRequest=5434) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/models?pullRequest=5434) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/models?pullRequest=5434) it.</sub>

2021-12-22 23:55 UTC, leiqing1 requested changes

2021-12-22 23:55 UTC, leiqing1 commented on tutorials/mobilenetv3_prod/Step6/README.md
> +python export_model.py --pretrained=../mobilenet_v3_small_paddle_pretrained.pdparams  --save-inference-dir=./inference_model
是不是改成改命令比较适合？
python3 tools/export_model.py --pretrained=./mobilenet_v3_small_pretrained.pdparams  --save-inference-dir=./inference_model
不然，（1）从操作层面，也没有cd tools操作；（2）从代码文件管理角度，把生成的inference模型放到tools下面也不合理。

2021-12-22 23:55 UTC, leiqing1 commented on tutorials/mobilenetv3_prod/Step6/README.md
> +在inference_model文件夹下有inference.pdmodel和inference.pdiparams文件。
在inference_model文件夹下生成inference.pdmodel、inference.pdiparams和inference.pdiparams.info文件。

2021-12-22 23:55 UTC, leiqing1 commented on tutorials/mobilenetv3_prod/Step6/README.md
> +模型转换工具[opt_linux](https://github.com/PaddlePaddle/Paddle-Lite/releases/download/v2.10/opt_linux)、[opt_mac](https://github.com/PaddlePaddle/Paddle-Lite/releases/download/v2.10/opt_mac)。或者参考[文档](https:
这里分成两步写比较适合？
1.安装模型转换工具 opt（以安装可跳过此步骤）：opt_linux(linux环境下的准备)参考https://github.com/PaddlePaddle/Paddle-Lite/releases/download/v2.10/opt_linux.......
2.利用opt工具转换模型
......

2021-12-22 23:55 UTC, leiqing1 commented on tutorials/mobilenetv3_prod/Step6/README.md
> +以 Ubuntu 为例介绍安装命令。注意需要 root 用户权限执行如下命令。
增加下，
mac环境安装参考链接：
windows环境安装参考链接：

2021-12-23 03:28 UTC, xingjing1 commented on tutorials/mobilenetv3_prod/Step6/README.md
> +模型转换工具[opt_linux](https://github.com/PaddlePaddle/Paddle-Lite/releases/download/v2.10/opt_linux)、[opt_mac](https://github.com/PaddlePaddle/Paddle-Lite/releases/download/v2.10/opt_mac)。或者参考[文档](https:
已修改

2021-12-23 03:28 UTC, xingjing1 commented on tutorials/mobilenetv3_prod/Step6/README.md
> +以 Ubuntu 为例介绍安装命令。注意需要 root 用户权限执行如下命令。
已修改

2021-12-23 03:28 UTC, xingjing1 commented on tutorials/mobilenetv3_prod/Step6/README.md
> +在inference_model文件夹下有inference.pdmodel和inference.pdiparams文件。
已修改

2021-12-23 03:28 UTC, xingjing1 commented on tutorials/mobilenetv3_prod/Step6/README.md
> +python export_model.py --pretrained=../mobilenet_v3_small_paddle_pretrained.pdparams  --save-inference-dir=./inference_model
已修改

2021-12-29 05:34 UTC, littletomatodonkey commented
麻烦参考下群里同步的内容整理下内容哈~

2022-01-04 12:59 UTC, chenjiaoAngel commented on tutorials/mobilenetv3_prod/Step6/README.md
> +    - [5.1 使用paddle-lite部署]()
paddle-lite 格式不对，统一是 Paddle Lite
如果是工程目录可以写:Paddle-Lite/lite/*

2022-01-04 12:59 UTC, chenjiaoAngel commented on tutorials/mobilenetv3_prod/Step6/README.md
> +        - [5.1.4 以arm v8 、android系统为例进行部署,开发机为ubuntu]()
android 建议统一写Android 
中英文间建议空格隔开

2022-01-04 12:59 UTC, chenjiaoAngel commented on tutorials/mobilenetv3_prod/Step6/README.md
> +        - [5.1.5 lite提供的mobilenet_light demo 的预测步骤分析以及添加前处理方法]()
lite 统一改为 Paddle Lite

2022-01-04 12:59 UTC, chenjiaoAngel commented on tutorials/mobilenetv3_prod/Step6/README.md
> +以 Ubuntu 为例介绍安装命令。注意需要 root 用户权限执行如下命令。mac环境下编译android库参考[链接](https://paddle-lite.readthedocs.io/zh/develop/source_compile/macos_compile_android.html)，windows下暂不支持编译android版本库。
链接 改为 Android 源码编译

2022-01-04 12:59 UTC, chenjiaoAngel commented on tutorials/mobilenetv3_prod/Step6/README.md
> + 推荐使用Paddle-Lite仓库提供的release的lib包，[下载链接](https://github.com/PaddlePaddle/Paddle-Lite/releases/tag/v2.10),在网页最下边选取要使用的lib包。
的release的lib包，[下载链接](ht ==》
的[release](https://github.com/PaddlePaddle/Paddle-Lite/releases/tag/v2.10)库

2022-01-04 13:43 UTC, littletomatodonkey commented on tutorials/mobilenetv3_prod/Step6/README.md
> +    - [5.1 使用 Paddle Lite 部署]()
首页不需要改动，后续我统一整理部署的首页链接哈

2022-01-04 13:43 UTC, littletomatodonkey commented on tutorials/mobilenetv3_prod/Step6/README.md
> +### 5.1 使用 Paddle Lite 部署
1. 这里的实战内容放在 https://github.com/PaddlePaddle/models/blob/release%2F2.2/tutorials/mobilenetv3_prod/Step6/deploy/lite_infer_cpp_arm_cpu/README.md 里面
2. 功能开发内容放在 https://github.com/PaddlePaddle/models/blob/release%2F2.2/tutorials/tipc/lite_infer_cpp_arm_cpu/lite_infer_cpp_arm_cpu.md 里面

2022-01-07 13:33 UTC, littletomatodonkey commented on tutorials/mobilenetv3_prod/Step6/deploy/lite_infer_cpp_arm_cpu/README.md
> +<div align="center">
1. 流程图可以按照群里沟通的ppt重新绘制一下，把其中的1，2，3，4，5重点写出来就行哈
2. 第一步建议介绍下环境准备，告诉用户在哪个环境中可以去做lite开发部署

2022-01-07 13:33 UTC, littletomatodonkey commented on tutorials/mobilenetv3_prod/Step6/deploy/lite_infer_cpp_arm_cpu/README.md
> +python ./tools/export_model.py --pretrained=./mobilenet_v3_small_paddle_pretrained.pdparams  --save-inference-dir=./inference_model
1. 这个预训练模型的名字需要更新下`mobilenet_v3_small_pretrained.pdparams`
2. 介绍下这个命令需要在哪个文件夹下运行，或者在运行之前直接给出cd的命令，如`cd tutorials/mobilenetv3_prod/Step6`

2022-01-07 13:33 UTC, littletomatodonkey commented on tutorials/mobilenetv3_prod/Step6/deploy/lite_infer_cpp_arm_cpu/README.md
> +### 2.3 以 arm v8 、Android 系统为例进行部署,开发机系统为 Ubuntu
这块环境的说明都放到第一步吧，不然用户看到这里才知道自己需要准备什么环境，

2022-01-07 13:33 UTC, littletomatodonkey commented on tutorials/mobilenetv3_prod/Step6/deploy/lite_infer_cpp_arm_cpu/README.md
> +在当前文件夹下可以发现mobilenet_v3.nb文件。
可以发现 -> 会生成

2022-01-07 13:33 UTC, littletomatodonkey commented on tutorials/mobilenetv3_prod/Step6/deploy/lite_infer_cpp_arm_cpu/README.md
> +./opt --model_file=./inference_model/inference.pdmodel --param_file=./inference_model/inference.pdiparams --optimize_out=./mobilenet_v3
这里使用`pip install paddlelite`的方式是否也可以直接调用`paddlelite_opt`工具呢？应该会更方便一些？或者两种都介绍一下哈

2022-01-07 13:33 UTC, littletomatodonkey commented on tutorials/mobilenetv3_prod/Step6/deploy/lite_infer_cpp_arm_cpu/README.md
> +git、make、wget、python、adb
这个目录下需要放cpp 文件，保证基于该目录的项目可以被编译，且它可以作为一个独立的lite项目，可以参考
: https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.3/deploy/lite/readme.md , 整个目录是可以单独执行的

2022-01-07 13:33 UTC, littletomatodonkey commented on tutorials/tipc/lite_infer_cpp_arm_cpu/lite_infer_cpp_arm_cpu.md
> +# Paddle Lite arm cpu 推理开发文档
arm和cpu都大写吧

2022-01-07 13:33 UTC, littletomatodonkey commented on tutorials/tipc/lite_infer_cpp_arm_cpu/lite_infer_cpp_arm_cpu.md
> +    - [2.1 准备模型 ](#2.1)
前面加一个步骤：准备环境

2022-01-07 13:33 UTC, littletomatodonkey commented on tutorials/tipc/lite_infer_cpp_arm_cpu/lite_infer_cpp_arm_cpu.md
> +Paddle Lite 框架直接支持模型结构为[ PaddlePaddle ](https://www.paddlepaddle.org.cn/)深度学习框架产出的模型格式。在 PaddlePaddle 静态图模式下，使用`save_inference_model`这个 API 保存预测模型，Paddle Lite 对此类预测模型已经做了充分支持；在 PaddlePaddle 动态图模式下，使用
每个步骤分成 1. 基本流程 2. 注意事项 3. 实战 ，告诉开发者一步步怎么做

* 基本流程：完成准备模型这个步骤需要做的事情
* 注意事项：在这个过程中可能会遇到的一些问题
* 实战：给一下`tutorials/mobilenetv3_prod/Step6/deploy/lite_infer_cpp_arm_cpu/`目录下对应的文档或者代码链接

下面每个步骤同理，可以参考群里发的pr

2022-01-07 13:33 UTC, littletomatodonkey commented on tutorials/tipc/lite_infer_cpp_arm_cpu/lite_infer_cpp_arm_cpu.md
> +Paddle Lite提供了 `C++` 、`Java` 、`Python` 三种 `API` ，只需简单五步即可完成预测（以 `C++ API` 为例）：
这种环境性问题，在第一步就介绍清楚，不建议在最后再说以这个为例。

2022-01-12 07:26 UTC, littletomatodonkey requested changes

2022-01-12 07:26 UTC, littletomatodonkey commented on tutorials/mobilenetv3_prod/Step6/deploy/lite_infer_cpp_arm_cpu/README.md
> +适用于 ``` python == 2.7\3.5\3.6\3.7 ```
python2.7去掉吧

2022-01-12 07:26 UTC, littletomatodonkey commented on tutorials/mobilenetv3_prod/Step6/deploy/lite_infer_cpp_arm_cpu/README.md
> +pip install paddlelite==2.10
pip3

2022-01-12 07:26 UTC, littletomatodonkey commented on tutorials/mobilenetv3_prod/Step6/deploy/lite_infer_cpp_arm_cpu/README.md
> +# 引用Paddlelite预测库
这个文件写成一个py文件吧，输入和输出参数可以指定，让用户执行这个py文件即可

2022-01-12 07:26 UTC, littletomatodonkey commented on tutorials/mobilenetv3_prod/Step6/deploy/lite_infer_cpp_arm_cpu/README.md
> +===clas result for image: ./demo.jpg===
1. 用这个图片测试吧，tutorials/mobilenetv3_prod/Step6/images/demo.jpg
2. 输出结果也再确认下，看着不对

2022-01-12 07:26 UTC, littletomatodonkey commented on tutorials/mobilenetv3_prod/Step6/deploy/lite_infer_cpp_arm_cpu/README.md
> +最终输出结果为 ```class_id: 8, prob: 0.9091238975524902``` ，表示预测的类别ID是```8```，置信度为```0.909```。
这结果和lite输出明显对不上啊...inference用的pil库，如果是cv2的预处理的话class id应该不变，prob稍有变化，在下面说明下就好

2022-01-12 07:26 UTC, littletomatodonkey commented on tutorials/mobilenetv3_prod/Step6/deploy/lite_infer_cpp_arm_cpu/mobilenet_v3/Makefile.def
> +CXX_DEFINES = -DARM_WITH_OMP -DHPPL_STUB_FUNC -DLITE_WITH_ARM -DLITE_WITH_LIGHT_WEIGHT_FRAMEWORK \
这个文件是必须的吗？是不是可以删掉

2022-01-12 12:39 UTC, littletomatodonkey approved these changes

2022-01-12 12:39 UTC, merged