add paddle2onnx doc
PaddlePaddle/models pull request #5446
Opened 2021-12-28 12:54 UTC by neonhuang

添加paddle2onnx 文档

2021-12-29 05:08 UTC, littletomatodonkey commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +## 1. 简介
建议补充一个流程图哈，可以参考：https://github.com/PaddlePaddle/models/blob/release%2F2.2/docs/tipc/train_infer_python/infer_python.md

2021-12-29 05:08 UTC, littletomatodonkey commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +需要准备 Paddle2ONNX 模型转化环境，和 ONNX 模型预测环境
1. 每个部分需要包含基本流程、注意事项以及实战，如果有核验点的话，可以再加一个核验的部分（验证用户在走到这个环节的时候是没有问题的）。
2. 这个文档是比较通用的说明文档，关于mv3的代码部分可以放在实战部分内容中~
3. 可以参考上面infer_python.md的链接，提供一些代码模板出来哈，方便用户直接拷贝修改使用

2021-12-29 15:42 UTC, littletomatodonkey commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +python3.7 -m pip install paddle2onnx
python3.7统一修改为python3吧，方便废py3.7环境的用户使用~

2021-12-29 15:42 UTC, littletomatodonkey commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +使用 Paddle2ONNX 将Paddle静态图模型转换为ONNX模型格式：
说明文档可以更通用一点，下面具体的代码和使用文档可以放在`https://github.com/zhangbo9674/models/blob/dev%2Famp_train_doc_new/tutorials/mobilenetv3_prod/Step6/deploy/onnx_python/README.md`目录下，另外就是这里尽量写的通用一些哈，比如说这个命令转换，可以写成

**【基本内容】**

paddle2onnx --model_dir=${your_inference_model_dir} \
--model_filename=${your_pdmodel_file} \
--params_filename=${your_pdiparams_file} \
--save_file=${output_file} \
--opset_version=10 \
--enable_onnx_checker=True

其中`${your_inference_model_dir}`指的是xxx，另外5个参数的含义也同理说明下哈

**【注意事项】**

（如果有）

**【实战】**

参考mobilenetv3的paddle2onnx使用文档中的第xx章节

2021-12-29 16:13 UTC, littletomatodonkey commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +执行完毕后，ONNX 模型会被保存在 `./inference/mobilenetv3_model/` 路径下
这个具体的内容可以作为`实战`环节呈现出来

2021-12-29 16:13 UTC, littletomatodonkey commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +表示预测的类别ID是`8`，置信度为`0.909`，该结果与基于训练引擎的结果完全一致
因为onnx model是从inference model转化过来的，所以这个可以和inference model的结果进行对比哈

2022-01-10 08:26 UTC, jiangjiajun requested changes

2022-01-10 08:26 UTC, jiangjiajun commented on tutorials/mobilenetv3_prod/Step6/deploy/onnx_python/README.md
> +执行完毕后，ONNX 模型会被保存在 `./inference/mobilenetv3_model/` 路径下
这些参数怎么用，更多关于参数的用法应该有一个超链可以让用户点过去看

2022-01-10 08:26 UTC, jiangjiajun commented on tutorials/mobilenetv3_prod/Step6/deploy/onnx_python/README.md
> +
这里改成
ONNX作为开源的神经网络交换格式，得到大多数推理引擎的部署支持。在本文档中我们采用微软开源的onnxruntime推理引擎，进行转换后模型的正确性较验。

2022-01-10 08:26 UTC, jiangjiajun commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +- 安装 ONNX
这里标题改为

## 安装onnxruntime
ONNX作为开源的神经网络交换格式，得到大多数推理引擎的部署支持。在本文档中我们采用微软开源的onnxruntime推理引擎，进行转换后模型的正确性较验。

2022-01-10 08:26 UTC, jiangjiajun commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +- Paddle 模型动转静导出
“动转静导出” 这个术语是TIPC中专有的吗，是否是“部署模型导出”

2022-01-10 08:26 UTC, jiangjiajun commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +### 2.3 ONNX 预测
前面是ONNX推理，这里是ONNX预测，都统一成 ONNX模型推理

2022-01-10 08:26 UTC, jiangjiajun commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +使用ONNXRuntime测试ONNX模型模型，确保模型精度符合预期
请确认下官方名是ONNXRuntime还是onnxruntime，然后统一一下

2022-01-10 12:44 UTC, neonhuang commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +python3.7 -m pip install paddle2onnx
处理了。

2022-01-10 12:44 UTC, neonhuang commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +## 1. 简介
done

2022-01-10 12:44 UTC, neonhuang commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +需要准备 Paddle2ONNX 模型转化环境，和 ONNX 模型预测环境
done

2022-01-10 12:44 UTC, neonhuang commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +- 安装 ONNX
修改了。

2022-01-10 12:44 UTC, neonhuang commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +使用 Paddle2ONNX 将Paddle静态图模型转换为ONNX模型格式：
done

2022-01-10 12:44 UTC, neonhuang commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +执行完毕后，ONNX 模型会被保存在 `./inference/mobilenetv3_model/` 路径下
done

2022-01-10 12:44 UTC, neonhuang commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +表示预测的类别ID是`8`，置信度为`0.909`，该结果与基于训练引擎的结果完全一致
done

2022-01-10 12:44 UTC, neonhuang commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +### 2.3 ONNX 预测
现在按产品的给的一个目录，编排了

2022-01-10 12:44 UTC, neonhuang commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +- Paddle 模型动转静导出
这个名字，源于https://github.com/PaddlePaddle/models/blob/release%2F2.2/docs/tipc/train_infer_python/infer_python.md#22-%E5%87%86%E5%A4%87%E6%8E%A8%E7%90%86%E6%A8%A1%E5%9E%8B

2022-01-10 12:45 UTC, neonhuang commented on tutorials/tipc/paddle2onnx/paddle2onnx.md
> +使用ONNXRuntime测试ONNX模型模型，确保模型精度符合预期
现在统一用ONNXRuntime

2022-01-10 14:00 UTC, littletomatodonkey approved these changes

2022-01-11 01:37 UTC, neonhuang commented on tutorials/mobilenetv3_prod/Step6/deploy/onnx_python/README.md
> +执行完毕后，ONNX 模型会被保存在 `./inference/mobilenetv3_model/` 路径下
修改好了

2022-01-11 01:45 UTC, littletomatodonkey approved these changes

2022-01-11 01:45 UTC, merged