CTR demo
PaddlePaddle/models pull request #57
Opened 2017-05-26 02:52 UTC by Superjom

数据处理部分篇幅太长，单独写了一个markdown文件

generate脚本稍后补充

文档是org mode写的，之后转成.md文件，所以会有 .org的文件，可以用一个单独目录隐藏起来

@lcy-seso

2017-05-26 03:27 UTC, lcy-seso requested changes
关于形式化的初步意见。

2017-05-26 03:27 UTC, lcy-seso commented on ctr/README.org
> +#+title: 使用 Wide & Deep neural model 进行 CTR 预估
未来会将markdown 转为 html，这里删除org  文件吧。

2017-05-26 03:27 UTC, lcy-seso commented on ctr/README.md
> +# 引用
1. 使用二级标题，## 参考文献，目前每一篇里面只保留一个一级标题。
2. 参考文献直接使用数字列表，去掉方括号。在引用文献的地方使用： \[[1](#参考文献)\] 这样的标记。
3. 论文也请附上链接

2017-05-26 03:27 UTC, lcy-seso commented on ctr/README.md
> +![img](./images/lr-vs-dnn.jpg)
图片引用的方式和Paddle其它示例不一致。请阅读：https://github.com/PaddlePaddle/book/wiki/%E4%B8%AD%E6%96%87%E6%95%99%E7%A8%8B%E6%92%B0%E5%86%99%E7%BB%9F%E4%B8%80%E6%A0%87%E5%87%86

2017-05-26 03:27 UTC, lcy-seso commented on ctr/README.md
> +# 数据和任务抽象
每一篇只有一个一级标题，这里修改为二级标题

2017-05-26 03:27 UTC, lcy-seso commented on ctr/README.md
> +
一级标题：#点击率预估，以后各小节为二级，三级等标题。

2017-05-26 03:27 UTC, lcy-seso commented on ctr/README.md
> +CTR(Click-through rate) 是用来表示用户点击一个特定链接的概率，
Click-through rate --> Click-Through Rate

2017-05-26 03:27 UTC, lcy-seso commented on ctr/README.md
> +click = paddle.layer.data(name='click', type=dtype.dense_vector(1))
135~ 136 多余的空行删除

2017-05-26 03:27 UTC, lcy-seso commented on ctr/README.md
> +<a id="orgd78c9ff"></a>
这些标记先从markdown 删除，后面html统一渲染。

2017-05-26 03:27 UTC, lcy-seso commented on ctr/README.md
> +<a id="orgd2cbfbd"></a>
这些标记先从markdown中删除，后面html统一渲染。

2017-05-26 03:27 UTC, lcy-seso commented on ctr/README.md
> +    for no, dim in enumerate(dnn_layer_dims[1:]):
no，重名名为 i,idx,num等吧。

2017-05-26 03:27 UTC, lcy-seso commented on ctr/README.md
> +    return _input_layer
172 ~ 173 多余的空行去掉。

2017-05-26 03:27 UTC, lcy-seso commented on ctr/README.md
> +<a id="orgb4020a9"></a>
这些标记先从markdown中删除，后面html统一渲染。

2017-05-26 03:27 UTC, lcy-seso commented on ctr/README.md
> +optimizer = paddle.optimizer.Momentum(momentum=0)
没有 paddle.init()不会出问题吗？

2017-05-26 03:27 UTC, lcy-seso commented on ctr/dataset.md
> +<a id="orgeaf74d5"></a>
html 标记先去掉吧。

2017-05-26 03:27 UTC, lcy-seso commented on ctr/dataset.org
> +
参考文献作为单独的一节，二级标题。

2017-05-26 03:33 UTC, lcy-seso commented
1. 版本库中目前只保存markdown，和其它项目保持统一，请先删掉 org文件
2. 后续会将markwon 自动转换成html 和 jupyter notebook等形式，尽量使用markdown 原生语法。

2017-05-31 04:51 UTC, lcy-seso requested changes
针对文档的一些修改建议。

2017-05-31 04:51 UTC, lcy-seso commented on ctr/README.md
> +![img](./images/lr-vs-dnn.jpg)
1. 图没有居中
2. 缺少图题
3. 图片的命名统一使用“_”代替“-”和repo中其他例子保持一致。"lr-vs-dnn.jpg" --> "lr_vs_dnn.jpg"
4. 和其它例子保持一致，使用下面的标记：
<p align="center">
<img src="images/lr-vs-dnn.jpg" width = "60%" align="center"/><br/>
Figure 1. ×
</p>

2017-05-31 04:51 UTC, lcy-seso commented on ctr/README.md
> +LR 的蓝色箭头部分可以直接类比到 NN 中对应的结构，可以看到 LR 和 NN 有一些共通之处（比如权重累加），
NN 是不是应该改成 DNN更好一些？

2017-05-31 04:51 UTC, lcy-seso commented on ctr/README.md
> +下图展示了 LR 和一个 \(3x2\) 的 NN 模型的结构：
NN 是不是应该改为DNN更合适一些？因为上文并没有出现 NN 这个术语。

2017-05-31 04:51 UTC, lcy-seso commented on ctr/README.md
> +如果 LR 要达到匹敌 NN 的学习能力，必须增加输入的维度，也就是增加特征的数量，
NN --> DNN。上文提出了DNN，但是没有提到NN。会为阅读者带来困惑。

2017-05-31 04:51 UTC, lcy-seso commented on ctr/README.md
> +2.  Learning to rank, 具体用 pairwise rank（标签 1>0）或者 list rank
list --> listwise

2017-05-31 04:51 UTC, lcy-seso commented on ctr/README.md
> +我们使用 Kaggle 上 `Click-through rate prediction` 任务的数据集[3] 来演示模型。
引用的标记符号请使用以下：
\[[3](#参考文献)\]

2017-05-31 04:51 UTC, lcy-seso commented on ctr/README.md
> +![img](./images/wide-deep.png)
图片的引用标记需要修正，1. 未居中，2. 缺图题， 3. 命名用“_”代替“-”

2017-05-31 04:51 UTC, lcy-seso commented on ctr/README.md
> +模型左边的 Wide 部分，可以容纳大规模系数特征，并且对一些特定的信息（比如 ID）有一定的记忆能力；
笔误：系数 --> 稀疏

2017-05-31 04:51 UTC, lcy-seso commented on ctr/README.md
> +Deep 部分使用了标准的多层前向传导的 NN 模型
NN 还是 DNN，或者两者皆可（那需要引入一下NN这个术语）需要在全文统一一下。

2017-05-31 04:51 UTC, lcy-seso commented on ctr/README.md
> +        # use sigmoid function to approximate ctr rate, a float value between 0 and 1.
a float value between 0 and 1.  --> which outputs a float value between 0 and 1.

2017-05-31 04:51 UTC, lcy-seso commented on ctr/README.md
> +paddle.init(use_gpu=False, trainer_count=11)
trainer_count默认设置为1。

2017-05-31 04:51 UTC, lcy-seso commented on ctr/README.md
> +2. Mikolov T, Deoras A, Povey D, et al. Strategies for training large scale neural network language models[C]//Automatic Speech Recognition and Understanding (ASRU), 2011 IEEE Workshop on. IEEE, 2011
为每一篇论文增加markdown标记的链接，以参考文献2 为例，修改如下：
2. Mikolov T, Deoras A, Povey D, et al. [Strategies for training large scale neural network language models](http://www.aclweb.org/anthology/P16-1186)[C]//Automatic Speech Recognition and Understanding (ASRU), 2011 IEEE Workshop on. IEEE, 2011: 196-201.

2017-05-31 04:51 UTC, lcy-seso commented on ctr/README.md
> +## 引用
统一叫做“参考文献”

2017-05-31 04:51 UTC, lcy-seso commented on ctr/dataset.md
> +
增加二级标题， ##参考文献

2017-05-31 04:51 UTC, lcy-seso commented on ctr/README.md
> +2. Mikolov T, Deoras A, Povey D, et al. Strategies for training large scale neural network language models[C]//Automatic Speech Recognition and Understanding (ASRU), 2011 IEEE Workshop on. IEEE, 2011
文中似乎只有对参考文献3的引用？

2017-05-31 04:51 UTC, lcy-seso commented on ctr/dataset.md
> +上面的方法尽管存在一定的碰撞概率，但能够处理任意数量的 ID 特征，并保留一定的效果[2]。
1. 参考文献的引用格式采用如下标记：\[[2](#参考文献)\]
2. 这一篇只要参考文献1？没有其它？

2017-05-31 04:51 UTC, lcy-seso commented on ctr/dataset.md
> +2.  类似词向量，用一个 Embedding Table 将每个类别映射到对应的向量
Embedding Table --> Embedding

2017-05-31 04:51 UTC, lcy-seso commented on ctr/dataset.md
> +类别型特征有有限多种值，在模型中，我们一般使用 embedding table 将每种值映射为连续值的向量。
Embedding table --> Embedding

2017-05-31 04:51 UTC, lcy-seso commented on ctr/dataset.md
> +
增加一两句描述用户应该如何使用这个类来处理数据呢？

2017-05-31 04:51 UTC, lcy-seso commented on ctr/dataset.md
> +```
增加一两句描述用户应该如何使用这个类来处理数据呢？

2017-05-31 04:51 UTC, lcy-seso commented on ctr/dataset.md
> +```
增加一两句描述用户应该如何使用这个类来处理数据呢。

2017-05-31 04:51 UTC, lcy-seso commented on ctr/dataset.md
> +Deep 和 Wide 两部分均以 `sparse_binary_vector` 的格式[1]输入，输入前需要将相关特征拼合，模型最终只接受 3 个 input，
参考文献的标记请改为：\[[1](#参考文献)\]

2017-05-31 04:56 UTC, Superjom commented on ctr/README.md
> +click = paddle.layer.data(name='click', type=dtype.dense_vector(1))
done

2017-05-31 06:09 UTC, Superjom commented on ctr/dataset.md
> +上面的方法尽管存在一定的碰撞概率，但能够处理任意数量的 ID 特征，并保留一定的效果[2]。
添加了[2]对应的文献

2017-05-31 06:12 UTC, Superjom commented on ctr/dataset.md
> +
done

2017-05-31 06:12 UTC, Superjom commented on ctr/dataset.md
> +```
done

2017-05-31 06:12 UTC, Superjom commented on ctr/dataset.md
> +```
done

2017-05-31 06:12 UTC, Superjom commented on ctr/dataset.md
> +
done

2017-05-31 06:37 UTC, Superjom commented on ctr/README.md
> +paddle.init(use_gpu=False, trainer_count=11)
done

2017-06-01 03:45 UTC, lcy-seso requested changes
关于文档的一些小意见。

2017-06-01 03:45 UTC, lcy-seso commented on ctr/README.md
> +Wide & Deep Learning Model[3] 可以作为一种相对成熟的模型框架使用，
参考文献的引用格式还是不太对。比如这里的3：
```text
\[[3](#参考文献)\]
```

2017-06-01 03:45 UTC, lcy-seso commented on ctr/README.md
> +我们使用 Kaggle 上 `Click-through rate prediction` 任务的数据集[\[2\]](https://www.kaggle.com/c/avazu-ctr-prediction/data) 来演示模型。
参考文献的引用格式还是不太对。比如这里的[2]：
```text
\[[2](#参考文献)\]
```

2017-06-01 03:45 UTC, lcy-seso commented on ctr/README.md
> +CTR(Click-Through Rate)[\[1\]](https://en.wikipedia.org/wiki/Click-through_rate) 是用来表示用户点击一个特定链接的概率，
参考文献的引用格式还是不太对。比如这里的[1]：
```text
\[[1](#参考文献)\]
```

2017-06-01 03:45 UTC, lcy-seso commented on ctr/README.md
> +Figure 1. LR 和DNN模型结构对比
风格保持一致，DNN 前后都增加一个空格。

2017-06-01 03:45 UTC, lcy-seso commented on ctr/README.md
> +我们可以将 `click` 作为学习目标，具体任务可以有以下几种方案：
具体任务可以有以下几种方案： --> 具体的，任务可以有以下几种方案：

2017-06-01 03:45 UTC, lcy-seso commented on ctr/README.md
> +```
1. 增加一个章节：##运行训练和测试
2. 略微做一个简单的，step by step 的描述来解释 clone 了这个repo的用户该如何一步一步执行本例中的这套脚本，例如包括以下内容：
    - 先运行哪个脚本下载数据/准备环境。
    - 运行哪个脚本启动训练任务，是否需要修改某些参数。
    - 告诉用户那个脚本负责读数据，如果需要feed 自己的数据，应该修改哪个脚本。

2017-06-01 03:45 UTC, lcy-seso commented on ctr/dataset.md
> +上面的方法尽管存在一定的碰撞概率，但能够处理任意数量的 ID 特征，并保留一定的效果[2]。
参考文献的标记还是有些问题：
```text
\[[2](#参考文献)\]
```

2017-06-01 03:45 UTC, lcy-seso commented on ctr/dataset.md
> +我们的实验数据集[\[3\]](https://www.kaggle.com/c/avazu-ctr-prediction/data)已经经过shuffle，可以扫描前面一定数目的记录来近似总的类别项集合（等价于随机抽样），
参考文献3 的标记有些问题。
```text
\[[3](#参考文献)\]
```

2017-06-01 06:19 UTC, Superjom commented on ctr/README.md
> +```
done

2017-06-01 06:45 UTC, lcy-seso requested changes
增加一个自动下载数据的脚本。

2017-06-01 06:45 UTC, lcy-seso commented on ctr/README.md
> +1. 下载训练数据，可以使用 Kaggle 上 CTR 比赛的数据\[[2](#参考文献)\]
1. 仿照models下`sequence_tagging_for_ner`在这个例子，增加一个data文件夹，data 文件夹下天机一个获取数据的脚本，https://github.com/PaddlePaddle/models/blob/develop/sequence_tagging_for_ner/data/download.sh
2. train.py增加一个main函数，main函数中指定usage中提到的四个函数的默认参数。
3. 最终效果：用户首先执行下载数据脚本，再执行train.py 可以直接运行训练任务。

2017-06-01 06:51 UTC, lcy-seso commented
Kaggle 的数据集无法通过脚本直接下载。修改一下README，加上一个step by step的过程，如何将原始数据提供给train.py脚本，启动训练任务：
    - 原始数据下载下是什么样的一个文件。
    - 需要做哪些处理？（比如解压）
    - 给 train.py 增加一个默认的main函数，可以直接执行。

2017-06-01 07:47 UTC, reyoung commented
It seems an issue about virtualenv let this Unittest failed.

The related issue is [here](https://github.com/pypa/virtualenv/issues/1053).

2017-06-01 12:28 UTC, lcy-seso approved these changes
LGTM

2017-06-01 12:29 UTC, merged