Caffe2fluid
PaddlePaddle/models pull request #617
Opened 2018-02-01 11:20 UTC by dragonwarrior

add support for converting a caffe-model to fluid-model

2018-02-01 12:42 UTC, qingqing01 commented
和@qiaolongfei讨论了下，觉得使用 https://github.com/ethereon/caffe-tensorflow 里的代码太多，这个tool总共超过10000行，可否：

1. 直把和Paddle相关的代码Merge到 models repo ？
2.  可否git clone  https://github.com/ethereon/caffe-tensorflow , 在文档里写明白用法？

或者其他更好的方案也行，也欢迎其他同学提供建议~

2018-02-02 01:49 UTC, dragonwarrior commented
好的，我稍微精简下代码

2018-03-02 07:54 UTC, qingqing01 approved these changes
Approve the first version.

2018-03-02 08:01 UTC, qingqing01 requested changes

2018-03-02 08:01 UTC, qingqing01 commented on fluid/image_classification/caffe2fluid/README.md
> +    this tool is used to convert a caffe-model to paddle-model(fluid api)
这里可以不缩进。

this tool -> This tool xxx .
caffe-mode -> Caffe model
paddle-model -> Fludi model.

Remove fluid api.

2018-03-02 08:01 UTC, qingqing01 commented on fluid/image_classification/caffe2fluid/README.md
> +### caffe2fluid
caffe2fluid -> Caffe2Fluid

2018-03-02 08:01 UTC, qingqing01 commented on fluid/image_classification/caffe2fluid/README.md
> +    (see more detail info in 'tests/lenet/README.md')
整体不用缩进。

2018-03-02 08:01 UTC, qingqing01 commented on fluid/image_classification/caffe2fluid/README.md
> +    1, prepare caffepb.py in ./proto, two options provided
1, prepare  -> 1. Prepare 
后面相同，首字母都大写吧。

2018-03-02 08:01 UTC, qingqing01 commented on fluid/image_classification/caffe2fluid/README.md
> +        option2: download one from github directly
option 1 -> 1). 
 option2 -> 2).

2018-03-02 08:01 UTC, qingqing01 commented on fluid/image_classification/caffe2fluid/README.md
> +### howto
howto  -> HowTo

2018-03-02 08:01 UTC, qingqing01 commented on fluid/image_classification/caffe2fluid/README.md
> +    some of this code come from here: https://github.com/ethereon/caffe-tensorflow
不需要缩进，line 20, line 22相同。首字母大写。

2018-03-02 08:01 UTC, qingqing01 commented on fluid/image_classification/caffe2fluid/README.md
> +### supported models
supported models -> Supported Models

2018-03-02 08:01 UTC, qingqing01 commented on fluid/image_classification/caffe2fluid/README.md
> +    lenet on mnist dataset
lenet -> LeNet
resnets->ResNets 
resnet50 -> ResNet 50

2018-03-02 08:12 UTC, dragonwarrior commented on fluid/image_classification/caffe2fluid/README.md
> +    this tool is used to convert a caffe-model to paddle-model(fluid api)
done

2018-03-02 08:12 UTC, dragonwarrior commented on fluid/image_classification/caffe2fluid/README.md
> +### caffe2fluid
done

2018-03-02 08:14 UTC, dragonwarrior commented on fluid/image_classification/caffe2fluid/README.md
> +    (see more detail info in 'tests/lenet/README.md')
done

2018-03-02 08:16 UTC, dragonwarrior commented on fluid/image_classification/caffe2fluid/README.md
> +    1, prepare caffepb.py in ./proto, two options provided
done

2018-03-02 08:16 UTC, dragonwarrior commented on fluid/image_classification/caffe2fluid/README.md
> +        option2: download one from github directly
done

2018-03-02 08:16 UTC, dragonwarrior commented on fluid/image_classification/caffe2fluid/README.md
> +    some of this code come from here: https://github.com/ethereon/caffe-tensorflow
done

2018-03-02 08:17 UTC, dragonwarrior commented on fluid/image_classification/caffe2fluid/README.md
> +### supported models
done

2018-03-02 08:18 UTC, dragonwarrior commented on fluid/image_classification/caffe2fluid/README.md
> +    lenet on mnist dataset
done

2018-03-02 08:38 UTC, qingqing01 approved these changes

2018-03-02 10:33 UTC, merged