ctc init
PaddlePaddle/models pull request #63
Opened 2017-06-02 07:16 UTC by Superjom

出现 gpu allocate 多次的问题

2017-06-04 10:20 UTC, qingqing01 commented on ctc/model.py
> +    block_y=3)
依据 https://github.com/PaddlePaddle/Paddle/issues/2296  这里看conv_features的 输出的特征c=128, h=11, w=3， block_y应该是11，估计这块设置不对，导致了GPU内存问题，以及issues #2296 的问题。

2017-06-06 02:00 UTC, Superjom commented
训练的配置写好了，基本可以 PR 了。
训练效果和生成的配置准备下次 pull 加进去 @qingqing01

2017-07-04 08:53 UTC, qingqing01 requested changes
另外，需要infer过程。

2017-07-04 08:53 UTC, qingqing01 commented on ctc/README.md
> +现实世界中的序列学习任务需要从连续的输入序列中预测出对应标签序列，
> 序列学习任务需要从连续的输入序列中预测出对应标签序列

连续的输入准确吗？ 机器翻译的输入不连续吧？

2017-07-04 08:53 UTC, qingqing01 commented on ctc/README.md
> +比如语音识别任务从连续的语音中得到对应文字序列，类似于seq2seq任务；
`seq2seq任务`如果是个专有名字需要加链接。

2017-07-04 08:53 UTC, qingqing01 commented on ctc/README.md
> +CTC 算法在很多领域中有应用，比如手写数字识别、语音识别、手势识别、连续图像文字识别等，除去不同任务中的专业知识不同，
连续图像文字识别不够准确。

2017-07-04 08:53 UTC, qingqing01 commented on ctc/README.md
> +本文将针对 **场景文字识别 (STR, Scene Text Recognition)** 任务，演示如何用 PaddlePaddle 实现 一个一站式 CTC 的模型 **CRNN(Convolutional Recurrent Neural Network)**
一站式 -> 端到端

2017-07-04 08:53 UTC, qingqing01 commented on ctc/README.md
> +本文将针对 **场景文字识别 (STR, Scene Text Recognition)** 任务，演示如何用 PaddlePaddle 实现 一个一站式 CTC 的模型 **CRNN(Convolutional Recurrent Neural Network)**
需要提下OCR，解释下和STR的区别？

2017-07-04 08:53 UTC, qingqing01 commented on ctc/README.md
> +1. 一站式训练，直接从原始数据到目标标签序列学习
一站式 -> 端到端

2017-07-04 08:53 UTC, qingqing01 commented on ctc/README.md
> +2. 不同于很多其他的算法，其输入图片不需要固定尺寸
> 不需要固定尺寸
这块准确吗？

2017-07-04 08:53 UTC, qingqing01 commented on ctc/README.md
> +1. `layer.warp_ctc` 调用 `warp CTC` 实现 CTC layer.
需要说明下warp_ctc用于GPU，CPU训练用啥，同时代码中需要支持CPU模式。

2017-07-04 08:53 UTC, qingqing01 commented on ctc/README.md
> +-   Convolutional Layers, 自动提取图像特征；最终会产生一个矩形的图像映射，可以拆分成图像特征序列
一个矩形的图像映射 ->  一个三维的图像特征映射

2017-07-04 08:53 UTC, qingqing01 commented on ctc/README.md
> +为了能够兼容对不同尺寸的图片，比如下面 Figure 3中的两张图片，将其高度固定，就变成了长度不相同的图片。
长度 -> 宽度

2017-07-04 08:53 UTC, qingqing01 commented on ctc/README.md
> +Figure 2. CTC模型结构
图片太大，如果不是原图，需要加上引用。

2017-07-04 08:53 UTC, qingqing01 commented on ctc/README.md
> +不同于经典NMT(Neural Machine Translation)中使用的beamsearch算法，CTC layer不会考虑已经生成的标签上文的信息，只考虑当前时间步生成某个标签的概率。
beamsearch -> beam search，并加参考链接。

2017-07-04 08:53 UTC, qingqing01 commented on ctc/README.md
> +        self.chars = [chr(i) for i in range(40, 171)]
为啥是(40, 171)范围？

2017-07-04 08:53 UTC, qingqing01 commented on ctc/README.org
> +#+title: CTC (Connectionist temporal classification) 模型介绍
README.org如果不要就去掉。

2017-07-04 08:53 UTC, qingqing01 commented on ctc/model.py
> +def ctc_convs(input_image, num, with_bn):
`ctc_convs`里没有ctc，可以换个名字，`conv_groups` ?

2017-07-04 08:53 UTC, qingqing01 commented on ctc/README.md
> +论文中具体使用的RNN算法是LSTM（Long-Short Term Memory）, 此模型应用比较广泛，本教程中不再赘述。
下面代码是GRU，不是LSTM。

2017-07-04 08:53 UTC, qingqing01 commented on ctc/model.py
> +            blank=self.num_classes)
还有个`ctc_error_evaluator`可以加上。

2017-07-04 08:53 UTC, qingqing01 commented on ctc/train.py
> +    cost=model.cost, parameters=params, update_equation=optimizer)
`momentum=0`是实际验证过的嘛？

2017-07-04 08:53 UTC, qingqing01 commented on ctc/data_provider.py
> +    image_file_list = '/home/disk1/yanchunwei/90kDICT32px/train_all.txt'
这个脚本需要有下载数据的过程，这个路径可以换成下载之后的路径。

2017-07-04 08:53 UTC, qingqing01 commented on ctc/README.md
> +```python
这块不用粘贴这么多代码，告诉用户是在哪个脚本和函数即可。

2017-07-04 08:53 UTC, qingqing01 commented on ctc/data_provider.py
> +        # image = to_chw(image)
# image = to_chw(image) 
注释的代码去掉。

2017-07-04 08:53 UTC, qingqing01 commented on ctr/model.py
> +#!/usr/bin/env python
CTR和DSSM部分代码和文档可以从这个PR里去掉吗？

2017-07-04 08:53 UTC, qingqing01 commented on ctc/train.py
> +        paddle.reader.shuffle(dataset.train, buf_size=100),
buf_size可以增大点，加大shuffle范围吧。

2017-07-05 01:37 UTC, Superjom commented on ctc/README.md
> +现实世界中的序列学习任务需要从连续的输入序列中预测出对应标签序列，
done

2018-03-06 03:16 UTC, closed without merging