Add an example of NER task in fluid style. For issue #644
PaddlePaddle/models pull request #689
Opened 2018-03-06 08:27 UTC by jshower

We add an example of NER task in fluid style. The model structure is similar with its V2 version. Finish issue #644

2018-03-09 06:30 UTC, guoshengCS commented on fluid/sequence_tagging_for_ner/README.md
> +# 命名实体识别
如果和原来v2示例的内容相同的话，建议删掉。其他一些数据和脚本文件类似。可以说明参考原先的内容。

2018-03-09 06:30 UTC, guoshengCS commented on fluid/sequence_tagging_for_ner/network_conf.py
> +            loc=0.0, scale=(1. / math.sqrt(hidden_dim) / 3), seed=0),
initializer里的seed不要固定了吧。

2018-03-09 06:30 UTC, guoshengCS commented on fluid/sequence_tagging_for_ner/network_conf.py
> +import math
请参照 https://www.python.org/dev/peps/pep-0008/#imports 调整下import的顺序并合适的加入空行。
```
Imports should be grouped in the following order:

standard library imports
related third party imports
local application/library specific imports
You should put a blank line between each group of imports.
```

2018-03-09 06:30 UTC, guoshengCS commented on fluid/sequence_tagging_for_ner/train.py
> +import numpy as np
请参照 https://www.python.org/dev/peps/pep-0008/#imports 调整下import的顺序并合适的加入空行。
```
Imports should be grouped in the following order:

standard library imports
related third party imports
local application/library specific imports
You should put a blank line between each group of imports.
```

2018-03-09 06:30 UTC, guoshengCS commented on fluid/sequence_tagging_for_ner/train.py
> +        pass_precision, pass_recall, pass_f1_score = test(
训练数据在`chunk_evaluator.reset()`之后的accumulated metrics，是可以通过`chunk_evaluator.eval()`获得的，不用另行运行test程序。可以参考 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/book/test_label_semantic_roles.py#L222

2018-03-09 06:30 UTC, guoshengCS commented on fluid/sequence_tagging_for_ner/train.py
> +
`model_save_dir `没有使用，请加上模型保存的代码，可以参考这里 https://github.com/PaddlePaddle/models/blob/develop/fluid/DeepASR/train.py#L246

2018-03-09 06:34 UTC, guoshengCS commented
也请加上infer.py和inference的代码，可以参考 https://github.com/PaddlePaddle/models/blob/develop/fluid/DeepASR/infer.py

也请加上GPU支持和多卡/多线程代码，可以参考 https://github.com/PaddlePaddle/models/blob/develop/fluid/DeepASR/model_utils/model.py#L85

另外收敛行和学习效果是否方便验证和提供下。辛苦

2018-03-13 12:46 UTC, jshower commented
修复了上面提到的没有保存模型，缺少infer.py，缺少并行与gpu/cpu选择，import格式不规范等问题。有些文件与原来的V2示例比较相似，但是细节内容上还是有较多差别，为了方便用户的直接使用，还是选择了保留。

2018-03-13 13:15 UTC, jshower commented
在增加这个模型的多线程版本时，遇到了一个问题，应该是paddle的多线程在特定情况下的一个bug，提了ISSUE，请关注 https://github.com/PaddlePaddle/models/issues/732

2018-03-16 02:38 UTC, guoshengCS commented on fluid/sequence_tagging_for_ner/README.md
> +   标记标签词典已附在`data`目录中，对应于`data/target.txt`文件。输入文本的词典以及词典中词语的预训练的词向量来自：[Stanford CS224d](http://cs224d.stanford.edu/)课程作业。**为运行本例，请首先在`data`目录下运行`download.sh`脚本下载输入文本的词典和预训练的词向量。** 完成后会将这两个文件一并放入`data
请去掉这个`data/vocab.txt`文件，`download.sh`会下载这个词典文件。

2018-03-16 02:38 UTC, guoshengCS commented on fluid/sequence_tagging_for_ner/README.md
> +extended        O       O
请确认并更正下这里的格式。
![image](https://user-images.githubusercontent.com/14105589/37461827-b6001560-288a-11e8-8176-35ec9d9959a5.png)

2018-03-16 02:38 UTC, guoshengCS commented on fluid/sequence_tagging_for_ner/train.py
> +    #place = fluid.CPUPlace()
请去掉注释掉的这一行。

2018-03-16 02:38 UTC, guoshengCS commented on fluid/sequence_tagging_for_ner/README.md
> +
看到`main`函数已经有所修改，请结合新的代码修改下这里的内容。

2018-03-16 02:38 UTC, guoshengCS commented on fluid/sequence_tagging_for_ner/infer.py
> +from utils import load_dict, load_reverse_dict
请和其他文件一样规范下这里import的格式。

2018-03-16 02:38 UTC, guoshengCS commented on fluid/sequence_tagging_for_ner/infer.py
> +        target_file="data/target.txt")
也请为infer加上GPU支持，并相应的调整README中对应的infer部分的内容。

2018-03-16 02:38 UTC, guoshengCS commented on fluid/sequence_tagging_for_ner/train.py
> +        fluid.io.save_inference_model(save_dirname, ['word', 'mark', 'target'],
建议save_inference_model时请不要加入target。

2018-03-16 02:38 UTC, guoshengCS commented on fluid/sequence_tagging_for_ner/infer.py
> +        name='target', shape=[1], dtype='int64', lod_level=1)
请去掉这三个data layer，这三个data layer应该是没有作用的，是加到`default_main_program`里的，而后面`fluid.io.load_inference_model`会返回新的Program对象`inference_program `，executor运行的是这个`inference_program `.

2018-03-16 02:42 UTC, guoshengCS commented
另外push新代码的时候请在每条comment下面简单回复下Done方便知道哪些上次comment的内容修改了，这也是需要养成的习惯，能够提高review的效率。辛苦

2018-03-19 02:58 UTC, jshower commented on fluid/sequence_tagging_for_ner/README.md
> +   标记标签词典已附在`data`目录中，对应于`data/target.txt`文件。输入文本的词典以及词典中词语的预训练的词向量来自：[Stanford CS224d](http://cs224d.stanford.edu/)课程作业。**为运行本例，请首先在`data`目录下运行`download.sh`脚本下载输入文本的词典和预训练的词向量。** 完成后会将这两个文件一并放入`data
好的，已删除

2018-03-19 03:03 UTC, jshower commented on fluid/sequence_tagging_for_ner/README.md
> +extended        O       O
格式确实是分成三列，三列分别是输入的词语，标准标签，生成的标签，以制表符分割，在提交的时候制表符会被替换成四个空格，但是实际产出时确实是以制表符分割。

2018-03-19 03:04 UTC, jshower commented on fluid/sequence_tagging_for_ner/train.py
> +    #place = fluid.CPUPlace()
已删除

2018-03-19 03:04 UTC, jshower commented on fluid/sequence_tagging_for_ner/README.md
> +
已修改

2018-03-19 03:05 UTC, jshower commented on fluid/sequence_tagging_for_ner/infer.py
> +from utils import load_dict, load_reverse_dict
已规范

2018-03-19 03:06 UTC, jshower commented on fluid/sequence_tagging_for_ner/infer.py
> +        target_file="data/target.txt")
已添加和调整

2018-03-19 03:14 UTC, jshower commented on fluid/sequence_tagging_for_ner/train.py
> +        fluid.io.save_inference_model(save_dirname, ['word', 'mark', 'target'],
在不添加target时，使用多线程模式训练的模型，保存后再次被load时运行会出错。这应该是因为多线程时，在parallel_do中的linear_chain_crf使用到了target，后续在预测时，虽然我们要获得的crf_decode并不需要target，但是程序仍然会报缺少target的错误。在单线程时则不会出现类似情况。考虑到程序的稳定性，并且增加一个target实际上并不会给使用者带来太大麻烦和开销，所以还是保留了target。

2018-03-19 03:14 UTC, jshower commented on fluid/sequence_tagging_for_ner/infer.py
> +        name='target', shape=[1], dtype='int64', lod_level=1)
已删除。

2018-03-19 03:16 UTC, jshower commented on fluid/sequence_tagging_for_ner/README.md
> +# 命名实体识别
内容上还是存在着一些差别，为了方便读者使用，还是予以保留了。

2018-03-19 03:16 UTC, jshower commented on fluid/sequence_tagging_for_ner/network_conf.py
> +            loc=0.0, scale=(1. / math.sqrt(hidden_dim) / 3), seed=0),
已删除。

2018-03-19 03:17 UTC, jshower commented on fluid/sequence_tagging_for_ner/network_conf.py
> +import math
已调整

2018-03-19 03:17 UTC, jshower commented on fluid/sequence_tagging_for_ner/train.py
> +import numpy as np
已调整

2018-03-19 03:17 UTC, jshower commented on fluid/sequence_tagging_for_ner/train.py
> +        pass_precision, pass_recall, pass_f1_score = test(
已修改

2018-03-19 03:17 UTC, jshower commented on fluid/sequence_tagging_for_ner/train.py
> +
已修改。

2018-03-19 03:21 UTC, jshower commented
已按照要求进行了修改和回复。辛苦再次确认是否可以approve。谢谢~

2018-03-19 09:13 UTC, lcy-seso requested changes
请不要merge 重复代码。保持目录结构，复用已有代码。

2018-03-19 09:13 UTC, lcy-seso commented on fluid/sequence_tagging_for_ner/README.md
> +# 命名实体识别
README里面重复内容太多，Github上面官方repo 如果背景介绍部分的文字完全相同，不可以直接Copy。
文字完全相同的部分请添加链接。不能直接复制。

2018-03-19 09:13 UTC, lcy-seso commented on fluid/sequence_tagging_for_ner/README.md
> +```
148 ~ 173行markdown缩进有问题，请加上缩进。

2018-03-19 09:13 UTC, lcy-seso commented on fluid/sequence_tagging_for_ner/README.md
> +## 真实结果示例
去掉“真实”

2018-03-19 09:13 UTC, lcy-seso commented on fluid/sequence_tagging_for_ner/README.md
> +<img src="imgs/convergent_curve.png" width="80%" align="center"/><br/>
请将 “convergent_curve” 修改为 “convergence_curve”。

2018-03-19 09:13 UTC, lcy-seso commented on fluid/sequence_tagging_for_ner/README.md
> +图1. Fluid下实验结果示例
1. 请将图注修改为：学习曲线
1. 请重绘以下这幅图，有以下问题：
    - x轴和y轴请标注分别代表什么含义。
    - x轴和y轴的标注字体太小，看不清。
    - 蓝色曲线的文字图注字体看不清楚。
    - 图注请不要出现Fluid。

2018-03-19 09:13 UTC, lcy-seso commented on fluid/sequence_tagging_for_ner/data/download.sh
> +if [ -f assignment2.zip ]; then
这部分代码和v2 https://github.com/PaddlePaddle/models/tree/develop/sequence_tagging_for_ner/data 完全相同。代码库中，请不要merge相同的代码。

1. 或者在README中增加一节，专门说明如果下载准备数目。
1. 或者维持当前目录结构，执行 https://github.com/PaddlePaddle/models/tree/develop/sequence_tagging_for_ner/data 下的download.sh脚本。

2018-03-19 09:13 UTC, lcy-seso commented on fluid/sequence_tagging_for_ner/data/target.txt
> +B-LOC
当前data 目录下的数据和脚本和  https://github.com/PaddlePaddle/models/tree/develop/sequence_tagging_for_ner/data 目录下内容完全相同。请删掉重复代码和数据。

2018-03-19 09:13 UTC, lcy-seso commented on fluid/sequence_tagging_for_ner/data/test
> +- : O O
当前data 目录下的数据和脚本和 https://github.com/PaddlePaddle/models/tree/develop/sequence_tagging_for_ner/data 目录下内容完全相同。请删掉重复代码和数据。

2018-03-19 09:13 UTC, lcy-seso commented on fluid/sequence_tagging_for_ner/data/train
> +EU NNP I-NP I-ORG
当前data 目录下的数据和脚本和 https://github.com/PaddlePaddle/models/tree/develop/sequence_tagging_for_ner/data 目录下内容完全相同。请删掉重复代码和数据。

2018-03-19 09:13 UTC, lcy-seso commented on fluid/sequence_tagging_for_ner/infer.py
> +import numpy as np
line 1 之后空一行。

2018-03-19 09:13 UTC, lcy-seso commented on fluid/sequence_tagging_for_ner/reader.py
> +"""
重复代码不可以merge。请保持目录结构，使用相对路径引用。

2018-03-19 09:13 UTC, lcy-seso commented on fluid/sequence_tagging_for_ner/train.py
> +import paddle.v2 as paddle
line 3 和 line 4 交换。

2018-03-19 09:13 UTC, lcy-seso commented on fluid/sequence_tagging_for_ner/utils.py
> +# -*- coding: utf-8 -*-
line1 可以删掉。

重复代码请不要merge。保持目录结构，重用已有代码。

2018-03-19 09:13 UTC, lcy-seso commented on fluid/sequence_tagging_for_ner/infer.py
> +          use_gpu):
请为这个函数添加docstring，风格可以参考reader.py中的注释风格。

2018-03-20 06:11 UTC, jshower commented on fluid/sequence_tagging_for_ner/README.md
> +```
已修改

2018-03-20 06:12 UTC, jshower commented on fluid/sequence_tagging_for_ner/README.md
> +## 真实结果示例
已修改

2018-03-20 06:12 UTC, jshower commented on fluid/sequence_tagging_for_ner/README.md
> +<img src="imgs/convergent_curve.png" width="80%" align="center"/><br/>
已修改

2018-03-20 06:13 UTC, jshower commented on fluid/sequence_tagging_for_ner/README.md
> +图1. Fluid下实验结果示例
已修改

2018-03-20 06:13 UTC, jshower commented on fluid/sequence_tagging_for_ner/data/download.sh
> +if [ -f assignment2.zip ]; then
已删除data目录，在README.md目录里说明下载方式。

2018-03-20 06:14 UTC, jshower commented on fluid/sequence_tagging_for_ner/data/target.txt
> +B-LOC
已删除

2018-03-20 06:14 UTC, jshower commented on fluid/sequence_tagging_for_ner/data/test
> +- : O O
已删除

2018-03-20 06:14 UTC, jshower commented on fluid/sequence_tagging_for_ner/data/train
> +EU NNP I-NP I-ORG
已删除

2018-03-20 06:14 UTC, jshower commented on fluid/sequence_tagging_for_ner/infer.py
> +import numpy as np
已修改

2018-03-20 06:16 UTC, jshower commented on fluid/sequence_tagging_for_ner/reader.py
> +"""
已删除改文件，在README.md里注明了获取的方式。

2018-03-20 06:16 UTC, jshower commented on fluid/sequence_tagging_for_ner/train.py
> +import paddle.v2 as paddle
已修改

2018-03-20 06:17 UTC, jshower commented on fluid/sequence_tagging_for_ner/utils.py
> +# -*- coding: utf-8 -*-
已删除该文件，在README.md中注明了获取的方式，将与之前不同的函数及新增的函数创建了一个utils_extend.py文件

2018-03-20 06:17 UTC, jshower commented on fluid/sequence_tagging_for_ner/infer.py
> +          use_gpu):
已添加

2018-03-20 06:18 UTC, jshower commented
已将上面提到的问题进行了修改，请确认是否可以合入，谢谢！

2018-03-21 00:20 UTC, lcy-seso commented on fluid/sequence_tagging_for_ner/README.md
> +参照https://github.com/PaddlePaddle/models/blob/develop/sequence_tagging_for_ner/README.md中的数据获取方式，将获取的data目录复制到本目录下。
1. 这里可以试着自己在网页端预览，可以看到由于没有空格连接展示有问题。
尽量不要直接贴URL地址，请使用markdown超链接标注方式。

1. 请参考PaddlePaddle v2版本[命名实体识别](http://www.paddlepaddle.org/docs/develop/models/sequence_tagging_for_ner/README.html) 一节中数据获取方式，将该例中的[data](https://github.com/PaddlePaddle/models/tree/develop/sequence_tagging_for_ner/data)文件夹拷贝至本例目录下，运行其中的[download.sh](https://github.com/PaddlePaddle/models/blob/develop/sequence_tagging_for_ner/data/download.sh)脚本获取训练和测试数据。

1. line 28行请同样修改。不要直接贴链接。请加上必要的描述和说明。

2018-03-21 00:20 UTC, lcy-seso commented on fluid/sequence_tagging_for_ner/README.md
> +本例需要使用https://github.com/PaddlePaddle/models/blob/develop/sequence_tagging_for_ner/reader.py以及https://github.com/PaddlePaddle/models/blob/develop/sequence_tagging_for_ner/utils.py，请将这两个文件复制到本目录下。
请按照上一条comment进行修改。

2018-03-21 06:46 UTC, jshower commented on fluid/sequence_tagging_for_ner/README.md
> +参照https://github.com/PaddlePaddle/models/blob/develop/sequence_tagging_for_ner/README.md中的数据获取方式，将获取的data目录复制到本目录下。
已修改

2018-03-21 06:46 UTC, jshower commented on fluid/sequence_tagging_for_ner/README.md
> +本例需要使用https://github.com/PaddlePaddle/models/blob/develop/sequence_tagging_for_ner/reader.py以及https://github.com/PaddlePaddle/models/blob/develop/sequence_tagging_for_ner/utils.py，请将这两个文件复制到本目录下。
已修改。

2018-03-21 06:47 UTC, jshower commented
已按照要求修改，辛苦在review一下是否可以合入。谢谢！

2018-03-21 08:04 UTC, lcy-seso approved these changes
LGTM.

2018-03-21 08:05 UTC, merged