Add loading model function for train.py.
PaddlePaddle/models pull request #72
Opened 2017-06-05 13:01 UTC by pkuyym

fix #2372

2017-06-07 10:16 UTC, xinghai-sun requested changes
Good. Thanks.

2017-06-07 10:16 UTC, xinghai-sun commented on deep_speech_2/train.py
> +    default='models/params.tar.gz',
Set default  to None (training from scratch).

2017-06-07 10:16 UTC, xinghai-sun commented on deep_speech_2/train.py
> +    help="Model path for initialization. (default: %(default)s)")
Add e.g. "If set None, the training will start from scratch. Otherwise, the training will resume from the existing model of this path".

2017-06-07 10:16 UTC, xinghai-sun commented on deep_speech_2/train.py
> +        assert os.path.isfile(args.init_model_path), "Invalid model."
It would be better to use "raise IOError" ?

2017-06-07 11:12 UTC, pkuyym commented on deep_speech_2/train.py
> +    default='models/params.tar.gz',
Done.

2017-06-07 11:12 UTC, pkuyym commented on deep_speech_2/train.py
> +    help="Model path for initialization. (default: %(default)s)")
Done.

2017-06-07 11:12 UTC, pkuyym commented on deep_speech_2/train.py
> +        assert os.path.isfile(args.init_model_path), "Invalid model."
Agree and done.

2017-06-08 06:06 UTC, xinghai-sun approved these changes
LGTM

2017-06-08 06:08 UTC, merged