readme 翻译
PaddlePaddle/models pull request #814
Opened 2018-04-05 18:45 UTC by vienous

translate into English

2018-04-09 02:27 UTC, shanyi15 commented
您好
CI测试未通过，失败原因
Trim Trailing Whitespace.................................................Failed
请参考[翻译常见问题](https://shimo.im/docs/zMRNcbMM3jA58ZJg)的第5个问题尝试解决，谢谢！

2018-04-09 02:46 UTC, shanyi15 reviewed
请先修改格式以通过CI测试，然后根据现有的意见修改，谢谢！

2018-04-09 02:46 UTC, shanyi15 commented on scheduled_sampling/READMD.en.md
> +
文件名写错，应为README.en.md

2018-04-09 02:46 UTC, shanyi15 commented on scheduled_sampling/READMD.en.md
> +Run these examples of programs in this directory require PaddlePaddle v0.10.0 . If your PaddlePaddle installation is lower than this requirement, please follow the instructions in the [installation d
关于版本信息，这里有一个参考："The program under this directory depends on PaddlePaddle v0.10.0 or upper. update it following this instruction if your PaddlePaddle version is lower."

2018-04-09 02:46 UTC, shanyi15 commented on scheduled_sampling/READMD.en.md
> +<img src="images/decay.jpg" width="50%" align="center"><br>
这里请将图片换成英文版的，并重新上传一份英文版图片配到文档里，路径同中文版图片。

2018-04-09 02:46 UTC, shanyi15 commented on scheduled_sampling/READMD.en.md
> +
It can be seen, i要小写，而且seen 后面最好加一个that

2018-04-09 07:21 UTC, shanyi15 commented
您好，之前几个还是同一个问题CI挂了，建议用sublime编辑器，我最近提的几个文档，都是亲测可行的
https://shimo.im/docs/zMRNcbMM3jA58ZJg
这里第5个问题的第2个方法

2018-04-09 07:28 UTC, shanyi15 commented
reviewer please note that: before you merge, please select squash and merge to simplify blog.

2018-04-09 08:34 UTC, vienous commented
最后一个可以了啊，我用的第一个方法

2018-04-10 17:29 UTC, abhinavarora requested changes

2018-04-10 17:29 UTC, abhinavarora commented on scheduled_sampling/README.en.md
> +The program under this directory depends on PaddlePaddle v0.10.0 or upper. update it following this [instruction](http://www.paddlepaddle.org/docs/develop/documentation/zh/build_and_install/pip_insta
update it following this [instruction] -> In order to update it, follow these instructions

2018-04-10 17:29 UTC, abhinavarora commented on scheduled_sampling/README.en.md
> +The generate target of sequence generate task is to maximize the probability of target sequence when a given source is input. During the training, the model input real elements as decoders to each st
generate target -> **generated** target

2018-04-10 17:29 UTC, abhinavarora commented on scheduled_sampling/README.en.md
> +The generate target of sequence generate task is to maximize the probability of target sequence when a given source is input. During the training, the model input real elements as decoders to each st
sequence generate task -> sequence **generation** task

2018-04-10 17:29 UTC, abhinavarora commented on scheduled_sampling/README.en.md
> +The generate target of sequence generate task is to maximize the probability of target sequence when a given source is input. During the training, the model input real elements as decoders to each st
During **the** training, -> During training,

2018-04-10 17:29 UTC, abhinavarora commented on scheduled_sampling/README.en.md
> +The generate target of sequence generate task is to maximize the probability of target sequence when a given source is input. During the training, the model input real elements as decoders to each st
maximize -> maximizes

2018-04-10 17:29 UTC, abhinavarora commented on scheduled_sampling/README.en.md
> +The generate target of sequence generate task is to maximize the probability of target sequence when a given source is input. During the training, the model input real elements as decoders to each st
current input, consequently generate the next element. -> current input to consequently generate the next element.

2018-04-10 17:29 UTC, abhinavarora commented on scheduled_sampling/README.en.md
> +The generate target of sequence generate task is to maximize the probability of target sequence when a given source is input. During the training, the model input real elements as decoders to each st
that probability distribution  ->  that **the** probability distribution

2018-04-10 17:29 UTC, abhinavarora commented on scheduled_sampling/README.en.md
> +Scheduled Sampling \[[1](#参考文献)\] is a method to solve the inconsistent distribution of input data during training and generation.In the early stage of training, this method mainly uses the real elem
generation.In -> generation. In

2018-04-10 17:29 UTC, abhinavarora commented on scheduled_sampling/README.en.md
> +Scheduled Sampling \[[1](#参考文献)\] is a method to solve the inconsistent distribution of input data during training and generation.In the early stage of training, this method mainly uses the real elem
stage -> **stages**

2018-04-10 17:31 UTC, abhinavarora requested changes

2018-04-10 17:31 UTC, abhinavarora commented on scheduled_sampling/README.en.md
> +In the process from a standard sequence to a sequence model, if an incorrect element is created in the preceding part of the sequence , the subsequent input state will be affected, and the error will
forwards -> **forward**

2018-04-10 17:31 UTC, abhinavarora commented on scheduled_sampling/README.en.md
> +Scheduled Sampling is mainly used in the training stage from sequence to sequence model.But It doesn't require Scheduled Sampling in  generation phrase
model.But -> model. But

2018-04-11 00:40 UTC, shanyi15 commented
@vienous please polish this doc according to the reviewer's suggestion, thank you!

2018-06-01 07:22 UTC, skylarch commented
To make things easier for you, I made a separate pull request with the reviewed version of the translation. Please close this pull request, and thanks for your contributions.

2018-06-01 07:23 UTC, closed without merging