Add error rate calculation script.
PaddlePaddle/models pull request #82
Opened 2017-06-08 09:22 UTC by pkuyym

resolves #81

2017-06-08 11:03 UTC, kuke commented on deep_speech_2/error_rate.py
> +    distance = distance.reshape((ref_len + 1, hyp_len + 1))
Above two lines can be merged into one line
```
distance = np.zeros((ref_len + 1, hyp_len + 1), dtype=np.int64)
```

2017-06-08 11:08 UTC, kuke commented on deep_speech_2/error_rate.py
> +    in speech recognition. It compares a reference to an hypophysis and
compare...to...: 将比作. compare with?.

2017-06-08 11:21 UTC, kuke reviewed
Almost LGTM

2017-06-08 11:21 UTC, kuke commented on deep_speech_2/error_rate.py
> +    will be squeezed to one
Would it be better to add and indent in line 114? The same below

2017-06-08 11:21 UTC, kuke commented on deep_speech_2/error_rate.py
> +    :param ignore_case: Whether ignoring character case.
Whether case-sensitive or not

2017-06-08 11:21 UTC, kuke commented on deep_speech_2/error_rate.py
> +    in speech recognition. It compares a reference to an hypophysis and
compare to --> compare with?

2017-06-08 11:21 UTC, kuke commented on deep_speech_2/error_rate.py
> +    distance = distance.reshape((ref_len + 1, hyp_len + 1))
Above two lines can be merged into one line
```
distance = np.zeros((ref_len + 1, hyp_len + 1), dtype=np.int64)
```

2017-06-08 11:21 UTC, kuke commented on deep_speech_2/error_rate.py
> +    We can use levenshtein distance to calculate WER. Take an attention that
Seems there is no "take an attention", but pay/draw ...

2017-06-08 13:35 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    in speech recognition. It compares a reference to an hypophysis and
Done.

2017-06-08 13:35 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    distance = distance.reshape((ref_len + 1, hyp_len + 1))
Done.

2017-06-08 13:35 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    We can use levenshtein distance to calculate WER. Take an attention that
Done.

2017-06-08 13:35 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    will be squeezed to one
Done.

2017-06-08 13:35 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    :param ignore_case: Whether ignoring character case.
Done.

2017-06-08 13:52 UTC, qingqing01 commented
比较通用的代码可以放到paddle的repo里吧~

2017-06-11 13:06 UTC, xinghai-sun requested changes

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +def wer(reference, hypophysis, delimiter=' ', filter_none=True):
1. "hypophysis" or "hypothesis"?
2. Why not provide a ignore_case argument, just as CER does?

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +    :type reference: str
str --> basestring. The same below.

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +
Remove the blank line.

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +    :return: WER
"WER" --> "Word error rate."

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +        Sc is the number of character substituted,
character --> characters

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +        Dc is the number of deleted,
the number of deleted --> the number of characters deleted. 
The same below.

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +    :type reference: str
str --> basestring. For unicode is not a str, but a basestring.
The same below.

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +def cer(reference, hypophysis, squeeze=True, ignore_case=False, strip_char=''):
1. hypophysis --> hypothesis
The same below.
2. Why is strip_char necessary?

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +                    will be squeezed to one
Forgot a dot mark?

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +    :return: CER
CER --> Character error rate.

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +    :param strip_char: If not set to '', strip_char in beginning and ending of
--> If not None, leading and trailing strip_char will be removed.

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +        hypophysis = ' '.join(filter(None, hypophysis.split(' ')))
The leading and trailing whitespace will be completely "removed" by this line of codes, instead of just "squeeze to one" as explained in the function doc. Please make them consistent.

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +    :param squeeze: If set true, consecutive space character
space character --> whitespace

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +        ref_words = filter(None, reference.strip(delimiter).split(delimiter))
cer和wer中strip的处理逻辑不同，让人疑惑。建议二者都不做strip，并且去除filter_none参数，直接filter。

注意下：strip，squeeze，filter_none这几个逻辑在cer和wer中很容易让人混乱。如果某个参数没能很清楚得解释，宁可去掉该参数，而不要含糊不清地留给用户。

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +    in speech recognition. It compares a reference with an hypophysis and
1. an hypothesis --> a hypothesis.
2. Please keep this description similar to cer function doc.

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +    Calculate charactor error rate (CER). CER will compare reference text and
will compare --> compares

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +    distance = np.zeros((ref_len + 1, hyp_len + 1), dtype=np.int64)
Why int64?

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +    # initialization distance matrix
initialization --> initialize

2017-06-11 13:06 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +import numpy as np
Please add a simple module doc.

2017-06-11 13:11 UTC, xinghai-sun commented
@qingqing01 目前因为ctc_beam_search暂时实现在计算图外，所以相应的WER/CER也只能临时放到计算图外，不合适放入paddle layer/evaluator.

2017-06-12 04:37 UTC, pkuyym reviewed
Remove unnecessary parameters to keep the processing logic correct and simple.

2017-06-12 04:37 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    distance = np.zeros((ref_len + 1, hyp_len + 1), dtype=np.int64)
int32 is enough here. Done.

2017-06-12 04:37 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    # initialization distance matrix
Done.

2017-06-12 04:37 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    :return: WER
Done.

2017-06-12 04:37 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    :type reference: str
Done.

2017-06-12 04:37 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +
Done.

2017-06-12 04:37 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    Calculate charactor error rate (CER). CER will compare reference text and
Done.

2017-06-12 04:37 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +        Dc is the number of deleted,
Done.

2017-06-12 04:37 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    :type reference: str
Done.

2017-06-12 04:37 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    :param squeeze: If set true, consecutive space character
Done.

2017-06-12 04:37 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +                    will be squeezed to one
Done.

2017-06-12 04:37 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +def wer(reference, hypophysis, delimiter=' ', filter_none=True):
Done.

2017-06-12 04:37 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    in speech recognition. It compares a reference with an hypophysis and
Done.

2017-06-12 04:37 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +        ref_words = filter(None, reference.strip(delimiter).split(delimiter))
Done.

2017-06-12 04:37 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +def cer(reference, hypophysis, squeeze=True, ignore_case=False, strip_char=''):
Done.

2017-06-12 04:37 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +        Sc is the number of character substituted,
Done.

2017-06-12 04:37 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +        hypophysis = ' '.join(filter(None, hypophysis.split(' ')))
Done.

2017-06-12 10:50 UTC, xinghai-sun approved these changes

2017-06-12 10:52 UTC, xinghai-sun requested changes
Could you  please add a unit test (with both English and Mandarin test case)?

2017-06-16 09:16 UTC, xinghai-sun requested changes

2017-06-16 09:16 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +    This module provides functions to calculate error rate in different level.
-->"""This .....
Let's keep consistent across all files.

2017-06-16 09:16 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +    Calculate word error rate (WER). WER compares reference text and
--> """ Calculate

2017-06-16 09:16 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +    Calculate charactor error rate (CER). CER compares reference text and
--> """Calculate

2017-06-16 09:16 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +    :rtype: float
Add ` :raises ValueError: If reference length is zero.`

2017-06-16 09:16 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +    :rtype: float
Add `:raises ValueError: If there is zero reference words.`

2017-06-16 09:16 UTC, xinghai-sun commented on deep_speech_2/tests/test_error_rate.py
> +# -*- coding: utf-8 -*-
Add:
""" Test error rate."""
from future import absolute_import
from future import division
from future import print_function
[blank line]

2017-06-16 09:16 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +"""
Add:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

Lets keep consistent across DS2 project.

2017-06-16 09:16 UTC, xinghai-sun commented on deep_speech_2/tests/test_error_rate.py
> +sys.path.append('..')
Could we avoid using sys.path.append?

2017-06-16 09:16 UTC, xinghai-sun commented on deep_speech_2/tests/test_error_rate.py
> +        word_error_rate = error_rate.wer(ref, hyp)
Could we add more test cases?
e.g. 
self.assertTrue(error_rate.wer(ref, ref) == 0)
test if ValueError is raised if len(ref) == 0.

2017-06-18 06:33 UTC, pkuyym reviewed
Extend ci and fix unittest following comments.

2017-06-18 06:33 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    This module provides functions to calculate error rate in different level.
Done.

2017-06-18 06:33 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +"""
Done.

2017-06-18 06:33 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    Calculate word error rate (WER). WER compares reference text and
Done.

2017-06-18 06:33 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    :rtype: float
Done.

2017-06-18 06:33 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    :rtype: float
Done.

2017-06-18 06:33 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    Calculate charactor error rate (CER). CER compares reference text and
Done.

2017-06-18 06:33 UTC, pkuyym commented on deep_speech_2/tests/test_error_rate.py
> +# -*- coding: utf-8 -*-
Done.

2017-06-18 06:33 UTC, pkuyym commented on deep_speech_2/tests/test_error_rate.py
> +sys.path.append('..')
Done.

2017-06-18 06:33 UTC, pkuyym commented on deep_speech_2/tests/test_error_rate.py
> +        word_error_rate = error_rate.wer(ref, hyp)
Done.

2017-06-18 12:13 UTC, xinghai-sun approved these changes
Great job! Almost LGTM.

2017-06-18 12:13 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +
Remove Line 5.

2017-06-18 12:13 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +from __future__ import print_function
Add a blank line below Line 8.

2017-06-18 12:13 UTC, xinghai-sun commented on deep_speech_2/tests/test_error_rate.py
> +            self.assertTrue(isinstance(e, ValueError))
self.assertRaises?

2017-06-18 12:13 UTC, xinghai-sun commented on deep_speech_2/tests/test_error_rate.py
> +            self.assertTrue(isinstance(e, ValueError))
use assertRaises ?

2017-06-18 12:13 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +    :raises ValueError: If reference length is zero.
reference length --> the reference length ?

The same in the cer.

2017-06-18 12:13 UTC, xinghai-sun commented on deep_speech_2/error_rate.py
> +def levenshtein_distance(ref, hyp):
1. rename it to `_levenshtein_distance` ?
2. Add a simple description or reference for levenshtein_distance?

2017-06-19 03:32 UTC, pkuyym reviewed
Follow comments.

2017-06-19 03:32 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +
Done.

2017-06-19 03:32 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +from __future__ import print_function
Done.

2017-06-19 03:32 UTC, pkuyym commented on deep_speech_2/error_rate.py
> +    :raises ValueError: If reference length is zero.
Done.

2017-06-19 03:32 UTC, pkuyym commented on deep_speech_2/tests/test_error_rate.py
> +            self.assertTrue(isinstance(e, ValueError))
Done.

2017-06-19 03:32 UTC, pkuyym commented on deep_speech_2/tests/test_error_rate.py
> +            self.assertTrue(isinstance(e, ValueError))
Done.

2017-06-19 03:38 UTC, merged