Add reader, ParallelExecutor and refine for Transformer
PaddlePaddle/models pull request #894
Opened 2018-05-08 07:59 UTC by guoshengCS

Add reader, ParallelExecutor and refine for Transformer

2018-05-09 02:43 UTC, pkuyym requested changes

2018-05-09 02:43 UTC, pkuyym commented on fluid/neural_machine_translation/transformer/config.py
> +    # This static learning_rate will multiply LearningRateScheduler
will multiply --> will be multiplied to

2018-05-09 02:43 UTC, pkuyym commented on fluid/neural_machine_translation/transformer/reader.py
> +                key=lambda sample: max(len(sample[0]), len(sample[1])) if len(sample) > 1 else len(sample[0])
Exceed 80 columns.

2018-05-09 02:43 UTC, pkuyym commented on fluid/neural_machine_translation/transformer/reader.py
> +        """
The comments shouldn't be here. 

```
class DataReader(object):
"""Comments for the constructor"""
```

2018-05-09 02:43 UTC, pkuyym commented on fluid/neural_machine_translation/transformer/reader.py
> +        :param fpattern: The pattern to match data files.
better to give an example.

2018-05-09 02:43 UTC, pkuyym commented on fluid/neural_machine_translation/transformer/reader.py
> +        :param pool_size: The buffer size to pool data.
Size of pool buffer.

2018-05-09 02:43 UTC, pkuyym commented on fluid/neural_machine_translation/transformer/reader.py
> +        :param sort_type: The grain to sort by length: 'global' for all
duplicated.

2018-05-10 16:36 UTC, guoshengCS commented on fluid/neural_machine_translation/transformer/config.py
> +    # This static learning_rate will multiply LearningRateScheduler
Done.

2018-05-10 16:36 UTC, guoshengCS commented on fluid/neural_machine_translation/transformer/reader.py
> +                key=lambda sample: max(len(sample[0]), len(sample[1])) if len(sample) > 1 else len(sample[0])
Done.

2018-05-10 16:36 UTC, guoshengCS commented on fluid/neural_machine_translation/transformer/reader.py
> +        :param sort_type: The grain to sort by length: 'global' for all
Done.

2018-05-10 16:36 UTC, guoshengCS commented on fluid/neural_machine_translation/transformer/reader.py
> +        :param pool_size: The buffer size to pool data.
Done.

2018-05-10 16:36 UTC, guoshengCS commented on fluid/neural_machine_translation/transformer/reader.py
> +        :param fpattern: The pattern to match data files.
Done.

2018-05-17 14:28 UTC, pkuyym approved these changes
LGTM

2018-05-18 03:39 UTC, merged