Add icnet.
PaddlePaddle/models pull request #975
Opened 2018-06-11 01:18 UTC by 4luojing

2018-06-12 08:58 UTC, wanghaoshuang requested changes

2018-06-12 08:58 UTC, wanghaoshuang commented on fluid/icnet/cityscape.py
> +DATA_PATH = "../../data/cityscape"
默认路径修改为"./data/cityscape"

2018-06-12 08:58 UTC, wanghaoshuang commented on fluid/icnet/cityscape.py
> +def load(image_label):
每个方法都要给出简要说明。

2018-06-12 08:58 UTC, wanghaoshuang commented on fluid/icnet/cityscape.py
> +def train(batch_size=32, random_mirror=False, random_scaling=False):
对外暴露的方法要给出详细使用说明。

2018-06-12 08:58 UTC, wanghaoshuang commented on fluid/icnet/infer.py
> +    fluid.layers.Print(predict, summarize=10)
去掉Print语句

2018-06-12 08:58 UTC, wanghaoshuang commented on fluid/icnet/network.py
> +def conv(input, k_h, k_w, c_o, s_h, s_w, relu=True, padding="VALID", group=1, biased=None, name=None, print_pad=False):
如果`group`没有被用到，建议将其从参数列表删除。

2018-06-12 08:58 UTC, wanghaoshuang commented on fluid/icnet/network.py
> +def conv(input, k_h, k_w, c_o, s_h, s_w, relu=True, padding="VALID", group=1, biased=None, name=None, print_pad=False):
`print_op` 貌似也是多余的。

2018-06-12 08:58 UTC, wanghaoshuang commented on fluid/icnet/network.py
> +    return fluid.layers.upsampling_bilinear2d(input, out_shape=out_shape)
最新paddle api已经将`upsampling_bilinear2d `重命名为`resize_bilinear`

2018-06-12 08:58 UTC, wanghaoshuang commented on fluid/icnet/network.py
> +
空行太多。

2018-06-14 01:39 UTC, lgone2000 commented
能否在image-segmentatation 建立一个子目录?便于未来扩展? by guoyi

2018-06-14 09:43 UTC, qingqing01 commented
@lgone2000 good idea.

2018-06-14 09:46 UTC, wanghaoshuang commented on fluid/icnet/README.md
> +本文采用Cityscape数据集，请前往[Cityscape官网]()注册下载。下载数据之后，按照[这里](https://github.com/mcordts/cityscapesScripts)的说明和工具处理数据。
官网地址补充完整。

2018-06-14 09:46 UTC, wanghaoshuang commented on fluid/icnet/eval.py
> +    fluid.io.load_persistables(exe, args.model_path)
对于evaluator来说，只load parameter就行。

2018-06-14 09:46 UTC, wanghaoshuang commented on fluid/icnet/eval.py
> +    print "loaded model from: %s" % args.model_path
判断下model_path是否存在。

2018-06-14 09:46 UTC, wanghaoshuang commented on fluid/icnet/eval.py
> +        print "count: %s; current iou: %.3f;" % (count, result[0])
建议在同行输出。

2018-06-14 09:46 UTC, wanghaoshuang commented on fluid/icnet/eval.py
> +def cal_mean_iou(wrong, cerroct, num_classes):
cerroct -> correct

2018-06-14 09:46 UTC, wanghaoshuang commented on fluid/icnet/eval.py
> +    return (cerroct.astype("float64") / sum).sum() / num_classes
如果class i 从来没出现过，那么`sum[i]`就是0, 不能直接除；最后求平均也要除真实出现的class数量。

另外num_classes == len(num_classes), 所以可以去掉num_classes这个参数。

2018-06-14 09:46 UTC, wanghaoshuang commented on fluid/icnet/infer.py
> +add_arg('out_path',          str,   "",         "Output path.")
给个默认的out_path. 其它路径也给个默认值。

2018-06-14 09:46 UTC, wanghaoshuang commented on fluid/icnet/infer.py
> +def color(input):
说明下方法的作用

2018-06-14 09:46 UTC, wanghaoshuang commented on fluid/icnet/infer.py
> +    fluid.io.load_persistables(exe, args.model_path)
load parameter既可

2018-06-14 09:46 UTC, wanghaoshuang commented on fluid/icnet/infer.py
> +        cv2.imwrite(args.out_path + "/" + filename + "_result.png", color(result[0]))
如果`args.out_path`不存在，需要新建一个。

2018-06-14 10:12 UTC, qingqing01 commented on fluid/icnet/README.md
> +- https://zhuanlan.zhihu.com/p/26653218
参考文献给知乎不够严谨， 只保留一篇paper就行了？

2018-06-14 10:12 UTC, qingqing01 commented on fluid/icnet/README.md
> +</p>
有mean IoU的结果吗？

2018-06-14 10:12 UTC, qingqing01 commented on fluid/icnet/README.md
> +Image Cascade Network（ICNet），在兼顾实时性的同时，比原来的Fast Semantic Segmentation,比如SQ, SegNet, ENet等大大地提高了准确率，足以与Deeplab v2媲美，给语义分割的落地提供了可能。
这段中文和后面链接里知乎的中文相同，需要修改。

2018-06-14 10:12 UTC, qingqing01 commented on fluid/icnet/README.md
> +ICNet利用了低分辨率图片的高效处理和高分辨率图片的高推断质量两种优点。主要思想是：让低分辨率图像经过整个语义网络输出一个粗糙的预测，然后利用文中提出的级联融合单元来引入中分辨率和高分辨率图像的特征，从而逐渐提高精度。整个网络结构如下：
同上，和知乎的中文描述相同，需要修改。

2018-06-14 10:12 UTC, qingqing01 commented on fluid/icnet/README.md
> +本文采用Cityscape数据集，请前往[Cityscape官网]()注册下载。下载数据之后，按照[这里](https://github.com/mcordts/cityscapesScripts)的说明和工具处理数据。
进入https://github.com/mcordts/cityscapesScripts 这个链接里，一眼看去，看不懂如何处理数据，我们这里可以提供处理脚本吗？

2018-06-14 10:12 UTC, qingqing01 commented on fluid/icnet/cityscape.py
> +    reader = paddle.reader.map_readers(mask, reader)
这里不需要这么多的 `paddle.reader.map_readers`吧，这样比较难以理解。

load, flip, resize, scale, to_chw， 组batch都可以封装到DataGenerater里吧。

也可以参考 https://github.com/PaddlePaddle/models/blob/develop/fluid/image_classification/reader.py。

2018-06-14 10:12 UTC, qingqing01 commented on fluid/icnet/cityscape.py
> +    reader =  paddle.reader.map_readers(test_process, reader)
不需要两个 `paddle.reader.map_readers`吧。

2018-06-14 10:12 UTC, qingqing01 commented on fluid/icnet/infer.py
> +    predict = fluid.layers.upsampling_bilinear2d(sub124_out, out_shape=data_shape[1:3])
upsampling_bilinear2d -> resize_bilinear

2018-06-14 10:12 UTC, qingqing01 commented on fluid/icnet/infer.py
> +
因为网络中有BN，需要：

`inference_program = fluid.default_main_program().clone(for_test=True) `

下面83行的exe运行这个 inference_program

2018-06-14 10:12 UTC, qingqing01 commented on fluid/icnet/network.py
> +    sub24_out = conv(sub24_sum_interp, 1, 1, num_classes, 1, 1, biased=True, relu=False, name="sub24_out")
上面网络可以模块化的写下吗？ 现在看着网络特别复杂。

2018-06-14 10:12 UTC, qingqing01 commented on fluid/icnet/network.py
> +import paddle.fluid as fluid
network.py 有更精确的名字吗？

2018-06-14 10:17 UTC, qingqing01 commented
https://travis-ci.org/PaddlePaddle/models/builds/390560755?utm_source=github_status&utm_medium=notification 

另外，code style没过，需要安装 pre-commit : http://www.paddlepaddle.org/docs/develop/documentation/fluid/zh/dev/contribute_to_paddle_cn.html#permalink-5--pre-commit-

2018-06-18 15:16 UTC, 4luojing commented
已按review修改代码。请@wanghaoshuang @qingqing01 确认。

2018-06-19 14:49 UTC, wanghaoshuang approved these changes
LGTM. 不知道 @qingqing01  还有什么意见么？

2018-06-21 03:26 UTC, merged