add augmentation part
PaddlePaddle/models pull request #99
Opened 2017-06-14 19:14 UTC by chrisxu2016

resolve #96
- [x] add data augmentation class ,inclued `noise_speech`, `impuls_response`, `resampler`, `speed_perturb`, `online_bayesias_normalization`.
- [x] add function to audio.py, eg. `convolve`， `add_noise`, `normalizer`

2017-06-15 11:48 UTC, xinghai-sun requested changes
Good job, but still needs intensive improvement.

Only reviewed for `audio.py` before Line 398. 

1. Please pay more attention to the details, especially for the docs.  Remember an old saying "Devil is in the details! ".

2. Please avoid copying codes from somewhere without a fully understanding about it. It would be better if we could improve it, or at least make it cleaner. The same thing goes to docs.

3. Please add unit tests or at least test every function before commit. If the project is urgent, some delay for the unit test would be acceptable. But at least, every function must be tested by the author before commit. For the audio parts, the tests should  also include writing the transformed audio into a wav file and then we listen to the wav file to make sure such transformation functions correctly. If we have time, a timely added unit test would be great!

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +import scikits.samplerate
Add the package "scikits" and "scipy" to requirements.txt. Make sure they can be installed by `pip install -r requirements.txt`.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +    def slice_from_file(cls, fname, start=None, end=None):
fname --> file
Please avoid using too many abbreviation if the full name is not too long.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        Loads a small section of an audio without having to load
Put Line 70 into Line 69.
The same below.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :param fname: input audio file name
"input audio file name." --> "Input audio filepath."
Note the upper case and an ending dot mark.

The same below.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +            If start is negative, it wraps around from the end. If not
1. Improper indent. Please make "If" align with "Start". The same below.
2. Remove "(supported granularity is ms )".

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +            format.
Don't forget :rtype:

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +
Remove the blank Line 84.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +
Remove the blank Line 89.
Please avoid using too many blank lines, unless it is really necessary.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        if sndfile.channels != 1:
We need to support multi-channel audio, just as `from_file(cls, file)` does.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +
Remove the blank Line 93.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +
Remove the blank line 100.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +
Remove the blank line 105, 112, 117, 122.
Why so many blank lines? Please use it only when it can significantly improve readability.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +            raise IndexError("The slice start position ({} s) is out of "
1. IndexError --> ValueError
2. "The slice start position ({} s) is out of bounds Filename: {}".format(end.fname)
--> "The slice start position (%f s) is out of bounds. Filename: %s" % (end, fname)
It is not an error, but let's just keep the format consistent throughout the DS2 project.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :param duration: length of silence in seconds
Remind again: length of silence in seconds --> Length of silence in seconds.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :type duration: scalar
scalar --> float.
The same below.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        samples = np.zeros(int(float(duration) * sample_rate))
float() is not necessary.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +    def concatenate(cls, *segments):
Please overload all classmethods from AudioSegment in SpeechSegment.
AudioSegment里面实现的@classmethod，都需要在SpeechSegment里重载，否则调用时返回的不是SpeechSegment类型，有点误导人。

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :type *segments: [AudioSegment]
remove [ ]

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        if N == 0:
A short version:
if len(segments) == 0:

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        if start is None:
Make it one line: `start = 0. if start is None else start`.
The same below.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :type *segments: [AudioSegment]
If it is a public method, please add doc about exceptions, e.g.
`:raises ValueError:  If number of segments is zero; if xxxxx.`

Please also add them in other public methods.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        """Normalize audio to desired RMS value in decibels.
to desired --> to the desired

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        """
Don't forget return and rtype.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :param target_db: Target RMS value in decibels.This value
Please put a whitespace before 'This'. Be careful about these details.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :type target_db: float, optional
Please remove ", optional".

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :type max_gain_db: float, optional
Please remove ", optional".

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :raises NormalizationWarning: if the required gain to normalize the
We don't have NormalizationWarning, --> ValueError.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +            for normalization.  This is to prevent nans when attempting
Here, before "This", there are two whitespace!

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        gain = min(max_gain_db, target_db - self.rms_db)
Remove "gain = min(max_gain_db, target_db - self.rms_db)".

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        Normalize audio using a production-compatible online/causal algorithm.
--> """Normalize ...

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        online estimates of the RMS even when there are very few samples.
Could you please explain it with math formula or add any paper link?

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :type target_bd: scalar
scalar --> float

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +            seconds before applying online normalization.
`prior_samples`, `prior_db` and `startup_delay`  are difficult to understand. Could you please explain them in more details ?

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +                       max_gain_db=300.0):
If normalize_ewma is not used or fully understood by us, please remove it. Otherwise, give detailed explanation.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        This resamples the audio to a new sample rate and returns a brand
"returns a brand. The existing AudioSegment is unchanged."  This doc is different from the code here.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        self._samples = new_samples
Is it still float32 after resampling ?

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        self._sample_rate = new_sample_rate
`new_sample_rate` is not defined!
Please test you code before committing !!!
Please also add unittests for all.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :param new_sample_rate: target sample rate
What is "new_sample_rate"? You have only "target_sample_rate"!

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        Note that this is an in-place transformation.
Please be careful about the doc's coding style (Upper case, dot mark, proper indent), as mentioned above.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :type sides: basestring
Here, unicode is not possible. So basestring --> str. Use basestring Only when both unicode and str are supported.

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +            raise ValueError("Unknown value for the kwarg 'sides'")
--> raise ValueError("Unknown sides value %s." % sides)

2017-06-15 11:48 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        """Return new AudioSegment containing audio between given boundaries.
This doc is different from the codes: not "return ....".

2017-06-16 07:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +import scikits.samplerate
Done

2017-06-16 07:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +    def slice_from_file(cls, fname, start=None, end=None):
Done

2017-06-16 07:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        Loads a small section of an audio without having to load
Done

2017-06-16 07:23 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :param fname: input audio file name
Done

2017-06-16 07:23 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +            If start is negative, it wraps around from the end. If not
Done

2017-06-16 07:23 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +
Done

2017-06-16 07:23 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +            format.
Done

2017-06-16 07:23 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +
Done

2017-06-16 07:23 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        if sndfile.channels != 1:
Done

2017-06-16 07:23 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +
Done

2017-06-16 07:23 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        if start is None:
Done

2017-06-16 07:23 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +
Done

2017-06-16 07:23 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +
Done

2017-06-16 07:24 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +            raise IndexError("The slice start position ({} s) is out of "
Done

2017-06-16 07:24 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :param duration: length of silence in seconds
Done

2017-06-16 07:24 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :type duration: scalar
Done

2017-06-16 07:24 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        samples = np.zeros(int(float(duration) * sample_rate))
Done

2017-06-16 07:24 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +    def concatenate(cls, *segments):
Done

2017-06-16 07:24 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :type *segments: [AudioSegment]
Done

2017-06-16 07:24 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :type *segments: [AudioSegment]
Done

2017-06-16 07:24 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        """
Done

2017-06-16 07:24 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        if N == 0:
Done

2017-06-16 07:24 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        """Normalize audio to desired RMS value in decibels.
Done

2017-06-16 07:24 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :param target_db: Target RMS value in decibels.This value
Done

2017-06-16 07:25 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :type target_db: float, optional
Done

2017-06-16 07:25 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        self._samples = new_samples
Done

2017-06-16 07:25 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        Note that this is an in-place transformation.
Done

2017-06-16 07:25 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +            for normalization.  This is to prevent nans when attempting
Done

2017-06-16 07:25 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :type max_gain_db: float, optional
Done

2017-06-16 07:25 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :raises NormalizationWarning: if the required gain to normalize the
Done

2017-06-16 07:25 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        gain = min(max_gain_db, target_db - self.rms_db)
Done

2017-06-16 07:25 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        Normalize audio using a production-compatible online/causal algorithm.
Done

2017-06-16 07:26 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        online estimates of the RMS even when there are very few samples.
There is no description in the speech-dl code

2017-06-16 07:27 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :type target_bd: scalar
done

2017-06-16 07:38 UTC, chrisxu2016 reviewed
I have rewrite the audio.py file to make it more formal. But there is still a problem, bayesias normalize not found in the speech_dl code related to the introduction. The part of the code will not affect other functions when delete it.

2017-06-16 07:42 UTC, chrisxu2016 reviewed
I have tested every function in audio.py，the unit test test script will be pushed later

2017-06-16 11:11 UTC, xinghai-sun requested changes
Still needs improvement.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +                            .format(type(other)))
-->`raise TypeError("Cannot add segments of different types: %s and %s." % (type(self), type(other)))`

As mentioned in last review, do not use two kinds of string formatting methods.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        """Returns length of segment in samples."""
Returns --> Return

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +    def concatenate(self, *segments):
Make it a classmethod: 
```
@classmethod
def concatenate(cls, *segment):
```

Please also overload it for SpeechSegment.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +            if type(seg) is not type(self):
type(self) --> cls

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        return type(self)(samples, sample_rate)
type(self) --> cls

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :return: Audio segment instance.
--> `Audio segment instance as concatenating results."

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :param *segments: Input audio segments
--> "Input audio segments to be concatenated."

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :type *segments: AudioSegment
Type of `*segment` is not  AudioSegment, but a tuple.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +    def __len__(self):
Ambiguous: num_samples or duration.
Remove it.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +                      added in.
Why a newline for L59? 
If 80 columns is enough, do not start a new line.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +            raise TypeError("Sample rates must match to add segments.")
Not TypeError！

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +            raise TypeError("Segment lengths must match to add segments.")
Not TypeError again!

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +    def __add__(self, other):
Ambiguous for users : concatenate or superimpose?
Do not use `__add__`, please rename it.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :param file: Input audio filepath
1. A dot mark!
2. Input audio filepath or file object.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +    def slice_from_file(self, file, start=None, end=None):
1. Overload it for SpeechSegment.
2. Make this a classmethod.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :return: The specified slice of input audio in the audio.AudioSegment format.
--> AudioSegment instance of the specified slice of  the input audio file.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :rainse ValueError: If the position is error, or if the time is out bounds.
1. rainse --> raises. Please be careful!
2. --> If `start` or `end` is incorrectly set, e.g. out of bounds in time.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :type file: basestring
--> basestring|file
It could also be a file-like object.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +                             "bounds. Filename: %s" % (start, file))
Remove " Filename ... " and the same below.
`file` could also be a file object.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        return type(self)(data, sample_rate)
type(self) --> cls

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +    def make_silence(self, duration, sample_rate):
1. Make it a classmethod.
2. Overload it in SpeechSegment.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :param duration: Length of silence in seconds
A dot mark!

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :param sample_rate: Sample rate
Dot mark again!
Please check elsewhere before commit!

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :return: Silence of the given duration
--> Silent AudioSegment instance of the given duration.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        """Normalize audio to be desired RMS value in decibels.
--> to be of the desired ...

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        sample rate.
-->`"""Resample the audio to a target sample rate".

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :type quality: basestring
basestring --> str

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        """Pads this audio sample with a period of silence.
Pads --> Pad

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :raises ValueError: If the sides not surport
-->  If `sides` is not supported.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :param allow_downsampling: whether to allow the noise signal to be downsampled
whether-->Wether

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :type allow_downsampling: boolean
boolean --> bool

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :type rng: random.Random
--> None|random.Random

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +                             (noise.sample_rate, self.sample_rate))
Convert L483-L485 to two lines. The same below.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        noise_gain_db = min(max_gain_db, noise_gain_db)
L490-491 --> `noise_gain_bd = min(self.rms_db - noise.rms_db - snr_dB, max_gain_bd)

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        output = self + self.tranform_noise(noise_subsegment, noise_gain_db)
We already have `def apply_gain(...)`.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +    def tranform_noise(self, noise_subsegment, noise_gain_db):
Remove this, use `apply_gain` instead.

2017-06-16 11:11 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :param allow_resample: indicates whether resampling is allowed when
indicates --> Indicates

2017-06-18 10:22 UTC, chrisxu2016 reviewed
Resolved the above mentioned problem

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        """Return new AudioSegment containing audio between given boundaries.
Done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +    def __len__(self):
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        """Returns length of segment in samples."""
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +    def __add__(self, other):
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +                      added in.
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +                            .format(type(other)))
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +            raise TypeError("Sample rates must match to add segments.")
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +            raise TypeError("Segment lengths must match to add segments.")
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +    def concatenate(self, *segments):
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :param *segments: Input audio segments
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :type *segments: AudioSegment
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :return: Audio segment instance.
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +            if type(seg) is not type(self):
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        return type(self)(samples, sample_rate)
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +    def slice_from_file(self, file, start=None, end=None):
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :param file: Input audio filepath
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :type file: basestring
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :return: The specified slice of input audio in the audio.AudioSegment format.
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :rainse ValueError: If the position is error, or if the time is out bounds.
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +                             "bounds. Filename: %s" % (start, file))
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        return type(self)(data, sample_rate)
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +    def make_silence(self, duration, sample_rate):
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :param duration: Length of silence in seconds
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :param sample_rate: Sample rate
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :return: Silence of the given duration
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        """Normalize audio to be desired RMS value in decibels.
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        sample rate.
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :type quality: basestring
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        """Pads this audio sample with a period of silence.
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :raises ValueError: If the sides not surport
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :param allow_resample: indicates whether resampling is allowed when
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :param allow_downsampling: whether to allow the noise signal to be downsampled
done Whether

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :type allow_downsampling: boolean
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :type rng: random.Random
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +                             (noise.sample_rate, self.sample_rate))
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        noise_gain_db = min(max_gain_db, noise_gain_db)
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        output = self + self.tranform_noise(noise_subsegment, noise_gain_db)
done

2017-06-18 10:22 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +    def tranform_noise(self, noise_subsegment, noise_gain_db):
done

2017-06-18 13:08 UTC, xinghai-sun requested changes
Almost LGTM.

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :raises TypeError: If every item in segments is not AudioSegment
every item in segments --> any segment

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +                            sample_rate of any two segment does not match.
two segment --> segments

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +                                "instance can be concatenated.")
remove "instance"

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        sample rate.
Is one line enough for the whole sentence?

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +    def superimposed(self, other):
superimposed --> superimpose ?

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +
Add "Note that this is an in-place transformation."

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +                           the length of segments don't match.
length --> lengths ?

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :raise ValueError: If the sample_rate of two segments not equal, or if
sample_rate--> sample rates
not equal --> are not equal
two segments --> the two segments

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :param dtype: Data type for export samples. Options: 'int16','int32',
Add a whitespace between `'int16',` and `'int32'`.

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +            raise ValueError("Unknown value for the kwarg %s" % sides)
the kwarg --> sides

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        """Return new AudioSegment containing audio between given boundaries.
Modify this sentence, since the function has no return.

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +            end_sec = self.duration + end_sec
Should we have more checks about the start_sec and end_sec, e.g. if they are out of bounds in time, just like `slice_from_file` ?

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        :raises ValueError: If the length of subsegment greater than
greater --> is greater

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +                            origineal segemnt.
origineal segemnt --> the original segment

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        """Convolve this audio segment with the given impulse_segment.
impulse_segment --> impulse segment.

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        """Adds the given noise segment at a specific signal-to-noise ratio.
Adds --> Add

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/audio.py
> +        noise.random_subsegment(self.duration, rng=rng)
Add `noise_new = copy.deepcopy(noise)`, and then perform transformation on `noise_new`, otherwise the input `noise` will be modified.

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/speech.py
> +        """Concatenate an arbitrary number of speech segments together.
Add "Both audio and transcript will be concatenated."

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/speech.py
> +        :raises TypeError: If every item in segments is not SpeechSegment
every item in segments --> any segment

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/speech.py
> +        sample rate.
Add "Transcript will be an empty string.".

2017-06-18 13:08 UTC, xinghai-sun commented on deep_speech_2/data_utils/speech.py
> +    def slice_from_file(cls, filepath, start=None, end=None, transcript=""):
It would be better for `transcript` to have no default value.

2017-06-18 16:08 UTC, chrisxu2016 reviewed
fix all problem

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +                            sample_rate of any two segment does not match.
Done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :raises TypeError: If every item in segments is not AudioSegment
Done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +                                "instance can be concatenated.")
Done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        sample rate.
Done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +    def superimposed(self, other):
Done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +
Done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :raise ValueError: If the sample_rate of two segments not equal, or if
Done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +                           the length of segments don't match.
Done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :param dtype: Data type for export samples. Options: 'int16','int32',
Done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +            raise ValueError("Unknown value for the kwarg %s" % sides)
Done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        """Return new AudioSegment containing audio between given boundaries.
Done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +            end_sec = self.duration + end_sec
Done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        :raises ValueError: If the length of subsegment greater than
Done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +                            origineal segemnt.
done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        """Convolve this audio segment with the given impulse_segment.
done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        """Adds the given noise segment at a specific signal-to-noise ratio.
done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/audio.py
> +        noise.random_subsegment(self.duration, rng=rng)
done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/speech.py
> +        """Concatenate an arbitrary number of speech segments together.
done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/speech.py
> +        :raises TypeError: If every item in segments is not SpeechSegment
done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/speech.py
> +    def slice_from_file(cls, filepath, start=None, end=None, transcript=""):
done

2017-06-18 16:08 UTC, chrisxu2016 commented on deep_speech_2/data_utils/speech.py
> +        sample rate.
done

2017-06-19 07:28 UTC, xinghai-sun approved these changes
LGTM

2017-06-19 07:30 UTC, merged